### ISSUE TITLE
Im unsure on how to compile Floodgate properly

### ISSUE THREAD

**Issue by ChieflyDevon** [GeyserMC/Floodgate#10]
I've tried for a couple hours and i cant seem to figure it out.

**Comment by RednedEpic** [comment]
See #5.

**Comment by ChieflyDevon** [comment]
sorry i havent ever compiled stuff like this so how would i go about building Floodgate into a jar file for a bucket server ?

**Comment by RednedEpic** [comment]
> sorry i havent ever compiled stuff like this so how would i go about building Floodgate into a jar file for a bucket server ?

Download maven and run `mvn clean install` when in the Geyser directory. Afterward, do the same thing in the Floodgate directory. 

If you’ve never worked with maven before, see: https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html.

**Comment by ChieflyDevon** [comment]
Thank you ! ill give it a try

**Comment by ChieflyDevon** [comment]
Ive just downloaded the geyser Github project and run mvn clean install while in the geyser directory and that worked fine and it built successfully. However when i then went into the directory i have downloaded for the Floodgate Project and attempt to run mvn clean install in its directory i run into the Error Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project floodgate-common: Compilation failure

**Comment by RednedEpic** [comment]
> Ive just downloaded the geyser Github project and run mvn clean install while in the geyser directory and that worked fine and it built successfully. However when i then went into the directory i have downloaded for the Floodgate Project and attempt to run mvn clean install in its directory i run into the Error Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project floodgate-common: Compilation failure

That normally would mean that you didn’t run the mvn clean install command in the Geyser directory, but could you paste the full error in hastebin from when you try to build Floodgate?

**Comment by ChieflyDevon** [comment]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.319 s
[INFO] Finished at: 2020-03-09T23:56:54Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project floodgate-common: Compilation failure
[ERROR] /C:/Users/Owner/Documents/Custom Minecraft model/Floodgate-development/common/src/main/java/org/geysermc/floodgate/FloodgatePlayer.java:[40,25] cannot find symbol
[ERROR]   symbol:   method getBedrockId()
[ERROR]   location: variable data of type org.geysermc.floodgate.util.BedrockData
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :floodgate-common
PS C:\Users\Owner\Documents\Custom Minecraft model\Floodgate-development>

**Comment by RednedEpic** [comment]
Redownload both Floodgate and Geyser and try rebuilding.

**Comment by ChieflyDevon** [comment]
Thank you that seems to have fixed the mvn clean install now i just need to attempt to package it. When running mvn package is there a certain file directory the .jar file is outputted ?

**Comment by RednedEpic** [comment]
> Thank you that seems to have fixed the mvn clean install now i just need to attempt to package it. When running mvn package is there a certain file directory the .jar file is outputted ?

Yeah. It’ll be in the target folder of the platform you want (e.g. `bukkit/target/floodgate-bukkit.jar`).

**Comment by ChieflyDevon** [comment]
Ah found it thank you for the help!
