### ISSUE TITLE
/linkaccount requires xbox-achievements-enabled: false

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [GeyserMC/Floodgate#100]
Is it possible to allow the use of `/linkaccount` while `xbox-achievements-enabled: true`?

Right now, we get the `Cheats are not enabled in this level` error when trying to link accounts until that setting is toggled. (And it does _not_ seem to get picked up by `/reload` — we have to restart the whole server to toggle it.)

**Comment by Camotoy** [comment]
Unfortunately this is a Bedrock limitation, not a Geyser limitation. Bedrock blocks all commands in order to prevent cheating. A workaround is present in this plugin made by a community member: https://www.spigotmc.org/resources/customcommandprefix.87224/

**Comment by JamesTheAwesomeDude** [comment]
Does [this wiki change](https://github.com/GeyserMC/Geyser/wiki/Floodgate/_compare/db96d7758ff15f8cc4c49ea508ede296424a4f4f...b77c779efecdd45a741da43e9d1bcda82871b7eb) take care of it appropriately?

**Comment by Camotoy** [comment]
I'm not sure if that is necessary as https://github.com/GeyserMC/Geyser/commit/7cefb5713e0aaf366fde30389998baf02854b9b8 finally clarifies what enabling Xbox achievements does. Therefore I may move that link to our configuration wiki page. Regardless, thank you for adding it and alerting me.
