### ISSUE TITLE
can't send form 

### ISSUE THREAD

**Issue by RhythmNz** [GeyserMC/Floodgate#102]
can't send form

**Comment by Tim203** [comment]
First of all I need to know if you're using my Floodgate 2.0 fork, if you don't: it's not implemented yet. If you do: please send your code and the error.

**Comment by Tim203** [comment]
First of all I need to know if you're using my Floodgate 2.0 fork, if you don't: it's not implemented yet. If you do: please send your code and the error.

**Comment by RhythmNz** [comment]
where can I get floowgate 2.0

**Comment by Tim203** [comment]
It's here: https://github.com/Tim203/Floodgate . You also need my Geyser fork: https://github.com/Tim203/Geyser .
If you don't know how to compile it you're better of waiting until 2.0 comes out publically.

**Comment by Tim203** [comment]
Duplicate of #36 and is implemented in the upcoming 2.0
