### ISSUE TITLE
The skins .. 

### ISSUE THREAD

**Issue by iSilviu-debug** [GeyserMC/Floodgate#107]
**I have a question** 
In my server I am using a version of floodgate which uses skins: ALEX AND STEVE. One question: in this version I use the cracked uuids directly from the floodgate 1.0 config. Is that a problem? Will the skins be fixed anyway? 

**Other**
Tim, you are very good cactus 🌵

**Comment by Chew** [comment]
Skins don't show up on Floodgate mode (this is planned on being fixed). Offline mode never shows any, to begin with.

**Comment by iSilviu-debug** [comment]
capisco, sfortunatamente non posso neanche usare la modalità offline perché gli utenti perderanno gli oggetti.

**Comment by Tim203** [comment]
> Tim, you are very good cactus 🌵

hehe

This is something that has been added in Floodgate 2.0, I'll close the issue for the milestone progress.
