### ISSUE TITLE
Wiki Incorrect

### ISSUE THREAD

**Issue by mepaddy** [GeyserMC/Floodgate#110]
I'm creating a Spigot plugin, and would like to use the FloodgateAPI to, among other things, send a form to players connected via Geyser. Using the instructions on [https://github.com/GeyserMC/Floodgate/wiki/Forms](url), I created a ModalForm, but the instructions to send it do not work. `FloodgateApi.getInstance()` does not exist, so I can't use `FloodgateApi#sendForm(UUID, Form)`. Also, `FloodgatePlayer#sendForm(Form)` does not exist either. The class `FloodgateApi` doesn't exist either, so I was using `FloodgateAPI` for all of my code. Not sure if this is just a typo or not. Is the wiki outdated or wrong, or is there something I'm missing here? Any help with this would be great!

**Comment by Tim203** [comment]
The wiki is ahead of the master branch.
I'm currently working on Floodgate 2.0, and the wiki pages are based of the 2.0 (which is still in development).
A lot of the features are only available in the 2.0, so I recommend using the 2.0 if you can't find what you're looking for. For that you'll need my Geyser fork and my Floodgate fork: https://github.com/Tim203/Floodgate https://github.com/Tim203/Geyser

**Comment by mepaddy** [comment]
Thank you!
