### ISSUE TITLE
Add a way to get the Skin of a Bedrock player

### ISSUE THREAD

**Issue by Tydium** [GeyserMC/Floodgate#111]
**What feature do you want?**
Skin Pulling through api. I think it would be cool if floodgate can download skins from the players skin on bedrock. (Oh I forgot to mention this is going to be for floodgate 2.0) My main reason for asking for this is to recreate one of those "Top Player" Npc Leaderboards.

**Alternatives?**
List any alternatives you might have tried

**Comment by Tim203** [comment]
While I can't promise it, it'll be very likely that you'll be able to do something like that in Floodgate 2.0

**Comment by Tim203** [comment]
While I can't promise it, it is very likely that you'll be able to do something like that in Floodgate 2.0

**Comment by Carbonixx** [comment]
Hiya, I have found a very... bandaid like approach to this. SkinsRestorer allows players to use the /skin command to change their skin, this also updates on the bedrock client although it is required for the command to be done twice for it to work, additionally, player models can mess up drastically during this but only requires a client restart.

**Comment by Tydium** [comment]
I ended up using Geyser Skin Manager. It works like a charm. Persona skins dont work yet on it but it works for most of the skins generally. I instantly killed Skins restorer with geyser skin manager

**Comment by Tim203** [comment]
GeyserSkinManager was made as a temporary solution until Floodgate 2.0 was released. Floodgate 2.0 also supports persona skins.

I worked on this specific feature request a few days ago and the API part is functional now.
I'll close the issue for the milestone progress.
