### ISSUE TITLE
Windows 10 player crashing when joining Java server

### ISSUE THREAD

**Issue by GidationBoy** [GeyserMC/Floodgate#112]
When my friend tried joining my java edition server, his game crashed every time.

**Comment by Camotoy** [comment]
This is probably a Geyser issue unless it doesn't happen if Floodgate is not used.

We can't do anything with this information without more context - perhaps copy Geyser's bug report issue template and paste it here, filling it in with your situation.

**Comment by GidationBoy** [comment]
I am using floodgate with Geyser. Where do I find Geyser's bug reports?

**Comment by Camotoy** [comment]
https://github.com/GeyserMC/Geyser/issues

**Comment by LordSiix** [comment]
# Disabling this will prevent command suggestions from being sent and solve freezing for Bedrock clients.
command-suggestions: false
