### ISSUE TITLE
Bad Packet

### ISSUE THREAD

**Issue by CooperRules** [GeyserMC/Floodgate#114]
Hey. Running Geyser with floodgate on a paper server, no bungee or velocity. I keep getting the same error, [Geyser-Spigot] Downstream packet error! Invalid packet id: 25

https://dump.geysermc.org/2SbYWjE92adV83QfRNVJ53fFhIxpV8Fu

**Comment by Konicai** [comment]
This is likely either an issue with your floodgate setup or ProtocolSupport. You can come to the Geyser [discord](http://discord.geysermc.org/). Feel free to `@konica`.

**Comment by Tim203** [comment]
I expect that this issue has been resolved in the discord.
If not, feel free to join the discord. Like Konicai said: this is mostlikely an issue with your Floodgate setup.
