### ISSUE TITLE
Steve issue

### ISSUE THREAD

**Issue by GidationBoy** [GeyserMC/Floodgate#116]
When I load into my server on bedrock, I noticed that with the **first few seconds**, their where Steve skins above placed custom heads also the other players online would have a Steve skin also.

Please Fix.

**Comment by Camotoy** [comment]
This is a Geyser issue as skulls and skins are loaded in - it has nothing to do with this plugin. This is a "won't fix" simply because it's not something we can "fix" unless there's a specific area we're able to identify that's a slowdown.

**Comment by Camotoy** [comment]
If you post in the Geyser repository, you will get the same answer and a request to follow the issue template.

**Comment by GidationBoy** [comment]
Is there any way to fix it?
