### ISSUE TITLE
Account linking

### ISSUE THREAD

**Issue by ttarik2** [GeyserMC/Floodgate#118]
I have installed Geyser as a plugin on a (Spigot) server and I am trying to link my Java and Bedrock accounts, and I am having trouble doing so.

Firstly, how do I disable xbox-achievements-enabled? Also, when I do the /linkaccount command I am getting a message saying '_Linking is not enabled on this server_.'

Also, will it cause any issues if my Bedrock and Java usernames are exactly the same?

Thanks for any help on this. It is really appreciated!

**Comment by Tim203** [comment]
> Firstly, how do I disable xbox-achievements-enabled

That's part of the Geyser config

> Also, when I do the /linkaccount command I am getting a message saying 'Linking is not enabled on this server.'

You have to enable account linking in your Floodgate config

> Also, will it cause any issues if my Bedrock and Java usernames are exactly the same?

No it wont cause any issues, unless you don't use a prefix for Floodgate players, which is not recommended.

**Comment by ttarik2** [comment]
I haven't figured out how to disable it through the Geyser config and the Floodgate. I am not used to this kind of stuff. 😅
If you or anyone else can walk me through how it would be greatly appreciated. 

Good to know the usernames won't cause issues though! 😄

**Comment by LichLord91** [comment]
https://github.com/GeyserMC/Geyser/wiki/Floodgate

https://github.com/GeyserMC/Geyser/wiki/Setup

**Comment by ttarik2** [comment]
Thanks for the help!
