### ISSUE TITLE
"You are not whitelisted on this server."

### ISSUE THREAD

**Issue by NoodlyBoi101** [GeyserMC/Floodgate#121]
I am running a server on 1.16.5 Spigot. I have Geyser-Spigot and Floodgate-bukkit installed on the server. I do have a whitelist but I had it turned it off but it still will not allow bedrock players to join giving them the message they aren't whitelisted.

**Comment by Tim203** [comment]
This doesn't look like a Floodgate issue, since we don't check the whitelist ourselves.
