### ISSUE TITLE
Whitelist command bug in console

### ISSUE THREAD

**Issue by Konicai** [GeyserMC/Floodgate#124]
Running the whitelist command in console returns an error and stacktrace about object casting. Nevertheless the whitelist entry is successfully created. 

Logs: https://pastebin.com/rfSMqHVe

Dump: https://dump.geysermc.org/gHL4RzYs9QDKAOa4i61FXwJ6eHGAn0LZ

**Comment by Chew** [comment]
Affected method:

https://github.com/GeyserMC/Floodgate/blob/dev/2.0/spigot/src/main/java/org/geysermc/floodgate/util/SpigotCommandUtil.java#L165-L172

Thank you for the report!

**Comment by Konicai** [comment]
`fwhitelist` no longer seems to be registering on floodgate 2.0 build #14 
Log: https://pastebin.com/wFqYkLRb
Dump: https://dump.geysermc.org/rlFAGwpaXsLeywn2DkD7uwq8QL08bTXt

**Comment by Tim203** [comment]
Shhh, I really didn't invert the check making it only register on platforms that don't support the whitelist command.

**Comment by Tim203** [comment]
Try build 15 :p

**Comment by Konicai** [comment]
The command registers now :)

Also I'm not sure if this is expected currently but there aren't proper messages for when the player is already whitelisted and when the player doesn't exist:

> fwhitelist add Quazar4055
[16:28:26 INFO]: floodgate.command.fwhitelist.player_already_whitelisted
> fwhitelist add 123445678910
[16:29:39 INFO]: floodgate.command.fwhitelist.user_not_found`
