### ISSUE TITLE
Server startup hangs on creation of key.pem on Linux

### ISSUE THREAD

**Issue by Konicai** [GeyserMC/Floodgate#125]
The server says it starts to load floodgate2.0 but then hangs forever. 

Log: https://pastebin.com/kudhAkrh
The server never proceeds past line 16

The `config.yml` is created successfully, however `key.pem` is not. If I create an empty file named `key.pem` floodgate fails to load due to an empty key (instead of just hanging forever). If I copy the server contents to windows `key.pem` is created and everything run as expected. Copying the key to the server install on linux makes linux load normally.

Plugins: 
- Floodgate 2.0 build `#15`
- Geyser (floodgate 2.0 branch) build `#3`

OpenJDK 11.0.9.1 on Debian Buster stable headless. PaperMC-1.16.5-573. I haven't tried a different java version, linux distro, or server jar.

**Comment by Konicai** [comment]
Sorry for all the name changes... had a user in the discord report this also happens on an headless ubuntu server

**Comment by jackson-57** [comment]
Ubuntu is Debian based, so it's possible that it is an issue with Debian specifically

**Comment by Konicai** [comment]
oops I didn't even know that

**Comment by Konicai** [comment]
I did some testing and it seems to hang on this specific line:

https://github.com/GeyserMC/Floodgate/blob/bab001c40fef6de7ab296ed30a876d98b9731624/common/src/main/java/org/geysermc/floodgate/config/loader/ConfigLoader.java#L113

Using Java 1.8 (OpenJDK 64-Bit Server VM 25.275-b01) resulted in the same behaviour

**Comment by Tim203** [comment]
Yeah, that's the part where we generate the key

**Comment by Konicai** [comment]
Yeah I just wasn't initially sure if it was the key or the file that was failing to create 🙂

**Comment by Konicai** [comment]
https://pastebin.com/LG3Rec2g 

It just took 3 hours to boot.... not an April fools joke 🤔

**Comment by Konicai** [comment]
Resolved in build 6 😄
