### ISSUE TITLE
Corrupted skin pixels

### ISSUE THREAD

**Issue by DoctaEnkoda** [GeyserMC/Floodgate#126]
Thank you for the work you have done on skin management! I have just reported a bug that java editions players have noticed.

Like on my screen below, we see a lot of strange particles on this one and it shouldn't exist.

I give you the used versions of Geyser and floodgate as well:

Geyser: 
```bash
18:18:20 INFO]: This server is running Geyser version 1.3.0-SNAPSHOT (git-floodgate-2.0-677a8d6) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.210)
[18:18:20 INFO]: Checking version, please wait...
[18:18:20 INFO]: No updates available.
```
Floodgate 2.0/dev : Build 15

https://media.discordapp.net/attachments/529746155337285642/826845303851450428/unknown.png

**Comment by Konicai** [comment]
Bedrock Edition client bug: https://bugs.mojang.com/browse/MCPE-130275

**Comment by Konicai** [comment]
Reopening as this is still an issue

**Comment by Tim203** [comment]
Are we sure that it isn't related to the Bedrock Edition issue you linked above? That issue is still not resolved

**Comment by Konicai** [comment]
I reopened this because the issue I linked is still unresolved

**Comment by Link0Darck** [comment]
Hello,
I have a problem and I have the last version but I noticed that it is like if the skins to be seen by other people it is necessary that it is the permission like on my laptop my character bedrock has a skin and know a player and my account java does not see the skin of the bedrock unless I give him the permission *

**Comment by Tim203** [comment]
I expect that this has been solved in the latest skin converter version.
Feel free to comment when you feel like this isn't the case.
