### ISSUE TITLE
"Connection Closed" Error Message on Join

### ISSUE THREAD

**Issue by WillyWhitewool** [GeyserMC/Floodgate#128]
Player /(IP):(Port) disconnected (Internal Exception: java.lang.NoSuchMethodError: it.unimi.dsi.fastutil.ints.Int2ObjectMap.computeIfAbsent(ILjava/util/function/IntFunction;)Ljava/lang/Object;) in the chat logs.

For the Console Logs: https://mcpaste.io/89b50d5b75d79aa0

Geyser Dump: https://dump.geysermc.org/o2QEmokQmGXgPNqCTZT725GvMtB3p0t0

Description: Updated to Floodgate 2.0. When joining on Bedrock received error message "Connection Closed." Java players join fine.

**Comment by Camotoy** [comment]
If I had to guess, we need to remove that usage or relocate the Fastutil dependency.

**Comment by WillyWhitewool** [comment]
Where and what is the Fastutil dependency?

**Comment by Camotoy** [comment]
It's something we need to fix.

**Comment by WillyWhitewool** [comment]
Okay, should I try reinstalling Floodgate 2.0 in the meantime? (removing the usage)

**Comment by Konicai** [comment]
You don't need floodgate-api.jar

As Camo said, this is something the devs need to fix

**Comment by WillyWhitewool** [comment]
Tried joining with my Java account on the server. Logs:

04.04 21:30:52 [Server] INFO [Geyser-Spigot] Player connected with username WillyWhitelol
04.04 21:31:00 [Server] INFO [Geyser-Spigot] Attempting to login using floodgate mode... authentication will be encrypted.
04.04 21:31:00 [Server] INFO [Geyser-Spigot] WillyWhitelol (logged in as: WillyWhitelol) has connected to remote java server on address
04.04 21:31:01 [Server] INFO [Geyser-Spigot] WillyWhitelol has disconnected from remote Java server on address because of java.io.IOException: Connection reset by peer
04.04 21:31:01 [Server] WARN java.io.IOException: Connection reset by peer
04.04 21:31:01 [Server] WARN at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
04.04 21:31:01 [Server] WARN at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
04.04 21:31:01 [Server] WARN at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
04.04 21:31:01 [Server] WARN at sun.nio.ch.IOUtil.read(IOUtil.java:192)
04.04 21:31:01 [Server] WARN at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:377)
04.04 21:31:01 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
04.04 21:31:01 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1134)
04.04 21:31:01 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
04.04 21:31:01 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
04.04 21:31:01 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
04.04 21:31:01 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
04.04 21:31:01 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
04.04 21:31:01 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
04.04 21:31:01 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
04.04 21:31:01 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
04.04 21:31:01 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
04.04 21:31:01 [Server] WARN at java.lang.Thread.run(Thread.java:748)
04.04 21:31:01 [Disconnect] User /IP has disconnected, reason: Internal Exception: java.lang.NoSuchMethodError: it.unimi.dsi.fastutil.ints.Int2ObjectMap.computeIfAbsent(ILjava/util/function/IntFunction;)Ljava/lang/Object;
04.04 21:31:01 [Server] INFO [Geyser-Spigot] Bedrock user with ip: /IP has disconnected for reason CLOSED_BY_REMOTE_PEER

**Comment by WillyWhitewool** [comment]
https://mcpaste.io/acbca863fca612e8

Line 450 for logs

**Comment by WillyWhitewool** [comment]
Here's my configs, I don't know if it makes a difference but it's worth looking at.

[geyser config.txt](https://github.com/GeyserMC/Floodgate/files/6258929/geyser.config.txt)
[floodgate config.txt](https://github.com/GeyserMC/Floodgate/files/6258930/floodgate.config.txt)

**Comment by WillyWhitewool** [comment]
Updated Geyser-Spigot to Version 7 of Floodgate 2.0.

New Logs: https://mcpaste.io/3d1946d7cd8aeb3e

Geyser Dump: https://dump.geysermc.org/Iqgccl2AMNZcVFY2575iBHpQpPk7AsUZ

**Comment by Camotoy** [comment]
Can you try updating to the latest Floodgate 2.0 and see if it resolves your issue?

**Comment by WillyWhitewool** [comment]
Just did, still having some problems, although I think my Windows 10 version is on 1.16.210, so I'm gonna try updating it if I can.

**Comment by Camotoy** [comment]
That is currently the latest version as of the time of my comment.

**Comment by WillyWhitewool** [comment]
Still the same problem. I've noticed that joining when my Java account is connected to the server gives me the error message "java.io.IOException: Connection reset by peer," while joining when no one else is on the server gives me the "Connection Closed" error message.

Geyser Dump: https://dump.geysermc.org/YVJSIvB1uzjnRSnLRUnOTiEzbtLyZNan

Logs: https://mcpaste.io/4f5f47ffe365b26e

**Comment by Tim203** [comment]
[Build 22](https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/dev%252F2.0/22/) should fix this issue.
Please comment if it doesn't, because then I'll reopen it.
