### ISSUE TITLE
[Floodgate 2.0] Forwarding on Velocity fails with StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Setadokalo** [GeyserMC/Floodgate#131]
Enabling floodgate data forwarding causes an IndexOutOfBoundsException on the proxy server, immediately disconnecting the bedrock player.
Velocity log: https://mclo.gs/oPA1gj3
Geyser dump: https://dump.geysermc.org/8nYeqKwyaLFmM4bdCa2tMsNy32dAHYDp

**Comment by Tim203** [comment]
Are you trying to use data forwarding type modern?
If you do, that isn't supported yet

**Comment by Setadokalo** [comment]
Modern forwarding is the only one supported by fabric proxy lite, unfortunately...
I thought this issue was fixed, as that's what I thought [this comment](https://github.com/GeyserMC/Floodgate/issues/33#issuecomment-762785923) was referring to. Alas, I guess I'll have to work on a workaround.

**Comment by Tim203** [comment]
Yeah, I thought it was, but it isn't fixed, unfortunately.

**Comment by Konicai** [comment]
I just wanted to note that modern data forwarding should be fine if you have `send-floodgate-data` set to `false`

**Comment by Tim203** [comment]
I'll close this issue in favour of #33
