### ISSUE TITLE
Floodgate 2.0 ProtocolSupport doesn't work

### ISSUE THREAD

**Issue by humematt190** [GeyserMC/Floodgate#132]
I tried installing protocolsupport with geyser and floodgate 2.0 and I tried joining on bedrock edition and it said Read timed out

**Comment by humematt190** [comment]
https://mclo.gs/yAXn7Pl
https://dump.geysermc.org/1vedXK0WPvJPjw9KHMSumqt3gBJxyDne

**Comment by Camotoy** [comment]
Should be resolved.
