### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by masterhacka** [GeyserMC/Floodgate#133]
The server is crashing when joinen and playing with bedrock edition: [https://gist.github.com/masterhacka/7f5f37f9ad09c9b42142a877e5cceaa3](https://gist.github.com/masterhacka/7f5f37f9ad09c9b42142a877e5cceaa3)

Server is running latest paper, geyser and floodgate builds.

**Comment by Camotoy** [comment]
See https://github.com/GeyserMC/Geyser/issues/2129.
