### ISSUE TITLE
Geyser/Floodgates 2.0 connection error

### ISSUE THREAD

**Issue by Hoangviphb999** [GeyserMC/Floodgate#135]
### Describe the bug

When i joining the server, it keep say "Connection Closed" and when i opened my server console, it have is error code bug: https://pastebin.com/iSYeL6Qf
Minecraft Server: Paper 1.8.8 (Using ViaVersion)
Geyser Version: Floodgate 2.0 latest
Floodgate 2.0: latest

### To Reproduce

No

### Expected behaviour

No

### Server Version and Plugins

Geyser-Spigot: Paper 1.8.8

### Geyser Version

Geyser/Floodgates 2.0 latest

### Minecraft: Bedrock Edition Version

1.16.220

**Comment by Hoangviphb999** [comment]
> This happens to me when i turn off `use-global-linking:` . no bedrock players can connect when it is false
In my config, the use-global-linking is true but still can't connected

**Comment by rtm516** [comment]
Can you provide your Floodgate and Geyser config files for when this happens?

**Comment by Hoangviphb999** [comment]
> Can you provide your Floodgate and Geyser config files for when this happens?

Normally, the floodgate 1.0 is public-key.pem right ?

**Comment by Hoangviphb999** [comment]
And my config still in old publickey.pem? Do i need to change into key.pem for Geyser 2.0 ?

**Comment by Konicai** [comment]
You only need to share the config of Geyser and Floodgate. You'll find them in the respective plugin folders of Geyser and Floodgate.

The .pem files are not your config. They are used to encrypt the playerdata. Don't share key.pem. 

config.yml is your config file

more about floodgate2.0: https://github.com/GeyserMC/Floodgate/wiki/Floodgate-2.0

**Comment by Hoangviphb999** [comment]
> You only need to share the config of Geyser and Floodgate. You'll find them in the respective plugin folders of Geyser and Floodgate.
> 
> The .pem files are not your config. They are used to encrypt the playerdata. Don't share key.pem.
> 
> config.yml is your config file
> 
> more about floodgate2.0: https://github.com/GeyserMC/Floodgate/wiki/Floodgate-2.0

Geyser Dump: https://dump.geysermc.org/BkkXv7yTWcT79oEewtproIvToq27iPmY

**Comment by Hoangviphb999** [comment]
Well, the issues was fixed.

**Comment by 7wOv6ySCjo** [comment]
> Well, the issues was fixed.

How? i have the same problem.
