### ISSUE TITLE
Velocity bungeeguard mode support

### ISSUE THREAD

**Issue by Allualbert** [GeyserMC/Floodgate#136]
Velocity bungeeguard mode support for floodgate

**Comment by Hoangviphb999** [comment]
> Velocity bungeeguard mode support for floodgate

There's a flođgates 2.0 for bungeecord in build floodgate build page

**Comment by Allualbert** [comment]
Not what I meant.
In Velocity (the proxy) there are multiple modes. Modern,bungeeguard, and legacy
Floodgate supports legacy but for security reasons, we need it to support bungeeguard mode also!

**Comment by Tim203** [comment]
Floodgate 2.0 should support all 3 forwarding types
