### ISSUE TITLE
Local Account Linking Not Working

### ISSUE THREAD

**Issue by WillyWhitewool** [GeyserMC/Floodgate#137]
Running the command /linkaccount with any input sends this message.
![image](https://user-images.githubusercontent.com/80795900/115462991-4adf2a00-a1f9-11eb-8215-62fef0cf2586.png)

Doing /linkaccount with no input gives this message. 
![image](https://user-images.githubusercontent.com/80795900/115463103-6cd8ac80-a1f9-11eb-94b7-99e6b739cbea.png)

Global linking works just fine, but "normal" account linking cannot be done.

Dump: https://dump.geysermc.org/9bofbXjQkW443tdtMSqwbb4Csn6EDUK8

**Comment by humematt190** [comment]
if you're using floodgate 2.0 i don't think you can use local linking

**Comment by Konicai** [comment]
You don't have local linking enabled in your floodgate config. You'll still be able to use global linking if you enable it.

**Comment by WillyWhitewool** [comment]
Just did that on my own, it fixed the problems. Plot twist: am dumb lol.

Thanks!
