### ISSUE TITLE
Account linking code not working

### ISSUE THREAD

**Issue by MajesticBacon** [GeyserMC/Floodgate#138]
I joined my server on my java and bedrock edition and on my java version I type /linkaccount "Bedrock username" and it tells me to enter /linkaccount "java username" "code" on the bedrock version right? So I go ahead and do that on my bedrock account and it tells me "Usage: /linkaccount <gamertag>" as if I only entered in "/linkaccount"

dump: https://dump.geysermc.org/KpAxuqI63neAqMSt7ZwUv7GFaUxysyIH

**Comment by Camotoy** [comment]
Did you enter in both usernames case-sensitive?

**Comment by MajesticBacon** [comment]
Yes I did

**Comment by MajesticBacon** [comment]
![image](https://user-images.githubusercontent.com/17579969/115469935-bf629a80-a1f2-11eb-86c3-80d2d165bf78.png)

I get this far, but when I type what it says on the bedrock edition on my switch it returns "Usage: /linkaccount gamertag>"

**Comment by MajesticBacon** [comment]
https://github.com/GeyserMC/Floodgate/issues/49

Looking through the closed issues, I found this and we had the same problem. I followed the same steps as him and it worked.
