### ISSUE TITLE
FloodGate 2.0 Not detecting Spigot 1.8.8

### ISSUE THREAD

**Issue by xOnlyFadi** [GeyserMC/Floodgate#139]
Hi FloodGate when I started using floodgate 2.0 on spigot 1.8.8 the server dosen't let me join and I get this error in the console and in minecraft when I join the server, using bungeecord works perfect but spigot 1.8.8 dosen't.
https://pastebin.com/7qkVZ9af
https://cdn.discordapp.com/attachments/613168464634576897/834144703343362078/unknown.png

**[22:27:34] [Server thread/INFO]: [floodgate] Enabling floodgate v2.0-SNAPSHOT
[22:27:34] [Server thread/ERROR]: [floodgate] Plugin floodgate v2.0-SNAPSHOT has failed to register events for class cloud.commandframework.bukkit.CloudBukkitListener because org/bukkit/event/server/TabCompleteEvent does not exist.**

**Comment by Tim203** [comment]
Can you check if the latest build fixed the issue?

**Comment by xOnlyFadi** [comment]
the error disappeared and it's working now thanks

**Comment by xOnlyFadi** [comment]
Hi again the first spigot problem got fixed the second did not get fixed 



https://user-images.githubusercontent.com/63213308/115622107-ad493080-a2b4-11eb-9e1e-8b29f094d117.mp4

![image](https://user-images.githubusercontent.com/63213308/115622348-f4cfbc80-a2b4-11eb-8a28-c353c6161fb3.png)

**Comment by Tim203** [comment]
Upgrading to a newer Spigot version is also a good solution xd

**Comment by xOnlyFadi** [comment]
Im using spigot 1.8.8 because my server is a 1.8 minigames pvp server that's why

**Comment by Tim203** [comment]
Try using the latest build

**Comment by xOnlyFadi** [comment]
it worked now thanks

**Comment by xOnlyFadi** [comment]
it worked now thanks, on java but bedrock i got this problem
![image](https://user-images.githubusercontent.com/63213308/115628933-a2939900-a2be-11eb-960d-9cecf46a4b0e.png)

**Comment by xOnlyFadi** [comment]
the timeout stopped appearing on java but it's still the same 
![image](https://user-images.githubusercontent.com/63213308/115744487-d8cd2900-a34f-11eb-912b-29653d78a225.png)

**Comment by Camotoy** [comment]
Are you using BungeeCord?

**Comment by xOnlyFadi** [comment]
im using waterfall aka bungeecord fork

**Comment by Camotoy** [comment]
Is Floodgate installed on the Spigot server still?

**Comment by xOnlyFadi** [comment]
yes

**Comment by Camotoy** [comment]
Send a complete log file from the Spigot server.

**Comment by xOnlyFadi** [comment]
newest log?

**Comment by xOnlyFadi** [comment]
here https://mclo.gs/B54tb2r
