### ISSUE TITLE
io.netty.handler.timeout.ReadTimeoutExeption

### ISSUE THREAD

**Issue by Cheezelaweeze** [GeyserMC/Floodgate#140]
that spams in console when i put floodgate into my server
only when a sertain player not on bedrock joins it starts i tryed deleting there playerdata.dat file but it still acures i restarted and reinstalled plugin.

paper 1.16.5 no other plugins.
<img width="525" alt="Screen Shot 2021-04-23 at 3 46 43 PM" src="https://user-images.githubusercontent.com/64792971/115928068-27abb900-a44b-11eb-8b2d-23ff055c3340.png">

**Comment by Konicai** [comment]
Are you still having this issue? Can you share your full server logs with https://mclo.gs ?

**Comment by Konicai** [comment]
Closing as there has been no update
