### ISSUE TITLE
Floodgate 2 doesn't work with Bungeecord in Offline mode and must be forced to Online.

### ISSUE THREAD

**Issue by ChaosityYT** [GeyserMC/Floodgate#142]
I am attempting to work with floodgate 2 for geyser but it doesn't want to work in bungeecord offline mode and only online, is there anyway you can add support for bungeecord offline? The problem is, when its in offline mode it decides to generate new UUID's for players which then my players lose their data, previous floodgate worked and floodgate 2 only has this issue. I need this for my authentication system and I have over 7000 people in my current server so renaming UUID's wouldn't be an option. Thank you!

**Comment by Wawwior** [comment]
Don't use Floodgate because the only thing it does is mix java and bedrock verification which is unneccesary when using offline mode where you dont need any verification at all.

**Comment by Tim203** [comment]
> Don't use Floodgate because the only thing it does is mix java and bedrock verification which is unneccesary when using offline mode where you dont need any verification at all.

Even offline servers can benefit from Floodgate. For example servers that want to use the Floodgate API or in general want a separate UUID for Bedrock players.

**Comment by Tim203** [comment]
> I am attempting to work with floodgate 2 for geyser but it doesn't want to work in bungeecord offline mode and only online, is there anyway you can add support for bungeecord offline? The problem is, when its in offline mode it decides to generate new UUID's for players which then my players lose their data, previous floodgate worked and floodgate 2 only has this issue. I need this for my authentication system and I have over 7000 people in my current server so renaming UUID's wouldn't be an option. Thank you!

Maybe this is an issue related to your own auth system, because Floodgate UUIDs haven't changed between v1 and v2

**Comment by Konicai** [comment]
Chaosity, its likely your authentication plugin that is causing issue with Floodgate. Most conflicts between authentication plugins and Floogate 2.0 are recorded in the comments here (nLogin, JPremium, FastLogin are named): https://github.com/GeyserMC/Geyser/issues/2232

Also, Floodgate does have uses for offline mode servers. Geyser currently doesn't replace spaces in usernames with underscores when auth-type is set to Floodgate (have fun dealing with spaces in names).
