### ISSUE TITLE
FG 2.0 - Velocity 1.1.5 Stuck in generating terrain loop

### ISSUE THREAD

**Issue by Parthurax** [GeyserMC/Floodgate#146]
Minecraft 1.16.5

As soon as i join with my bedrock client i get stuck in a "generating terrain" loop.
This starts spamming so fast that the load on Velocity reach over 110% on my r3600x dedicated.
With only one Player logging in.

it happend from on day to another, everything worked fine. i tried Updating to the newest builds Geyser 2.0 and Floodgate 2.0 with the same Issue.
This happens with only geyser and Floodgate installed.

Geyser Dump:
https://dump.geysermc.org/g9LCRmgiS93fiO7DCbzL2kLmUf5bjNG0
Velocity Dump:
https://dump.velocitypowered.com/noyetelaja.json
Error in Velocity:
https://pastebin.com/bLMfSudn

i tested it wihtout floodgate and i came to the login screen without problems, but i wasnt able to login for some reasons.

Have a great day,

**Comment by Parthurax** [comment]
Am i the only one with this issue ? What can i do ? ^^

**Comment by Camotoy** [comment]
Does Java Edition connect fine?

**Comment by Parthurax** [comment]
> Does Java Edition connect fine?

Yes, everything works fine for java.

Here is a log from the server when i connect with bedrock: https://pastebin.com/a3A5KryT
its just a endless loop

**Comment by Konicai** [comment]
Does this still occur with the latest Geyser/Floodgate/Velocity?

**Comment by Tim203** [comment]
Closing this issue because of inactivty
