### ISSUE TITLE
No bedrock skins visible. Only on Proxy

### ISSUE THREAD

**Issue by masterhacka** [GeyserMC/Floodgate#147]
### Describe the bug

I changed to geyser 2.0 on my bungee network. Unfortunately I can't see the bedrock skins on other servers.  Only at the lobby. Hope you can help me

### To Reproduce

Install Bungeecord
Install a Lobby
Install one more server

### Expected behaviour

Bedrock skin should be visible on all servers

### Geyser Version

newest Geyser 2.0

**Comment by masterhacka** [comment]
I am already using newest build:

https://i.imgur.com/3NVwxpE.png
https://i.imgur.com/kn9pRkc.png

**Comment by LegacyGamerHD** [comment]
I also have this some times the skins never load

**Comment by cobrex1** [comment]
Just to confirm that I updated to FG2.0 and Geyser 2.0 and am also having the same issue (Waterfall and Paper). I can see Bedrock skins on the Lobby server and no others. I changed Global Linking: true from false (I am not linking Java and Bedrock accounts), this made no difference. 

I added FG2.0 on all back-end servers with Global Linking as true and this also made no difference.

**Comment by TaminoPalm** [comment]
Same problem

**Comment by hydevdotbiz** [comment]
i have same issue and player java can't see player bedrock skin

**Comment by IsaacTheDev** [comment]
Please fix this issue.

**Comment by Konicai** [comment]
This issue is known and improvements to skin handling between the globalAPI/geyser/floodgate will come in the future. Please don't bump this if you have nothing to provide

**Comment by Chew** [comment]
Floodgate is an open-source project.

**Comment by LegacyGamerHD** [comment]
Found a tempert fix use geyser skin manager

**Comment by Tim203** [comment]
I'm closing this issue in favor of #183 because that issue has more information.
