### ISSUE TITLE
Bedrock player can't connect

### ISSUE THREAD

**Issue by zimzaza4** [GeyserMC/Floodgate#149]
If there is a bedrock player on the server, other bedrock players cannot enter. 

![IMG20210527215051](https://user-images.githubusercontent.com/53421735/119839843-0c930400-bf37-11eb-8fbb-0df1cdc41298.jpg)

![Screenshot_20210526_210048_com mojang minecraftpe](https://user-images.githubusercontent.com/53421735/119839870-10bf2180-bf37-11eb-8498-c4506f9c3ed5.jpg)

Floodgate2.0 #38
Geyser-floodgate2.0 #22

**Comment by zimzaza4** [comment]
> Which platforms are you using? (Bungee,Velocity,Spigot)
> And can you try build 39 of Floodgate 2.0?

I tried build 39. It seems to solve the problem, thank you very much

**Comment by zimzaza4** [comment]
The problem reappeared

**Comment by Tim203** [comment]
Yeah thanks, someone else also reported this and I'll push a fix in a few minutes.

**Comment by Tim203** [comment]
Can you try #40?

**Comment by zimzaza4** [comment]
Seems solved
