### ISSUE TITLE
Geysermc error

### ISSUE THREAD

**Issue by Minionguyjpro** [GeyserMC/Floodgate#151]
Hello. I have an error, how to fix?

**Comment by RednedEpic** [comment]
Please only use this issue tracker for legitimate purposes. If you want help you’re going to need to provide something actually meaningful.

**Comment by Minionguyjpro** [comment]
What you mean?

**Comment by Camotoy** [comment]
Consider joining our Discord if you need help with setting up: https://discord.com/invite/geysermc

**Comment by Minionguyjpro** [comment]
Wait i fixed

**Comment by Minionguyjpro** [comment]
But know have new error:

**Comment by Minionguyjpro** [comment]
If anyone joins it says connection closed by peer.

**Comment by RednedEpic** [comment]
Again, if you’re going to want help please provide meaningful information that allows us to help you out. For issues like this, please use Discord.

**Comment by Minionguyjpro** [comment]
Wait i fixed it fully.
