### ISSUE TITLE
floodgate disabling on server startup (spigot 1.17)

### ISSUE THREAD

**Issue by dromzeh** [GeyserMC/Floodgate#156]
**Describe the bug**
upon starting up my 1.17 spigot server, floodgate disables itself with a fair amount of errors followed: https://mclo.gs/WclT2zy

**To Reproduce**
- setup a spigot 1.17 server
- install geyser & floodgate
- restart the server

**Expected behaviour**
floodgate not disabling on spigot 1.17

**Geyser version**
1.4.0-SNAPSHOT (git-master-cc2d26d) 

**Server Version & Plugins**
CraftBukkit version 3102-Spigot-c9cea60-4d2c780 (MC: 1.17) +  floodgate and geyser

**Comment by JamesHawkinss** [comment]
Can reproduce, Spigot 1.17 Geyser 1.4.0.

**Comment by Jens-Co** [comment]
Floodgate is currently not working on the new 1.17 spigot servers. More info in the announcements channel of Geyser Discord!

**Comment by hjwoods777** [comment]
Can reproduce like above.

**Comment by Camotoy** [comment]
Please do be patient! (Bear in mind I just woke up but) 1.17 has had some major internal changes in regards to Spigot.

**Comment by Camotoy** [comment]
Resolved in 58882e8.

**Comment by hjwoods777** [comment]
You are great, thanks!!!!

**Comment by creepergal** [comment]
this is so confusing pls explain
