### ISSUE TITLE
Player Java Can't See Player Bedrock Skin On Latest Geyser And Floodgate

### ISSUE THREAD

**Issue by hydevdotbiz** [GeyserMC/Floodgate#157]
### Describe the bug
I player Java and i can't see anymore skin player bedrock like before this. After i update floodgate and geyser to master build now i can't see anymore. Now i just see player bedrock just skin alex and steve

### To Reproduce
Install Spigot 1.17
Install Latest Geyser (Master)
Install Floodgate 2.0 (Master)

### Expected behaviour
Player Java can see Player Bedrock Skin like before this.

### Screenshots / Videos
No response

### Server Version and Plugins
Spigot 1.17
Geyser Latest
Floodgate Latest

### Geyser Dump
No response

### Geyser Version
Latest Version

### Minecraft: Bedrock Edition Version
Latest

### Additional Context
No response

**Comment by cobrex1** [comment]
This is the same issue as #147

**Comment by hydevdotbiz** [comment]
> This is the same issue as #147

not sure same or not but this issue with spigot 1.17 and 147 issue with proxy. so not sure. hope dev see this report

**Comment by Tim203** [comment]
It's quite possible that this is because the skin uploader can't upload the skins fast enough, which causes a skin upload queue.
I do think that this is a different issue than #147 because #147 can at least see the skin on one server, and the op doesn't see the skin at all.

**Comment by txtrapline** [comment]
I have this issue as well

**Comment by Tim203** [comment]
I expect #182 and this issue to be the same issue.
I'm closing this issue because #182 has more information.
