### ISSUE TITLE
Feature request: floodgate access for unsigned players

### ISSUE THREAD

**Issue by denisryba** [GeyserMC/Floodgate#16]
Please add possibility to connect to the offline java server which uses floodgate-type geyser for bedrock players who are not signed in their xbox/microsoft accounts.

**Comment by LegacyGamerHD** [comment]
dont crack your bedrock also this should be in geyser rather then floodgate

**Comment by denisryba** [comment]
But this can partially resolve java-bedrock link problem as you will be able to cnahge your nickname you have on your java account.

**Comment by Tim203** [comment]
Like what is said by Legacy; Floodgate can't change that since Floodgate applies the data provided by Geyser and Geyser doesn't allow that
