### ISSUE TITLE
Players can not use the /linkaccount command. Told they do not have permission.

### ISSUE THREAD

**Issue by Andarius68** [GeyserMC/Floodgate#162]
I tried setting floodgate.linkaccount and floodgate.unlinkaccount nodes in their permission settings but to no avail. As an Op I can run the commands just fine but if I deOp myself I, too, receive the message that I do not have permission to use the command.

https://dump.geysermc.org/MZpQ3dRTMvlaEFaz5awFWJcwrzs6uY2v

**Comment by Tim203** [comment]
The new permission names are:
floodgate.command.linkaccount &
floodgate.command.unlinkaccount

**Comment by Andarius68** [comment]
Thank you.
