### ISSUE TITLE
[BUG] Floodgate networking issues

### ISSUE THREAD

**Issue by KolakZ** [GeyserMC/Floodgate#164]
**Bug Description**
After adding Floodgate to my server, mobs suddenly teleport and there are a bunch of block-break delays that have been reported by many players which got fixed when I removed Floodgate.

**Floodgate Verson**
Build #13

**Comment by Camotoy** [comment]
What does CPU and memory look like when this happens?

**Comment by KolakZ** [comment]
I have Floodgate installed on my Waterfall server; 0.05% / 300% cpu and 1.98 / 2GB ram (I am forcing the full heap in startup command using Aikar flags).

**Comment by KolakZ** [comment]
On my backend servers, the ram and cpu seems perfectly normal as well. The only difference is that the ping of every player is unusually high, no issues with the cpu or ram.

**Comment by CoreyShupe** [comment]
@KolakZ can you send us the logs on your proxy? Omitting all the IPs of course, and can you see if you’re receiving out of memory exceptions in your logs?

**Comment by KolakZ** [comment]
https://paste.coaster.host/373808089110193.md

I am not even close to using `1GB` of ram on the proxy.

**Comment by Konicai** [comment]
Can you run `geyser dump` and share the link here? A sparks report as described below would also be useful (with floodgate installed): 
![Uploading AD6EC2EA-2055-4193-A2DB-7C70E2F0510F.jpeg…]()

**Comment by KolakZ** [comment]
https://dump.geysermc.org/d1rMps1CKJKoeUuPppp9hGskrgXXPwoy

**Comment by KolakZ** [comment]
https://spark.lucko.me/5375egImHI

**Comment by Camotoy** [comment]
It could just be me, but that Spark report appears to be blank.

**Comment by KolakZ** [comment]
That's weird, I'll make another one.

**Comment by jackson-57** [comment]
> It could just be me, but that Spark report appears to be blank.

at a glance, it does also seem to be blank for me

**Comment by KolakZ** [comment]
This is probably why: `async-profiler engine is not supported on your system: Operation not permitted`

**Comment by KolakZ** [comment]
Would a timings report be sufficient?

**Comment by KolakZ** [comment]
It shouldn't be an issue with my hardware though. I am using an `AMD Ryzen 9 3950X` with `3` dedicated cores. The bandwidth is really good as well. When using floodgate, everything seems as if ticks are skipping but in `/mspt` and `/tps`, it's really good and none of the ticks are skipping.

**Comment by KolakZ** [comment]
```[02:56:19 INFO]: TPS from last 5s, 1m, 5m, 15m: 20.0, 20.0, 20.0, 20.0
mspt
[02:56:20 INFO]: Server tick times (avg/min/max) from last 5s, 10s, 1m:
[02:56:20 INFO]: ◴ 1.5/1.3/1.8, 1.5/1.3/2.1, 1.5/1.3/2.3```

**Comment by Camotoy** [comment]
Try updating Floodgate and see if by chance it resolves?

**Comment by KolakZ** [comment]
Still had the issues with `Build #15`.

**Comment by KolakZ** [comment]
I tried a little test and just put Floodgate on my backend servers and had no issues. But when I put Floodgate on my Waterfall server, that's when I got a lot of issues.

**Comment by KolakZ** [comment]
If that helps.

**Comment by itsDrav** [comment]
This seems to be the same issue as #154. Similar higher ping as seen in that issue.

**Comment by Tim203** [comment]
Yes, that is most likely the same issue. I'm closing this issue in favour of #154
