### ISSUE TITLE
Bedrock player cannot see their own skin

### ISSUE THREAD

**Issue by Sanluli36li** [GeyserMC/Floodgate#166]
I can’t see my skin when I log in to the game with the bedrock client. I can see other's skin, other people can see my skin
Disable floodgate, everything is normal when using geyser online mode to login

Use Geyser online mode:
![QQ截图20210624033614](https://user-images.githubusercontent.com/5201743/123158982-05f89d80-d49f-11eb-9639-f93972d2a0af.png)

Use Floodgate:
![QQ截图20210624034530](https://user-images.githubusercontent.com/5201743/123159021-1872d700-d49f-11eb-812e-d2c0eb7c393d.png)

Velocity 1.1.5
Geyser version 1.4.0-SNAPSHOT (git-master-ca558fc)
floodgate use build 15
ViaVersion 4.0.0
ViaBackwards 4.0.0

Server is 1.16.5 with Fabric loader 0.11.3
with CarpetMod, Lithium, Phosphor, Servux

**Comment by Konicai** [comment]
Hi, does this still occur with the latest Floodgate build (18)?

**Comment by Sanluli36li** [comment]
Now the skins seen by Bedrock Edition players seem to be set by Bedrock Edition itself instead of the linked java version account.

**Comment by Tim203** [comment]
That bug was fixed 15 days before you posted that comment.
I'm going to assume that you were not using the latest Floodgate version and because of that I'm going to close this issue.
