### ISSUE TITLE
Cant whitelist Bedrock users with Geyser and Floodgate installed on 1.17 spigot

### ISSUE THREAD

**Issue by notgman349yt** [GeyserMC/Floodgate#168]
My Apex hosting server has Geyser and Floodgate installed. and allows bedrock to connect to my Java server
BUT
i cant whitelist
and i cant turn off whitelist bc its a private server
im using the auth: _ for bedrock
and when i did Whitelist add _NotGman349 after connecting for the first time
it said "this player does not exist"

**Comment by Camotoy** [comment]
Use `/fwhitelist` for Floodgate players.

**Comment by notgman349yt** [comment]
> Use `/fwhitelist` for Floodgate players.

ok thanks. lemme see if this works

**Comment by notgman349yt** [comment]
> Use `/fwhitelist` for Floodgate players.

IT WORKS TYSM
