### ISSUE TITLE
floodgate geyser err

### ISSUE THREAD

**Issue by muyunil** [GeyserMC/Floodgate#169]
When using Floodgate, this error occurs very frequently, causing Bedrock Edition players to be unable to join the server. I found this problem in both the paper and the 1.17 version of fabirc.

error：
[21:09:52 INFO]: [floodgate] Enabling floodgate v2.0-SNAPSHOT
[21:09:53 INFO]: Running delayed init tasks
[21:09:53 INFO]: Done (39.279s)! For help, type "help"
[21:09:53 INFO]: Timings Reset
[21:39:25 INFO]: [floodgate] Something isn't right with this data. Try logging in again or contact a server administrator if the issue persists.
[21:39:40 INFO]: [floodgate] Something isn't right with this data. Try logging in again or contact a server administrator if the issue persists.
>

**Comment by SMGoro** [comment]
I have same error to this:


> 18:09:13 [信息] [Geyser-BungeeCord] /192.168.1.103:59938 尝试连接!
> 18:09:14 [信息] [Geyser-BungeeCord] 玩家以 SummerGoro 的用户名建立了连接
> 18:09:18 [信息] [Geyser-BungeeCord] 尝试使用Floodgate模式登录... 身份验证将会被加密。
> 18:09:18 [信息] [Geyser-BungeeCord] SummerGoro (以 SummerGoro 登入) 连接到了远端Java服务器，地址为 169.254.60.106
> 18:09:18 [警告] [Geyser-BungeeCord] We couldn't make sure that your system clock is accurate. This can cause issues with logging in.
> 18:09:18 [信息] [/192.168.1.103:58329] <-> InitialHandler has connected
> 18:09:18 [信息] [Geyser-BungeeCord] SummerGoro 因 Something isn't right with this data. Try logging in again or contact a server administrator if the issue persists. 从远程Java服务器 169.254.60.106 断开
> 18:09:18 [信息] [Geyser-BungeeCord] 基岩版IP为: /192.168.1.103 的玩家因 CLOSED_BY_REMOTE_PEER 断开连接

**Comment by SMGoro** [comment]
> 18:55:42 [信息] [Geyser-BungeeCord] /192.168.1.103:59938 尝试连接!
> 18:55:43 [信息] [Geyser-BungeeCord] 玩家以 SummerGoro 的用户名建立了连接
> 18:55:46 [信息] [Geyser-BungeeCord] 尝试使用Floodgate模式登录... 身份验证将会被加密。
> 18:55:46 [信息] [Geyser-BungeeCord] SummerGoro (以 SummerGoro 登入) 连接到了远端Java服务器，地址为 169.254.60.106
> 18:55:46 [警告] [Geyser-BungeeCord] We couldn't make sure that your system clock is accurate. This can cause issues with logging in.
> 18:55:46 [警告] [floodgate] We couldn't make sure that your system clock is accurate. This can cause issues with logging in.
> 18:55:46 [信息] [/192.168.1.103:58885] <-> InitialHandler has connected
> 18:55:46 [信息] [floodgate] Floodgate player logged in as BE_SummerGoro joined (UUID: 00000000-0000-0000-0009-01fdd1d40d50)
> 18:55:46 [警告] [floodgate] Missing locale file: zh_CN
> 18:55:46 [信息] [Geyser-BungeeCord] 为 BE_SummerGoro (00000000-0000-0000-0009-01fdd1d40d50) 注册基岩版皮肤
> 18:55:46 [信息] [BE_SummerGoro] <-> ServerConnector [lobby] has connected
> 18:55:46 [信息] [BE_SummerGoro] <-> ServerConnector [lobby] has disconnected
> 18:56:16 [警告] [BE_SummerGoro] -> UpstreamBridge - read timed out
> 18:56:16 [信息] [BE_SummerGoro] disconnected with: ReadTimeoutException : null
> 18:56:16 [信息] [floodgate] Floodgate player logged in as BE_SummerGoro disconnected
> 18:56:16 [信息] [Geyser-BungeeCord] SummerGoro 因 ReadTimeoutException : null 从远程Java服务器 169.254.60.106 断开
> 18:56:16 [信息] [Geyser-BungeeCord] 基岩版IP为: /192.168.1.103 的玩家因 CLOSED_BY_REMOTE_PEER 断开连接
> 18:56:17 [警告] Event PlayerDisconnectEvent(player=BE_SummerGoro) took 663ms to process!
> 18:56:17 [信息] [BE_SummerGoro] -> UpstreamBridge has disconnected

**Comment by muyunil** [comment]
geyser dump: 
httpss://dump.geysermc.org/2qk7gq84xCZloPSuDlyZLaRNIpEclTiy

**Comment by SMGoro** [comment]
> geyser dump:
> httpss://dump.geysermc.org/2qk7gq84xCZloPSuDlyZLaRNIpEclTiy

What's this?

**Comment by SMGoro** [comment]
https://dump.geysermc.org/f7y02zjhAgyvJNbqZIkG83Z6kP7MOuA8

**Comment by Tim203** [comment]
> We couldn't make sure that your system clock is accurate. This can cause issues with logging in.

This is the reason why you're having this problem. Floodgate asks a server what time it is, and if it failed to do so issues like that can occur.
If you're using the global api, make sure that the firewall allows outgoing traffic to `api.geysermc.org` (TCP port 443).
And for the time synchronization make sure that `time.cloudflare.com` (UDP port 123) is open.

**Comment by muyunil** [comment]
> > 我们无法确保您的系统时钟准确无误。这可能会导致登录问题。
> 
> 这就是您遇到此问题的原因。Floodgate 会询问服务器现在是什么时间，如果它没有这样做，就会发生类似的问题。
> 如果您使用的是全局 api，请确保防火墙允许传出流量到`api.geysermc.org`（TCP 端口 443）。
> 对于时间同步，请确保`time.cloudflare.com`（UDP 端口 123）已打开。

Hello, because my server is in China, I often can't connect to the time server, so I need some detailed content of this verification process, I will find a solution, such as using a proxy or the like.
