### ISSUE TITLE
Whitelisting bedrock players with spaces does not work

### ISSUE THREAD

**Issue by Kirugaming** [GeyserMC/Floodgate#173]
When trying to whitelist a player with a space in their name it gives me 
Invalid Command Syntax. Correct command syntax is: /fwhitelist add

**Comment by Chew** [comment]
`/fwhitelist add "user name"`

**Comment by Camotoy** [comment]
I tried that. It didn't work. :(

**Comment by Chew** [comment]
WHAT! a bug on our hands :(

**Comment by 9021007** [comment]
This is still an issue
