### ISSUE TITLE
Upload to Spigotmc.org

### ISSUE THREAD

**Issue by Minionguyjpro** [GeyserMC/Floodgate#177]
Upload the plugin to Spigotmc.org, and then set the download link to external jenkins link and it will being automatticaly updated on Spigot

**Comment by MrZomka** [comment]
Why though?

**Comment by lukeeey** [comment]
> Why though?

more publicity, easy access

**Comment by Minionguyjpro** [comment]
> With the Floodgate merge (which means that Floodgate will run inside Geyser) it seems unlikely that this will happen. For most servers you won't need do download Floodgate separately anymore.

Interesting, when will the process for that merge happen?

**Comment by Minionguyjpro** [comment]
> Depends on quite a few things like the available time and the amount of changes we'd want to introduce.
> A 3.0 allows us to break stuff, so if we want to make some big changes it's best to do it then hehe

Aha.
