### ISSUE TITLE
/linkaccount not found

### ISSUE THREAD

**Issue by jack-bailey** [GeyserMC/Floodgate#179]
I'm running the latest version of Geyser + Floodgate on Velocity 3.0.0 with 1.17 PaperMC Servers
The crossplay works but /linkaccount isn't found to be a command on Java or Bedrock.
I've enabled linking in the config.yml but no luck.

**Comment by Konicai** [comment]
Share your floodgate config file

**Comment by jack-bailey** [comment]
Sure: https://hastebin.com/inalejequb.yaml

**Comment by jackson-57** [comment]
I believe you need to uncomment `enable-own-linking`. You can also use Global Linking instead, if you do not want to set up local linking. Setting up local linking requires downloading a database implementation (found on the CI) and putting it in the Floodgate folder.

**Comment by jack-bailey** [comment]
I did so, no luck.
How do I setup global linking? 
I set this up without issues in 1.16.5 with Bungee so I don't know why this isn't going as smoothly

**Comment by rtm516** [comment]
Global and local linking is covered on the wiki page https://github.com/GeyserMC/Floodgate/wiki/Features#what-is-global-linking
