### ISSUE TITLE
Bedrock skins get just applied on some servers

### ISSUE THREAD

**Issue by ofunny** [GeyserMC/Floodgate#183]
I use a setup with a Proxy (Waterfall 1.17.1#448) and multiple backend Minecraft server (Paper, 1.17.1#124).
On the Proxy Geyser and Floodgate have been installed, sending Floodgate data is enabled and on all Minecraft servers Floodgate has been installed as well.

Geyser-BungeeCord: 1.4.1-SNAPSHOT
floodgate: 2.0-SNAPSHOT

The configuration of Floodgate on each backend MC server is identical (I did a file compare to be sure).

**Problem**
I tested the Skin applier/uploader now multiple times and always with the latest build of Geyser/Floodgate. I also know about the queue length problem for uploading.

Anyways: a Skin I tested gets well applied on one of my Minecraft servers, while it will not show up on the rest of my servers behind the proxy. As mentioned above, the Floodgate setup is identically on all servers and Geyser runs on the proxy only.

That being said, I do not believe that this is a queue length problem only – otherwise the skin would not be applied on any server in my network.

If you need additional informations just reply here or ping me on Discord @ofunny

**Comment by Tim203** [comment]
Does this only happen for the first person joining the server or does this always happen?

**Comment by masterhacka** [comment]
> Does this only happen for the first person joining the server or does this always happen?

It does happen always.

**Comment by gam3rboy7** [comment]
I have the same issue but it happens on all of the servers.

**Comment by Tim203** [comment]
A bug that was preventing skins from showing up in a lot of situations (both BungeeCord and Velocity were affected). This has been fixed in 2.2.1 (which can be found in the `development` branch at the time of writing)
