### ISSUE TITLE
fwhitelist doesn't work when the user has a space in their name.

### ISSUE THREAD

**Issue by Greg-J** [GeyserMC/Floodgate#184]
I have a user whose Bedrock username has a space in it. Like `The Guy123`.

The `fwhitelist` command doesn't support this and using quotes doesn't work either.

Is this an oversight, or am I doing something wrong?

**Comment by Camotoy** [comment]
Are you on the latest Floodgate build? This should be fixed.

**Comment by Greg-J** [comment]
> Are you on the latest Floodgate build? This should be fixed if you use double quotes.

The latest version from here: https://ci.opencollab.dev/job/GeyserMC/job/Floodgate-Fabric/job/master/

**Comment by Konicai** [comment]
Tracked here https://github.com/GeyserMC/Floodgate-Fabric/issues/34
