### ISSUE TITLE
Skins cache really weird with SkinRestorer and offlinemode

### ISSUE THREAD

**Issue by cmod31** [GeyserMC/Floodgate#185]
We experimented with that issue on the SkinRestorer Discord with a minecraft test server that i still have btw already (Camotoy,knat ticket-1625856715) but i forgot to make this github issue a couple of times.

Plugins used: floodgate, geyser, authme, fastlogin
(For fastlogin you have to disable skin forwarding in the config but thats their problem so ignore authme and fastlogin)

Basically the Bedrock skin gets not updated with every join as it should. When i change the skin a random skin that i joined the server with gets applied. 
Sometimes you don't get a skin at all or it just shows up client side.

**Comment by Camotoy** [comment]
Instead of being offline mode conflicts, it's probably just #182 doing its manifesting.

**Comment by cmod31** [comment]
Ok but its still this behaviour idk if its the same but if it is you can close it if you want

**Comment by cmod31** [comment]
so i tested it its just with offline mode together with skinrestorer

**Comment by xknat** [comment]
if your using a custom skin like a "[Mohawk hairstyle](https://en.wikipedia.org/wiki/Mohawk_hairstyle)" it will show a black head.
There is a difference between using a skin which could be "viable" for both java and bedrock and skins that are just to "custom" making weird thing happen.

**Comment by Tim203** [comment]
I do convert animated / custom heads iirc, so they shouldn't be black. I however don't translate animated bodies atm, it's on the todo list.
However, like you said, the weirder the shape, the less accurate it'll (likely) be.

**Comment by Tim203** [comment]
I'm closing this because I expect this to be the same issue as #182
