### ISSUE TITLE
Latest Velocity Netty Builds Break Geyser

### ISSUE THREAD

**Issue by BumbleTree** [GeyserMC/Floodgate#186]
### Describe the bug

The latest versions of velocity break geyser. I've pinpointed this to the netty update

### To Reproduce

Use Build GeyserMC/Geyser#50 + of velocity 3.0.1
Restart with geyser.
Get this error
https://pastebin.com/v02k7skg

### Expected behaviour

It to work 

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/77128029/127251516-42e133a4-4536-4012-92ba-f2747884c046.png)

### Server Version and Plugins

1.17.1

### Geyser Dump

https://dump.geysermc.org/biqk2S1ffkGlBoVxAN1DLeGaeVc9tQGV

### Geyser Version

1.4.1-SNAPSHOT (git-inject-de39fd8)

**Comment by Camotoy** [comment]
I'm closing as this is likely a Velocity bug, or at the least the team knows about it and has reverted the problematic commit for the time being: https://github.com/VelocityPowered/Velocity/commit/211da180b376534d109e77ae4c4a1c1b3e4156c2

We will of course be working with them should this be a problem on our end.
