### ISSUE TITLE
Server Lag

### ISSUE THREAD

**Issue by Nevercold** [GeyserMC/Floodgate#187]
Hey,

the bungeecord server hangs every 2 minutes.
According to Spark it is Floodgate (picture attached)

Why does this happen? When the plugin is down, everything runs smoothly.
![image](https://user-images.githubusercontent.com/32977558/127860845-28dda4dc-8136-4703-84f3-f28d288b01a1.png)

**Comment by Camotoy** [comment]
Please provide the direct Spark dump link.

**Comment by LordTheFreak** [comment]
im the owner from that server here is the link: https://spark.lucko.me/CvEamQgFGJ

**Comment by LordTheFreak** [comment]
Please fix this. Thanks.

**Comment by Chew** [comment]
Floodgate is an open-source project.

**Comment by Tim203** [comment]
I expect this to be related to #154. Because of that, I'm closing this issue in favour of #154
