### ISSUE TITLE
Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added

### ISSUE THREAD

**Issue by mibby** [GeyserMC/Floodgate#19]
Java 11.0.7 LTS (AdoptOpenJDK)
Waterfall dev 327 (BungeeCord 1.15.2)
Floodgate development dev 5

```
[18:46:47] [main/WARN] [com.fasterxml.jackson.databind.ext.Java7Support]: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
[18:46:47] [main/INFO]: Loaded plugin floodgate-bungee version 1.0-SNAPSHOT by GeyserMC
```

**Comment by RednedEpic** [comment]
> Java 11.0.7 LTS (AdoptOpenJDK)
> Waterfall dev 327 (BungeeCord 1.15.2)
> Floodgate development dev 5
> 
> ```
> [18:46:47] [main/WARN] [com.fasterxml.jackson.databind.ext.Java7Support]: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
> [18:46:47] [main/INFO]: Loaded plugin floodgate-bungee version 1.0-SNAPSHOT by GeyserMC
> ```

Ignore this error, it’s harmless. In the future, please follow the issue template properly.

**Comment by DoctorMacc** [comment]
Is there any way we can suppress this?

**Comment by mibby** [comment]
There is no issue template... But okay, should at least target JDK8 or 11.

**Comment by DoctorMacc** [comment]
@mibby this is one of our dependencies; it's not directly our fault.

**Comment by mibby** [comment]
Might want to look into replacing it with a modern alternative then if you just use it to grab config variables.

**Comment by RednedEpic** [comment]
> Might want to look into replacing it with a modern alternative then if you just use it to grab config variables.

Jackson is updated and I think this error is just a bug on their end. It works just fine for us and Floodgate/Geyser requires java 8 at the minimum 😄.

**Comment by mibby** [comment]
Perhaps the method was finally deprecated and removed with Java 11.
