### ISSUE TITLE
Cannot whitelist players.

### ISSUE THREAD

**Issue by Ev3Friv** [GeyserMC/Floodgate#190]
I cant whitelist any players to floodgate anymore. I have whitelisted players before and they are still able to join.
When I tried to whitelist a player I got a java null pointer exception. I then updated Geyser and Floodgate to the latest versions.
Now when I try to whitelist a new player it doesn't even print an error log or anything in the chat.

**Comment by Camotoy** [comment]
This is likely due to our API server being down. We'll keep this issue open until the situation is resolved.

**Comment by Ev3Friv** [comment]
Thank you.
