### ISSUE TITLE
Bedrock skins not showing for Java players

### ISSUE THREAD

**Issue by SleepingLaura** [GeyserMC/Floodgate#193]
We've been using Floodgate for a while now, but Bedrock players their skins don't load for Java players.
They don't load at all, even after more than a month, so it probably isn't an issue with the queue either. (They don't load on any of the servers)

**Server versions**
Geyser: 1.4.1-SNAPSHOT (Newest version)
Proxy: Waterfall 1.17 (Running Floodgate 2.0-SNAPSHOT (Newest version))
Hub: Patina 1.16.5
SMP: Patina 1.16.5
SMP 2: Patina 1.17.1
Development server: Patina 1.17.1

Even when we used PaperMC on our hub server it didn't load.

Is there any reason why this happens?

**Comment by Camotoy** [comment]
We have several other issues tracking skins (#157 for example) and we are aware of the issue. For cleanliness of issues, I will close this one on behalf of that. Thank you anyway.
