### ISSUE TITLE
When the proxy server enables the "send-floodgate-data" option, the player joins the server and is kicked out, and the console reports an error.

### ISSUE THREAD

**Issue by DJelly4K** [GeyserMC/Floodgate#195]
**Describe**
When the "send-floodgate-data" option is enabled in the floodgate configuration file of the proxy server *(Velocity 3.0.0)*, the key.pem of the downstream server and the proxy server remains ***the same***. When the player enters the server, he waits in a blank background and then gets kicked. When I was out of the game, the previous kicked out message showed "Time read out". When I tested it again today, the prompt changed to "Disconnect from the server".

**Steps to reproduce**
1. On the proxy server *(Velocity 3.0.0)*, I configured the floodgate configuration file and changed "send-floodgate-data" to true
2. I used the mysql database to connect the proxy server and the downstream server, the communication is normal
3. When I entered the server, I was waiting in the void, and then I was kicked out of the game, prompting: "Time read out" *(before)* or "Disconnect from the server" *(now)* 

**Software & system environment used**
System: Windows Server 2022 Beta Datacenter(Build 20324)

*JVM: *
1. Velocity's (Java16): Zulu OpenJDK16.0.2 (Fully compatible with HotSpot)
2. Downstream servers' (Java11) (Used Viaversion on proxy server): Alibaba Dragonwell OpenJDK11.0.11.7 (Fully compatible with HotSpot)

Proxy server: Velocity 3.0.0 with ***MODERN PROTOCOL***
Downstream server: Airplane 1.16 (Build10)
Geyser: 1.4.1-SNAPSHOT (git-master-a1d167d)
Floodgate: 2.0 (Build22)

**Screenshots**
1. Tips for being kicked out of the game (before)
(Sorry I didn’t have a screenshot, please understand)
2. Tips for being kicked out of the game (now)
![image](https://user-images.githubusercontent.com/68630033/130504075-12e2c685-06df-4f17-879b-0b1c9a3e9dbe.png)
Translate: Disconnet from the server
3. Screenshot of proxy server error
![image](https://user-images.githubusercontent.com/68630033/130504146-cf664898-da25-4930-af6c-a8d5e88db7f8.png)
4. Screenshot of downstream server error
![image](https://user-images.githubusercontent.com/68630033/130504204-38e4198a-cdbc-41ee-aee7-2c01f0756f74.png)
5. Proxy server's floodgate configuration file
![image](https://user-images.githubusercontent.com/68630033/130504288-881c56b6-464b-4ea0-9993-bcab87b19c11.png)
![image](https://user-images.githubusercontent.com/68630033/130504318-560d4f76-d79c-4fde-99cc-bc5a864b2165.png)
6. Downstream server's floodgate configuration file 
![image](https://user-images.githubusercontent.com/68630033/130504384-94d5b184-ba61-4692-bef8-7d9bf5ec3a25.png)
![image](https://user-images.githubusercontent.com/68630033/130504420-6607e3a5-d694-458a-bbfc-8f2f00c47a25.png)

**Remarks**
1. I used machine translation (Google Translate), sorry, please forgive me
2. I also tried the Waterfall proxy server, but the error "Time read out" still appears, and the background error is roughly the same.

**Comment by DJelly4K** [comment]
By the way, I can’t access the Discord server because mobile phone number verification is required, but Chinese mobile phone number verification is not supported

**Comment by Camotoy** [comment]
Our apologies on the Discord requirement - this should hopefully be changed soon. 

How did you copy the key file?

**Comment by DJelly4K** [comment]
> Our apologies on the Discord requirement - this should hopefully be changed soon.
> 
> How did you copy the key file?

I used the mysql database to connect the proxy server and the downstream server, the communication is normal

**Comment by DJelly4K** [comment]
> Our apologies on the Discord requirement - this should hopefully be changed soon.
> 
> How did you copy the key file?

Thank you for your help. I always thought that Mysql database was used to synchronize key.pem. Now I have unified the key.pem of the proxy server and the downstream server and can enter the game normally. Thank you again.
