### ISSUE TITLE
floodgate no longer works on spigot 1.8.8

### ISSUE THREAD

**Issue by Rednd** [GeyserMC/Floodgate#198]
on floodgate build 22 geyser could connect to the server and play, errors would occur but at least players could connect and play. however on floodgate build 23 (i think, i forgot if it happens on this build) and floodgate build 24. geyser players are unable to connect to the server, even if geyser standalone has the same key as floodgate. bedrock players will start connecting and then get displayed the message/error "connection closed" and in the minecraft server console it says "join through official geyser". no errors are displayed in the server console, but this message always appears even if i were to make sure both keys are the same.

**Comment by Rednd** [comment]
i still need help with this

**Comment by Rednd** [comment]
this issue still occurs on floodgate build 25

**Comment by Tim203** [comment]
The 'join through the official Geyser' message happens when the key isn't the same between instances. This has nothing to do with 1.8

**Comment by Camotoy** [comment]
Yeah no this is a 1.8 issue.

**Comment by Tim203** [comment]
Apparently yeah. The fix got merged more than 5 years ago and Minecraft 1.8.8 is over 6 years old. This is the sole reason why the jar file of Floodgate Spigot is much larger than the other platforms, and the jar size will increase again once we fix this :p

**Comment by Camotoy** [comment]
This has been fixed as of the latest Floodgate. Please do note that 1.8.8 is despised by developers not just because it's old but because it's kind of a pain to work with. Our current stance is to support Floodgate on 1.8 as long as we can but this could change at any time.
