### ISSUE TITLE
Feature request: Java/Bedrock account linking

### ISSUE THREAD

**Issue by jackson-57** [GeyserMC/Floodgate#2]
I believe there should be a way to link a player's Java and Bedrock accounts together with Floodgate. This would mean, once linked, the Bedrock account would use the Java account's UUID and username. Some sort of account ownership verification would be required. This feature would allow for a Java player to log off on their computer, and join as the same user on, for example, their phone. While the same thing can be accomplished with online mode, two instances of Geyser would be required, one for the Bedrock only players, and one for the Java/Bedrock players. Not only that, online mode requires the user to log in to their Java account every time, which is inconvenient and (if the Geyser instance is not hosted by the user) insecure. Linking the accounts would skip the Java login process entirely.

**Comment by Heath123** [comment]
We need this

**Comment by CamJW101** [comment]
This would be very beneficial, especially for SMPs and other survival servers.

**Comment by Heath123** [comment]
I’m actually working on this as my first contribution (hopefully)

**Comment by Heath123** [comment]
Adding in #18

**Comment by k-jiang** [comment]
Is it possible to support mixed-mode servers meanwhile?

Networks like us using plugins like [FastLogin](https://www.spigotmc.org/resources/fastlogin.14153/) that allow players join with both online and offline mode. We manage online player's data with online UUID and allow them to change their names. Also offline players can join our network with [AuthMe](https://www.spigotmc.org/resources/authmereloaded.6269/) authentication, no name-change though.

I know it would be better to submit it as an new issue. But this is also deeply related to the linking feature as well. For example, we want:
1. Both online and offline players be able to /linkaccount through BungeeCord commands after correctly authenticated (through official or AuthMe, this is handled by FastLogin installed in BungeeCord).
2. Once they have /linkaccount-ed, online players are linked to their corresponding online-UUIDs and offline players are linked to offline-UUIDs.

We would like to have such a feature as bonus cause we don't have to choose between either side of players. And good jobs to @Heath123 @RednedEpic !

**Comment by rtm516** [comment]
> Is it possible to support mixed-mode servers meanwhile?
> 
> Networks like us using plugins like [FastLogin](https://www.spigotmc.org/resources/fastlogin.14153/) that allow players join with both online and offline mode. We manage online player's data with online UUID and allow them to change their names. Also offline players can join our network with [AuthMe](https://www.spigotmc.org/resources/authmereloaded.6269/) authentication, no name-change though.
> --SNIP--

In the current PR it links the server known UUID to their xuid from MS, so should work with Authentication plugins

**Comment by Tim203** [comment]
What you described should already be possible with the current system, like @rtm516 said.

**Comment by JamesTheAwesomeDude** [comment]
This thread is still very high up on Google Search results

If you have found yourself here accidentally, here is the documentation you're looking for: https://github.com/GeyserMC/Geyser/wiki/Floodgate#account-linking

**Comment by Tim203** [comment]
Thanks, I didn't know that
