### ISSUE TITLE
Latest Floodgate breaks BungeeServerManger plugin

### ISSUE THREAD

**Issue by itsDrav** [GeyserMC/Floodgate#201]
When updating Floodgate to latest, which with testing fixed the ping issues going on with previous versions of the plugin, broke the functionality of BSM. I, in a previous issue found that the ping issues came down to an interaction between floodgate and BSM/AJQueue, so this fix is what I'm assuming broke the plugin. 

BSM allows for hotswapping servers, and not needing to rely on restarting the proxy anytime a server needs to be added to the network. 

To recreate: 
1. Get a bungee network running with 2-3 servers
2. Install BSM (https://www.spigotmc.org/resources/bungeeservermanager-bungeecord-mysql.24837/) 
3.  Add all of the servers you need to BSM
4. Install Latest Floodgate
5. When running /servermanger list , it will show all servers as offline, even though they are online. You can still use /send to get to the servers but other plugins that check if the server is offline before sending you (AJQueue) will not let you join the server. 

Downgrading floodgate to a previous version fixes the issue, as all servers go back to being online on proxy restart. 

** With further testing, this seems to be a problem with any plugin that tries to ping a server for its current status. I have now also seen this happen with AJQueue, as with the latest floodgate I cannot join any servers, as it says the said server is offline.

**Comment by itsDrav** [comment]
With further testing, this issue can be easily replicated with a clean bungee network running latest floodgate, and the free version of AJQueue. Any server you try to join with /queue results in a message saying the server is offline, even though it's not. Floodgate has to be the issue since downgrading to the version my server had before the update fixes the online / offline issue. 

AJQ: https://www.spigotmc.org/resources/ajqueue.78266/

**Comment by Camotoy** [comment]
I wasn't initially able to reproduce your issue, but can you try with the latest Floodgate build?

**Comment by itsDrav** [comment]
I just tested, and it requires send-floodgate-data to be set to true for it to break the other plugins, maybe it has to do something with this?

**Comment by Camotoy** [comment]
Thanks, that did it.
