### ISSUE TITLE
I cant Link Account pls help me

### ISSUE THREAD

**Issue by Prasadnaw** [GeyserMC/Floodgate#205]
![image](https://user-images.githubusercontent.com/79042630/134178013-f8971892-e748-4d78-b4cb-ebfc03311bf2.png)

**Comment by Tim203** [comment]
By default only global linking is enabled. You have to follow a few steps if you want to enable local linking as well.
Related wiki pages:
https://github.com/GeyserMC/Floodgate/wiki/Features#what-is-global-linking
https://github.com/GeyserMC/Floodgate/wiki/Features#local-linking

**Comment by lukeeey** [comment]
it doesn’t look like the message is being translated

**Comment by Tim203** [comment]
I know. I thought that it has been fixed a while back but it doesn't look like it has
