### ISSUE TITLE
Got an error from requesting the xuid of a Bedrock player

### ISSUE THREAD

**Issue by Column01** [GeyserMC/Floodgate#206]
Hey there,
I tried to whitelist my bedrock account for testing my Geyser server and got the following message:
```
2021-09-25 19:04:20 | [ERROR] [floodgate] Got an error from requesting the xuid of a Bedrock player: The Xbox Api isn't setup correctly. Please contact a GeyserMC developer
```
Any idea how I can fix this?

**Comment by Camotoy** [comment]
One workaround is to have the Bedrock player join test.geysermc.org and then try to whitelist. If that does not work, have the player join your server as it is temporarily un-whitelisted, then whitelist them normally like a Java player.

**Comment by JamesTheAwesomeDude** [comment]
@Camotoy Should this issue be re-opened, or at least re-pinned? That **workaround** [is undocumented](https://github.com/GeyserMC/Floodgate/wiki/Features#whitelist-command), and the issue is still present:

```
[18:47:25 INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 started
[18:47:59 ERROR]: [floodgate] Got an error from requesting the xuid of a Bedrock player: Unable to find user in our cache. Please try specifying their Floodgate UUID instead
[18:48:00 INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 shutting down
```

(I was unaware of the `test.geysermc.org` workaround, so I ended up just [looking up the XUIDs](https://www.cxkes.me/xbox/xuid) and formatting them in UUID style manually...)

**Comment by JamesTheAwesomeDude** [comment]
This issue is still present as of the latest build (Jenkins, January 14th).

```
>whitelist list
There are 25 whitelisted players: …
>fwhitelist add squeegily
>whitelist list
There are 26 whitelisted players: …
>fwhitelist add skyridersam
>whitelist list
There are 26 whitelisted players:…
>whitelist add *skyridersam
That player does not exist
>
```
`fwhitelist` only works on players it knows about, and, unlike `whitelist` it **doesn't even display an error** when it fails.

**Comment by Tim203** [comment]
It does return something, but it's probably rcon what's causing this.
You probably also don't get a response if you run `floodgate`. If you don't get a response from that command as well, please open a separate issue saying that commands don't respond when rcon is used.
