### ISSUE TITLE
Xbox API is not setup correctly for whitelist

### ISSUE THREAD

**Issue by ATK422** [GeyserMC/Floodgate#208]
"Got an error from requesting the xuid of a Bedrock player: The Xbox Api isn't setup correctly. Please contact a GeyserMC developer"

I get this message whenever I try to whitelist anyone using /fwhitelist add

**Comment by Camotoy** [comment]
One workaround is to have the Bedrock player join test.geysermc.org and then try to whitelist. If that does not work, have the player join your server as it is temporarily un-whitelisted, then whitelist them normally like a Java player.

Pinning this until this is resolved or we have a workaround.

**Comment by ATK422** [comment]
Got it thanks

**Comment by highamperage** [comment]
I have the same issue. I was able to get around it by adding "." before their gamertag.
Such as _fwhitelist add .XboxGamerName_

**Comment by Tim203** [comment]
Should be fixed now

**Comment by Noobz4Life** [comment]
Issue does not seem to be fixed, attempted on two separate servers and still have get the same Xbox API error message. Running on 1.18 Paper.

**Comment by Dalethium** [comment]
I am currently experiencing this issue on the build published today @Tim203

**Comment by JamesTheAwesomeDude** [comment]
I am also experiencing this on the Jenkins snapshot build from December 23rd.

```
[18:47:25 INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 started
[18:47:59 ERROR]: [floodgate] Got an error from requesting the xuid of a Bedrock player: Unable to find user in our cache. Please try specifying their Floodgate UUID instead
[18:48:00 INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 shutting down
```

Should this issue be re-opened, or at least re-pinned? I was unaware of the `test.geysermc.org` workaround, so I ended up just [looking up the XUIDs](https://www.cxkes.me/xbox/xuid) and beating them into shape manually...
