### ISSUE TITLE
Messages aren't showing correctly

### ISSUE THREAD

**Issue by srnyx** [GeyserMC/Floodgate#210]
**Server version:**
This server is running Purpur version git-Purpur-1394 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: acb8a26 on ver/1.17.1)
You are 8 version(s) behind
Previous version: git-Purpur-1393 (MC: 1.17.1)

**Screenshots:**
![img](https://img.srnyx.xyz/r/kuhnrce2r9a.png)
![img](https://srnyx.is-from.space/r/kuhnroga69a.png)
![img](https://srnyx.likes.cash/r/kuhnuwkfz9a.png)

**Comment by Tim203** [comment]
The issues you provided in your screenshots have either been fixed in master already, or will be fixed in master once `dev/2.1.1` has been released.
Thanks for reporting.
