### ISSUE TITLE
Global linking doesnt work

### ISSUE THREAD

**Issue by Tr1xN** [GeyserMC/Floodgate#216]
When I connect to the server from java and bedrock at the same time, two players appear on the server.
They have same nicknames, bud different UUID and for this reason, different inventory, level, etc

![Screenshot 2021-10-11 141249](https://user-images.githubusercontent.com/87714261/136781756-10e673b5-94ab-445a-ba7e-6c2e1299395e.png)

![Screenshot 2021-10-11 142100](https://user-images.githubusercontent.com/87714261/136781933-8c549eae-d1b9-4563-9b9a-9cde9bb9879b.png)

**Comment by Tim203** [comment]
It looks like your server is in offline mode. Global linking only works in online mode servers.
