### ISSUE TITLE
Floodgate Whitelisting Problem

### ISSUE THREAD

**Issue by FlaredMokoMC** [GeyserMC/Floodgate#218]
I have Minecraft server with my friends and it's whitelisted server but there's a problem on whitelisting players in floodgate. Everytime I do `/fwhitelist add FlaredMoko` it doesn't showing the message "Player whitelisted!" its shows nothing and I tested to join my server but I'm still not whitelisted :/
![Screenshot_2021-10-16-12-55-53-49](https://user-images.githubusercontent.com/76171957/137574297-085d2110-dc4a-4dfe-b021-ca92bbbe441f.jpg) I'm using WiFi and I'm not lagging

Floodgate downloaded
Geyser downloaded

**Comment by Chew** [comment]
Can you send a Geyser dump? `/geyser dump`

**Comment by MrZomka** [comment]
Try doing it in-game, it's probably just a Pterodactyl related bug.

**Comment by Chew** [comment]
Gonna close until we get some more information here, no response when asked for a dump so gonna close this as stale. Feel free to reply if the above doesn't work.
