### ISSUE TITLE
Java Players get hit with "Can't Connect to server" on Server List on Velocity.

### ISSUE THREAD

**Issue by goosBanny** [GeyserMC/Floodgate#224]
Using Velocity 3.0.1 along with the latest version of Floodgate-Velocity, Java users can no longer connect to the server. Removing Floodgate fixes this issue.
The console outputs the following:
`com.velocitypowered.proxy.connection.client.HandshakeSessionHandler$LegacyInboundConnection@59cbdb17 is pinging the server with version Legacy`

**Comment by Tim203** [comment]
Are you sure that you aren't using Velocity's 3.1.0 dev builds?
I think that this is the same issue as #222

**Comment by goosBanny** [comment]
`/velocity version` shows `Velocity 3.0.1`

**Comment by Camotoy** [comment]
Are you sure that you're using the latest Floodgate version? There have been a couple builds where Java connections were definitely borked.

**Comment by goosBanny** [comment]
Yeah, downloaded the latest versions of both Geyser and Floodgate this morning. Didn't work, tried downgrading, still didn't work. It's suddenly working fine now, though. Dunno what fixed it.. :/

**Comment by Camotoy** [comment]
Good to hear! I'll close this then, unless another change in behavior happens.
