### ISSUE TITLE
Index 26 out of bounds for length 5

### ISSUE THREAD

**Issue by Git2Gud** [GeyserMC/Floodgate#225]
Getting this below error when trying to set up floodgate on a server with Geyser installed.
![image](https://user-images.githubusercontent.com/93807611/140821575-98606323-17f3-4010-b349-cff7587b0c83.png)
I've narrowed it down to a floodgate issue - the server ran perfectly just now with just Geyser on it. I went through the config.yml in nano and couldn't find any parameter set to 26. If you know how I could fix this I'd really appreciate it!

**Comment by Camotoy** [comment]
Are you sure you're on the latest Floodgate version?

**Comment by Git2Gud** [comment]
> Are you sure you're on the latest Floodgate version?

@Camotoy 
[This](https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/) is where I downloaded it - it was the only place I could find a download of the spigot jar I was looking for.

**Comment by Camotoy** [comment]
Yes, that link is valid. Please try re-downloading it if you have not recently (I.E. within the last day).

If you still have issues, please supply a Geyser dump.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by Git2Gud** [comment]
You know.... I'm very disappointed in myself that I didn't try that first. I don't know if floodgate's had an update in the past like two days, but that worked and I guess that works! thanks for the help, sorry it was such a simple fix haha

**Comment by Camotoy** [comment]
No worries! It's our fault that we had a temporary bug that affected Java players. Enjoy!
