### ISSUE TITLE
Can not OP bedrock players if  username-prefix is set

### ISSUE THREAD

**Issue by myxxmikeyxx** [GeyserMC/Floodgate#230]
I just wanted to tack this issue. I was not able to op someone form server console when they had an username-prefix set. 
I had to remove the prefix and then OP them and then I could. I tried typing the name with and without the prefix. 
They then had OP
After that I added back the Prefix and it said that they were no longer op.

**Comment by myxxmikeyxx** [comment]
Apparently the player does still have OP because with a plugin I have installed I can see the Admin commands.
But I Still could not op them from console, I can OP them from in the game though.

**Comment by Chew** [comment]
I'm not sure the prefix but are you wrapping it in quotes? Like `/op "*Geyser"`
