### ISSUE TITLE
Wrong error message in fwhitelist command

### ISSUE THREAD

**Issue by Flubberlutsch** [GeyserMC/Floodgate#231]
When using `/fwhitelist add <username>` and a Java player with given username is on the server, Floodgate responds with INVALID_USERNAME ("Username is too short or too long"), which is clearly not the cause of the command abortion. It would probably be better if instead the user was asked to provide the custom prefix along with the username.

https://github.com/GeyserMC/Floodgate/blob/a8829c6d57979a7c66db4b54cecc60cf991293d7/common/src/main/java/org/geysermc/floodgate/command/WhitelistCommand.java#L88

**Comment by Tim203** [comment]
This should be fixed in `dev/2.1.1`
