### ISSUE TITLE
IP forwarding don't work

### ISSUE THREAD

**Issue by LuckCrafter** [GeyserMC/Floodgate#232]
### Describe the bug
Setup a GeyserMC - Bungeecord with two Servers (testing 1.18)
If i try join from the lobby to the main server, i get the error msg

> If you wish to use IP forwarding, please enable it in your BungeeCord config as well!

It work for Java player, only Bedrock player will be "kicked" and stay in the lobby server

### To Reproduce
1. Create a Network with two Servers
2. Create a portal with Advanced-Portals
> /ap create bungee:main name:pmain triggerblock:air

3. Walk trought (On Java it will work, on Bedrock not)

### Expected behaviour
join too the main server like the java player

### Screenshots / Videos
No response

### Server Version and Plugins
Java Version
> openjdk 17.0.1 2021-10-19

**Proxy:** Waterfall-1.18-462
- Geyser-Bungeecord
- floodgate (own-linked is setup with mysql)
- bungee-rcon-1.0.0 [link](https://github.com/orblazer/bungee-rcon)
- LuckPerms-Bungee-5.3.86 (Setup with mysql and invaile)

**Lobby:** paper-1.18-22
- Advanced-Portals-0.5.12-snapshot
- flootdgate-spigot 
- ViaVersion-4.1.0 (I want add older 1.16.5 servers for java players)
- ViaBackwards-4.1.0
- worldedit-bukkit-7.2.3 (not needed)

**main:** paper-1.18-22
- floodgate-spigot 
- LuckPerms-Bukkit-5.3.86

### Geyser Dump
https://dump.geysermc.org/DO8iU3aW9WATmsafL7y7OAJeb3Zbk0zL

### Geyser Version
GeyserMC: Build #941 (Dec 2, 2021, 3:26:45 PM)
Floodgate: Build #53  (Dec 2, 2021, 1:50:04 AM) 

### Additional Context
At first, the server complex run in docker with this container setup:
```
FROM alpine:edge
RUN apk update
RUN for i in 8 11 16 17; do 
    apk add openjdk${i}-jre && ln -s /usr/lib/jvm/java-${i}-openjdk/bin/java /usr/bin/java${i}
done
RUN apk add git make gcc-gdc
RUN git clone https://github.com/Tiiffi/mcrcon.git 
RUN make -C mcrcon
RUN mv mcrcon/mcrcon /usr/bin/ 
RUN rm -rf mcrcon
RUN apk del git make gcc-gdc
WORKDIR /minecraft
```
each server get his own container and are connected with a docker network bridge with custom subnet and static ips.
Only the default and Geyser port a forwarded
> -p 25577:25565 -p 19132:19132/udp

Also is the main restricted set to true in the Bungee Config and the perms add with luckperms on the default group

PS: Yes key.pem are copied to the lobby and main server and send-floodgate-data is set to true on floodgate-bungee config

**Comment by Camotoy** [comment]
Is Floodgate updated on the Spigot server?

**Comment by LuckCrafter** [comment]
Yes, i run floodgate master branch (commit ef04531)
Bedrock Version is v1.18.0
The Command-log isn't also not useful.
Only i know, it doesn't forward my IP
Proxy:
```
[<time> INFO]: [.<player>|/<public ip>:0] <-> ServerConnector [mainAaGeWa] has connected
[<time> INFO]: [.<player>|/<public ip>:0] <-> ServerConnector [mainAaGeWa] has disconnected
[<time> INFO] [Geyser-BungeeCord]: Could not find packet for RequestChunkRadiusPacket
[<time> INFO] [Geyser-BungeeCord]: Could not find packet for RequestChunkRadiusPacket
```

Lobby: `null`

Main:
`[<time> INFO]: /172.24.0.10:39371 lost connection: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!`

**Comment by LuckCrafter** [comment]
Never mind. It looks be that the floodgate-spigot.jar file was broken on the main server.
a redownload fix it.
