### ISSUE TITLE
Create Generic Packet Send

### ISSUE THREAD

**Issue by CoreyShupe** [GeyserMC/Floodgate#233]
This ticket is for creating a generic packet send.

Ideally this would allow users of floodgate to implement any non-implemented packet, since this is an unsafe operation it should be packaged inside of an Unsafe instantiator so the user knows it is unsafe for use.
Along with this to avoid issues with plugins interfering with intended behavior floodgate should log which users are instantiating the unsafe class.
Such a solution could come with an unsafe constructor in the FloodgateApi class where:
```
public Unsafe createUnsafe() {
    logger.warn("Unsafe floodgate api usage detected");
    return new Unsafe();
}
```
With this in mind, Unsafe should be locked down with a package-private protected/private constructor to avoid any outside creation without the logs.

This Unsafe class should be the container for all unsafe methods including the initial use-case listed here.

Ideally the generic packet send would be implemented to where we define the packet ID and the buffer which is being sent to the client and push it through one of the unsafe instance methods.

**Comment by Tim203** [comment]
This feature request has been implemented and should be available in the master branch now.
