### ISSUE TITLE
Support for java things

### ISSUE THREAD

**Issue by TUA0910** [GeyserMC/Floodgate#235]
Can there be a fix for sweeping edge, banners on shields and the luck potion and effect like there is a fix for minecart furnace

**Comment by Camotoy** [comment]
This is the wrong repository - it isn't up to Floodgate to control this.
- Sweeping edge book/enchantment labelling will likely come in the future
- Banners on shields is impossible at this time, at least without limitations
- I'm not sure how easy it is to add functional custom potions.

**Comment by TUA0910** [comment]
> This is the wrong repository - it isn't up to Floodgate to control this.
> 
> * Sweeping edge book/enchantment labelling will likely come in the future
> * Banners on shields is impossible at this time, at least without limitations
> * I'm not sure how easy it is to add functional custom potions.

I moved it to https://github.com/GeyserMC/Geyser/issues/2681
