### ISSUE TITLE
Plugin 'Geyser-Spigot' could not be loaded.

### ISSUE THREAD

**Issue by Murmiks** [GeyserMC/Floodgate#240]
<html>
<body>

Could not load 'plugins/Geyser-Spigot.jar' in folder 'plugins'
--
13 | org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: org/geysermc/geyser/platform/spigot/GeyserSpigotPlugin has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
14 | at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
15 | at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
16 | at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
17 | at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
18 | at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
19 | at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
20 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
21 | Caused by: java.lang.UnsupportedClassVersionError: org/geysermc/geyser/platform/spigot/GeyserSpigotPlugin has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
22 | at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_292]
23 | at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_292]
24 | at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_292]
25 | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:148) ~[minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
26 | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
27 | at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
28 | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
29 | at java.lang.Class.forName0(Native Method) ~[?:1.8.0_292]
30 | at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_292]
31 | at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
32 | at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
33 | ... 6 more

</body>
</html>

**Comment by Jens-Co** [comment]
Geyser only runs on java 16 and up. So please update your java version.

thanks :)
