### ISSUE TITLE
Overflow in packet detected!

### ISSUE THREAD

**Issue by Korgen1** [GeyserMC/Floodgate#242]
I get this when trying to use floodgate with Geyser standalone. 

`InitialHandler - overflow in packet detected! Cannot receive string longer than 255 (got 344 characters)`

**Comment by Tim203** [comment]
If I remember correctly, this was related to using TCPShield in combination with Floodgate.
I'm hereby closing the issue because I referred you to TCPShield support, and I haven't seen you since. So I expect your issue to be solved.
