### ISSUE TITLE
Redstone block states Idea

### ISSUE THREAD

**Issue by Dr01000111** [GeyserMC/Floodgate#244]
I had an Idea for how Redstone block states could be seen on the bedrock client. First bedrock addon support allows for custom blocks so what if on the bedrock client they would see the Redstone dust as a custom block. this custom block could have right-clicked functionality and could have 2 different block states one for cross and one for on. there would be another custom block for on for the cross and dot. this could also be done for Redstone redirecting its self into pistons. This might need a resource pack to work but over all I think this is a clever solution to the problm

**Comment by AnhNguyenlost13** [comment]
Maybe add to the GeyserOptionalPack, also this is the wrong repository to post this in.

**Comment by Dr01000111** [comment]
this won't work with just the geyser optional pack because it adds custom blocks to the bedrock client like an addon not a resource pack

**Comment by Konicai** [comment]
Pretty sure this could just be done with custom model data in GeyserOptionalPack, which is the appropriate place for this, or Geyser.
