### ISSUE TITLE
I can not connect to my Java Server

### ISSUE THREAD

**Issue by loeffelkap** [GeyserMC/Floodgate#252]
Hello, i habe downloaded the plugins Geyser and Floodgate and have set it up appropriately. But this error comes if I join with the Bedrock: "An internal error happened while handling Floodgate data. Try logging in again or connect a server administrator in the issue persist."
What can must I do to join on my Server?

**Comment by Camotoy** [comment]
Please do not open duplicate issues across repositories. Thank you!
