### ISSUE TITLE
Bukkit/Paper download?

### ISSUE THREAD

**Issue by Shadowblitz16** [GeyserMC/Floodgate#256]
your downloads don't list a paper or bukkit version.
![image](https://user-images.githubusercontent.com/2453707/147887277-178963f4-8f3b-41c9-99c7-892580bc1ecb.png)

**Comment by rtm516** [comment]
They are for anything past 1.14.

**Comment by Shadowblitz16** [comment]
@rtm516 I don't understand how exactly do I install this for paper mc for 1.18.1?

**Comment by Shadowblitz16** [comment]
nvm I figured it out.
spigot plugins works on paper

**Comment by Chew** [comment]
We don't support CraftBukkit anymore (no one should) but yes, `Spigot` works fine, if not better, on Paper.
