### ISSUE TITLE
Floodgate encryption fail

### ISSUE THREAD

**Issue by Zynaxwastaken** [GeyserMC/Floodgate#257]
When a bedrock player tries to join my server, they are disconnected with the error message `geyser.auth.floodgate.encryption_fail`. I have uploaded what is shown in the console [here.](https://mclo.gs/gG14Es4) 

Server version: Paper 1.18.1
Geyser build: 997
Floodgate build: 54

**Screenshot**
![image_2022-01-05_165408](https://user-images.githubusercontent.com/67625857/148256920-c57e78fa-2eb2-41e1-90f6-855539628717.png)

**Comment by rtm516** [comment]
I suggest deleting your key and restarting which will cause it to regenerate.

**Comment by Zynaxwastaken** [comment]
Regenerating the key solved the issue, thanks
