### ISSUE TITLE
Using * as player Prefix

### ISSUE THREAD

**Issue by ICodeDumbStuff** [GeyserMC/Floodgate#259]
when using * as player prefix  the minecraft backend servers kick the player with the error: Failed to verify username!

but using anything else like a . works perfectly fine, players prefix needs to be * because tebex only supports *

**Comment by Camotoy** [comment]
We are aware of this issue; for now, you can disable `unsupported-settings.perform-username-validation` in the `paper.yml` config. Floodgate will fix this issue in the future.

**Comment by ICodeDumbStuff** [comment]
doesnt work on 1.17.1 paper server

**Comment by SocMinarch** [comment]
> doesnt work on 1.17.1 paper server

This option was added in 1.17.1 build 407, it won't work on older versions

**Comment by ICodeDumbStuff** [comment]
was it added to all new builds?

**Comment by ICodeDumbStuff** [comment]
not new builds, Was it alled to all versions but ye newest builds
