### ISSUE TITLE
Floodgate Players can't connect over IPv6 behind Bungee Proxy

### ISSUE THREAD

**Issue by bennet0496** [GeyserMC/Floodgate#264]
When a Floodgate Player tries to connect over IPv6 he is immediately kicked with
```
Kicked whilst connecting to server: If you wish to use IP forwarding, please enable it in your BungeeCord config as well! 
```
The Server config is correct and the problem is exclusive to Floodgate (Bedrock) Players over IPv6, it does not happen with IPv4 and not for Java Players with IPv6 or IPv4. I filled this bug previously with Spigot because I tracked the Problem down to the `HOST_PATTERN` in `PacketHandshakingInSetProtocol`. I have a more detailed explanation there in [SPIGOT-6913](https://hub.spigotmc.org/jira/browse/SPIGOT-6913).

But even though the problem technically is the `HOST_PATTERN` it is triggerd by [`/spigot/src/main/java/org/geysermc/floodgate/util/SpigotHandshakeHandler.java`](https://github.com/GeyserMC/Floodgate/blob/763ede8817270fc0ceaad4a3d2b0c7ce3c40b2ed/spigot/src/main/java/org/geysermc/floodgate/util/SpigotHandshakeHandler.java#L60) because the inserted client IP there does not truncate the IPv6 zone identifier, what according to [md_5](https://hub.spigotmc.org/jira/browse/SPIGOT-6913?focusedCommentId=40604&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-40604) Bungee normally explicitly does.

I haven't found where the IP address in `SpigotHandshakeHandler` exactly originates from (a `java.net.InetAddress`?) to maybe read the IP without the identifier in the first place. But because it sounds like Bungee usually specifically handles the identifier, Floodgate should probably too. Even though the Address adheres to RFC addressing specifications, but it seams to violate the Bungee protocol definition.

**Environment**
Spigot/Paper Server with Floodgate behind a Bungee/Waterfall proxy with Geyser and Floodgate.

**Comment by Tim203** [comment]
I don't have IPv6 myself, but the latest Geyser commit GeyserMC/Geyser@5ce2c11 (build 1012) should fix this.
