### ISSUE TITLE
Add ability to handle bedrock packets

### ISSUE THREAD

**Issue by ghost** [GeyserMC/Floodgate#277]
## Add the ability to add an event (or packet) handler to handle packets.
I ran into such a problem that I need to handle a bedrock packet, but I can’t.  For example handle a packet with overloads for commands.

**Comment by Tim203** [comment]
Our goal is to instead of exposing packets directly and we add API for what people need. Please open a feature request for the things you want to instead, and maybe Geyser extensions already have what you need.
