### ISSUE TITLE
help on configuration

### ISSUE THREAD

**Issue by comonier** [GeyserMC/Floodgate#287]
bungeecord + lobby + survival
bung = 1.18.2 = bungeecord.jar
lobby = paper 1.18.2
survival = paper 1.18.2

bungeecord plugins: 
- authme bungeecord
- fastlogin bungeecord
- floodgate bungeecord
- geyser bungeecord
- skinrestorer bungeecord

on lobby i have plugins: [same on survival]
- authme
- fastlogin bukkit
- geyser-spigot
- floodgate-spigot
- protocollib
 - viaversion
 - viabackwards
 - viarewind
 
 bungeecord have option ip-fowarding : true and lobby + survival bungeecord: true
 
 geyser and floodgate configured
 ```java
 bedrock:
  address: 0.0.0.0
  port: 19132
  clone-remote-port: false
  motd1: "motd1"
  motd2: "motd2"
  server-name: "name"
  compression-level: 6
  enable-proxy-protocol: false
remote:
  address: auto
  port: 25565
  auth-type: floodgate
  allow-password-authentication: true
  use-proxy-protocol: false
  forward-hostname: false
floodgate-key-file: key.pem
saved-user-logins:
  - ThisExampleUsernameShouldBeLongEnoughToNeverBeAnXboxUsername
  - ThisOtherExampleUsernameShouldAlsoBeLongEnough
pending-authentication-timeout: 1000
command-suggestions: true
passthrough-motd: false
passthrough-protocol-name: false
passthrough-player-counts: false
legacy-ping-passthrough: false
ping-passthrough-interval: 3
forward-player-ping: false
max-players: 100
debug-mode: false
allow-third-party-capes: true
allow-third-party-ears: false
show-cooldown: title
show-coordinates: true
disable-bedrock-scaffolding: false
always-quick-change-armor: false
emote-offhand-workaround: "disabled"
cache-images: 0
allow-custom-skulls: true
add-non-bedrock-items: true
above-bedrock-nether-building: false
force-resource-packs: true
xbox-achievements-enabled: false
metrics:
  enabled: true
  uuid: hided
scoreboard-packet-threshold: 20
enable-proxy-connections: false
mtu: 1400
use-direct-connection: true
config-version: 4
```
floodgate config
```java

key-file-name: key.pem
username-prefix: "."
replace-spaces: true
disconnect:
  invalid-key: Please connect through the official Geyser
  invalid-arguments-length: Expected {} arguments, got {}. Is Geyser up-to-date?
player-link:
  enabled: true
  require-link: false
  enable-own-linking: false
  allowed: true
  link-code-timeout: 300
  type: sqlite
  enable-global-linking: true
config-version: 2
```
So when i tried to join by mcpe 
![image](https://user-images.githubusercontent.com/19571541/159554607-24098909-e87a-48b8-b604-4b3dbdf7e4f1.png)

on server i get that msg
![image](https://user-images.githubusercontent.com/19571541/159554316-975d9066-de66-4583-962c-c2c4d3cb52fc.png)

any help ?

`ip_forward: true` is already true because i have bung / lobby / survival - so... what can be ?

**Comment by Chew** [comment]
Don't put Geyser on your target servers, it only needs to be on the bungee server. Make sure you're connecting to the bungee Geyser instance. 

Gonna go ahead and close and ask you to move to [Discord](https://discord.gg/geysermc) for further support. Thank you!

**Comment by comonier** [comment]
> Don't put Geyser on your target servers, it only needs to be on the bungee server. Make sure you're connecting to the bungee Geyser instance.
> 
> Gonna go ahead and close and ask you to move to [Discord](https://discord.gg/geysermc) for further support. Thank you!

did it, now its showing a new msg
![image](https://user-images.githubusercontent.com/19571541/159556034-11c01f2e-f5d8-4705-9c6a-d81fdd1dea13.png)

**Comment by comonier** [comment]
solution : copy key from floodgate-bungeecord to floodgate backend folders
gg
close
