### ISSUE TITLE
Missing /fwhitelist command

### ISSUE THREAD

**Issue by QueenAlienor** [GeyserMC/Floodgate#289]
Floodgate appears to be missing the /fwhitelist command.

**Comment by Camotoy** [comment]
The `fwhitelist` command is working correctly for me. Please be more specific - like attach a Geyser dump.
The `fwhitelist` command does not work on proxies, and has to be done on backend servers.

**Comment by QueenAlienor** [comment]
Where would I locate a "Geyser dump".  Please be super specific as I am
fairly new to the back end of minecraft servers.  Basically, assume I know
nothing but am capable of learning about anything.  I tried the command
both on backend servers in game and on console.  Thank you in advance for
your help.  I sincerely appreciate it.

QueenAlienor

**Comment by Jens-Co** [comment]
You will need to run the command geyser dump in console or /geyser dump in-game. This will give you an url that you can give us.

**Comment by QueenAlienor** [comment]
https://dump.geysermc.org/k3T7Tc6TPesLfvoGH4stwN6WU1QQwaUR

**Comment by Tim203** [comment]
Like Camotoy said, the `fwhitelist` command only exists on platforms that have a build-in whitelist (Spigot and Fabric)
