### ISSUE TITLE
player bedrock cannot join

### ISSUE THREAD

**Issue by Xiizu** [GeyserMC/Floodgate#290]
that is the error message
io.netty.channel.unix.Error$NativeIoException: readAddress(..) failed: Connection reset by peer

**Comment by Tim203** [comment]
Please post your whole log instead of such a short snippet.
Most of the time this kind of error isn't caused by Floodgate. Instead, it's caused by a misconfiguration of Geyser.
Please join our discord if you need assistance in setting up Geyser.
