### ISSUE TITLE
Book not showing text

### ISSUE THREAD

**Issue by Dapho999** [GeyserMC/Floodgate#291]
I have this book that players get and for some reason they can't see the 2 first pages and java players can. The last page works fine.
[message.txt](https://github.com/GeyserMC/Floodgate/files/8406068/message.txt)

**Comment by Jens-Co** [comment]
Hi there!

Can you please make a new issue on the Geyser repository since this issue is in the wrong repo?
(https://github.com/GeyserMC/Geyser/issues)

Please follow the issue template and provide us with as much info as you can.

I'll close this issue here 
Thanks!
