### ISSUE TITLE
"Disconnected from Server" disconnect message

### ISSUE THREAD

**Issue by BraveCaperCat** [GeyserMC/Floodgate#293]
When joining a 1.18.2 server with floodgate+geyser installed "Disconnected from Server" message appears on a dirt background like any other bedrock error message, along with a OK button that disconnects you,  i can't see the server log, because it just keeps printing back a error message to do with another plugin,

The only non plugin, would be the server type, which is mohist which ALSO supports forge mods, which i don't have any (YET)

**Comment by Chew** [comment]
Mohist is not supported. Please see https://essentialsx.net/do-not-use-mohist.html.

**Comment by ItzRuler** [comment]
You seriously redirecting people to the EssentialsX website when the entire article is just total garbage?

**Comment by ItzRuler** [comment]
> When joining a 1.18.2 server with floodgate+geyser installed "Disconnected from Server" message appears on a dirt background like any other bedrock error message, along with a OK button that disconnects you, i can't see the server log, because it just keeps printing back a error message to do with another plugin,
> 
> The only non plugin, would be the server type, which is mohist which ALSO supports forge mods, which i don't have any (YET)

Did you add the geyser plugin?

**Comment by ItzRuler** [comment]
> > When joining a 1.18.2 server with floodgate+geyser installed "Disconnected from Server" message appears on a dirt background like any other bedrock error message, along with a OK button that disconnects you, i can't see the server log, because it just keeps printing back a error message to do with another plugin,
> > The only non plugin, would be the server type, which is mohist which ALSO supports forge mods, which i don't have any (YET)
> 
> Did you add the geyser plugin?

Floodgate is just bonus authentication to be bundled with geysermc.

**Comment by BraveCaperCat** [comment]
@Chew IS NO LONGER ALLOWED TO POST HERE

**Comment by Camotoy** [comment]
Chew is a member of our triage team.

Regardless, Mohist's website states for 1.18.2: 
`Important: Mohist 1.18.2 is still experimental and the plugin compatibility is very close to 0%. If you plan to use it for production, please wait for it to be stable.`
Likely meaning this error has to wait for Mohist to resolve.

**Comment by BraveCaperCat** [comment]
> Chew is a member of our triage team.
> 
> Regardless, Mohist's website states for 1.18.2: `Important: Mohist 1.18.2 is still experimental and the plugin compatibility is very close to 0%. If you plan to use it for production, please wait for it to be stable.` Likely meaning this error has to wait for Mohist to resolve.

and anyway, i think it might of been that i needed java 18 becuase of wait, where is that issue again, maybe it was on the main geyser project?

**Comment by BraveCaperCat** [comment]
> Chew is a member of our triage team.
> 
> Regardless, Mohist's website states for 1.18.2: `Important: Mohist 1.18.2 is still experimental and the plugin compatibility is very close to 0%. If you plan to use it for production, please wait for it to be stable.` Likely meaning this error has to wait for Mohist to resolve.



> ah, it's: [GeyserMC/Geyser#2956](https://github.com/GeyserMC/Geyser/issues/2956)

well, it's with a just plugin server, so maybe both.
