### ISSUE TITLE
Mod support

### ISSUE THREAD

**Issue by BraveCaperCat** [GeyserMC/Floodgate#294]
Would you be able to support mods, if the server has mods?

Basically, would i be able to access mods with a bedrock client? or would you have to add support for that? or is that even possible?

**Comment by Camotoy** [comment]
Geyser emulates a vanilla Java Edition game client. If the mods installed on the server allow a full vanilla client to connect, then a Geyser player can. (Conversely, if a player must install mods, a Geyser player can not join.)

**Comment by BraveCaperCat** [comment]
> Geyser emulates a vanilla Java Edition game client. If the mods installed on the server allow a full vanilla client to connect, then a Geyser player can. (Conversely, if a player must install mods, a Geyser player can not join.)
it was supposed to be a question, not a feature request.
