### ISSUE TITLE
Converted skin uses incorrect skin model

### ISSUE THREAD

**Issue by mooziii** [GeyserMC/Floodgate#297]
### Describe the bug

When a bedrock player has a slim skin, it will be shown as a classic skin for java players.

### To Reproduce

1. Put a slim skin on the bedrock account
2. Join a java server
3. The bedrock player will have a classic skin for all java players.

### Expected behaviour

The player skin model should be slim for all players.

### on bedrock:
![bedrock image](https://i.imgur.com/MXtcA2L.png)

### on java:
![java image 1](https://i.imgur.com/IRu7ZZO.png)
![java image 2](https://i.imgur.com/CyAGlzI.png)

### Geyser Dump

https://dump.geysermc.org/FVKs1rF6E1qTixYc4jlGFEJRH0aFyMuK

### Geyser Version

2.0.2-SNAPSHOT (git-master-fb26e26)

### Minecraft: Bedrock Edition Version

1.18.12

### Additional Context

Im using floodgate.

**Comment by Tim203** [comment]
I pushed a change to the skin converter yesterday.
Could you try joining again with that skin and see if the same skin still produces this issue?

**Comment by mooziii** [comment]
newest build from jenkis
![image](https://user-images.githubusercontent.com/63669478/167287621-fb9f2e66-6027-4ad5-baed-1b76146ceec9.png)

**Comment by Tim203** [comment]
In that case could you join `test.geysermc.org:19100` with your Bedrock account? This allows me to see why your skin is being converted like that.

**Comment by mooziii** [comment]
![image](https://user-images.githubusercontent.com/63669478/167288308-deab3c9a-f4c9-44e6-a6a9-9747118f8ce8.png)

**Comment by Tim203** [comment]
Ah oops. I'll let you know when that has been fixed.

**Comment by Tim203** [comment]
You should be able to connect now.

**Comment by mooziii** [comment]
yes 
![image](https://user-images.githubusercontent.com/63669478/167291473-de0b4831-84cd-4368-90ce-beb676bcb4b9.png)

**Comment by Tim203** [comment]
I took a look at it today, and the converter says that it's an Alex skin.
Because of that I'm closing this issue, as it should be fixed.
