### ISSUE TITLE
Issues connecting to server with Floodgate installed on Switch

### ISSUE THREAD

**Issue by sherbFTFY** [GeyserMC/Floodgate#305]
Howdy,

I have been connecting to a private hosted java server just fine, using the public GeyserMC DNS spoof. The server jas GeyserMC and Floodgate installed, however I have been using my Microsoft (migrated Mojang) account to login and connect every time; I have been trying to reconfigure the server to connect without the need for this, but I keep getting the "You need a Java Edition account to play on this server."

The server is set to offline mode (no account verification) and every possible Floodgate option is enabled in Geyser's config.yml file.

The server itself is port forwarded via TCP, however I am not forwarding UDP due to my own limitations on my home network. Plus dat stuff complicated, screw off microsoft lol

Any tips?

**Comment by Camotoy** [comment]
Make sure you're getting a log in your server when you try to connect. Also, make sure you're connecting to the server as a Bedrock server, and not a Java one through GeyserConnect. For further help, please use our Discord. Thanks!
