### ISSUE TITLE
Floodgate Crash 100% CPU

### ISSUE THREAD

**Issue by Abeoji** [GeyserMC/Floodgate#306]
I am opening this ticket today, in regards to an issue I have been having via proxy after x amount of uptime the proxy would go to 100% CPU usage. Essentially dropping everyone's connection and when players would try to rejoin they would be greeted with " You are already connected to this server message" I am providing a spark sample of when the occurrence happened.

Spark :
https://spark.lucko.me/H9ytMn79FA

`floodgate (26957.52ms)
Netty Worker IO Thread (x32)100.00%
org.geysermc.floodgate.inject.bungee.BungeeInjector$BungeeProxyToServerInjectInitializer.write()93.30%
org.geysermc.floodgate.inject.bungee.BungeeInjector.injectClient()93.30%
org.geysermc.floodgate.inject.CommonPlatformInjector.addInjectedClient()93.30%
java.util.HashSet.add()93.30%
java.util.HashMap.put()93.30%
java.util.HashMap.putVal()93.30%
java.util.HashMap$TreeNode.putTreeVal()93.30%
java.util.HashMap$TreeNode.balanceInsertion()33.45%
/usr/lib/jvm/java-17-openjdk-amd64/lib/server/libjvm.so (native)0.00%
/usr/lib/jvm/java-17-openjdk-amd64/lib/server/libjvm.so (native)0.00%
/usr/lib/jvm/java-17-openjdk-amd64/lib/server/libjvm.so (native)0.00%
libc-2.31.so.syscall()0.00%`

**Comment by Camotoy** [comment]
We have reports of this issue. We don't think it's on our end; we think it's another plugin causing the issue. Please provide a Geyser dump:
Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by Abeoji** [comment]
> 

https://dump.geysermc.org/mrPygmeXoxZodkzcE8S5ey3wGFn2cobo

**Comment by Camotoy** [comment]
If you're able to try with no other plugins then do that - or else it's some sort of config issue.

**Comment by Abeoji** [comment]
Issue resolved. Caused by external factors :D thank you

**Comment by Camotoy** [comment]
What was the issue?

**Comment by Camotoy** [comment]
Which one?
