### ISSUE TITLE
Not able to connect on Java with Lunarclient

### ISSUE THREAD

**Issue by SudoPigeon223** [GeyserMC/Floodgate#311]
I'm using both latest versions of Geyser spigot and Floodgate but I get immediately disconnected with the message "Invalid Payload REGISTER!" when connecting with Lunarclient. I can connect perfectly fine on vanilla or bedrock so I'm not sure what would be causing the issue because it worked fine prior to 1.19. I'm also using Spigot but I was using Paper before 1.19. And I also wanted to point out that I'm using Aternos as my hosting provider.  Here is my dump: https://dump.geysermc.org/6Ama0OBIqkVwkZ5YyTvXltImo9bwWIvp

**Comment by Camotoy** [comment]
This doesn't sound like an us issue, so I'm closing. If the issue removes itself while removing Geyser and Floodgate, let us know.

**Comment by SudoPigeon223** [comment]
I first brought up the issue in the support channel of the discord server and Kastle told me to create an issue here. I played around with it and it works fine without Geyser or with just Geyser and no Floodgate. I think that Floodgate is the issue especially because it worked fine with Floodgate on 1.18.2. I could definitely be wrong so I guess I'll see if anyone else has this issue. Thanks for the response.

**Comment by SudoPigeon223** [comment]
After checking with the Lunarclient community it seems that it is their issue. Thanks again for your help.
