### ISSUE TITLE
Empty username-prefix broken in config upgrade

### ISSUE THREAD

**Issue by krusic22** [GeyserMC/Floodgate#314]
Upgrading to the latest version of Floodgate, with an empty username prefix, the "" is removed and Floodgate fails to load.
The problem is resolved by manually inserting "" back.
Old configuration line:
`username-prefix: ""`
Following the upgrade:
`username-prefix: `

This results in the following error in the console:
![image](https://user-images.githubusercontent.com/8352435/172892941-22b818a3-c147-4264-8374-fbe4fff4bc39.png)

Dump: https://dump.geysermc.org/F81uwrglmwVOgyHUIIWjJwaXOd9xAgJP

**Comment by Tim203** [comment]
This issue also happens with the `-` prefix, as that is seen as a sequence

**Comment by Tim203** [comment]
This issue has been fixed in the latest build (67) for configs that haven't been updated to config version 3 yet.
Thanks for reporting this.
