### ISSUE TITLE
Villager interact BUG?

### ISSUE THREAD

**Issue by BufalinoSD** [GeyserMC/Floodgate#316]
Describe the bug
Users trying to trade with the librarian villagers do not open the GUI and their inventory is bugged.

To Reproduce
Try swapping with a bookseller

Expected behaviour
fix this bug

Screenshots / Videos
https://youtu.be/tf9GwMOtMLI
https://youtu.be/HPn3AWEh64I 
![image](https://user-images.githubusercontent.com/88399754/173194364-00d6337e-87aa-4fff-b97f-ddab2dc7c58a.png)

**Comment by BufalinoSD** [comment]
I just checked with older versions and everything works fine.

**Comment by BufalinoSD** [comment]
![image](https://user-images.githubusercontent.com/88399754/173194151-70493d2e-4e7f-4d83-a042-ca0995162e00.png)
NEW LINK: https://youtu.be/tf9GwMOtMLI

**Comment by Camotoy** [comment]
It sounds like this is the same issue as https://github.com/GeyserMC/Geyser/issues/3046. I'm closing this issue since it involves Geyser code and not Floodgate code. Thanks!
