### ISSUE TITLE
Bedrock just unable to join the World

### ISSUE THREAD

**Issue by dercreeperlive** [GeyserMC/Floodgate#324]
I found a bug, that if a Bedrock Player tries to connect to a server running the latest version of geyser, it will not be able to join the world. I tried setting up geyser in diffrent ports and ips and it didn´t work. Before the update, geyser worked just fine. I also reinstalled it a few times.

Please Fix it, I want to play with all my other friends.

**Comment by ImDaBigBoss** [comment]
Can you send the error that you're getting?

**Comment by Chew** [comment]
Please see this lovely guide: https://geysermc.wiki/geyser/fixing-unable-to-connect-to-world/

If you continue to have issues, please let us know on [Discord](https://discord.gg/geysermc) and we'll be happy to help.

Regardless, this is a Geyser issue, and not a Floodgate one.
