### ISSUE TITLE
Bedrock Skins on Java sometimes not appearing

### ISSUE THREAD

**Issue by Roctivels** [GeyserMC/Floodgate#325]
When I play on Java with a Friend who has Bedrock and we play through Floodgate, sometimes his Skin is not visible (keep in mind it's not a traditional skin it's made with the built in skinmaker from bedrock)

**Comment by BobtheBob123456** [comment]
Hi,
I don't know if this is still an issue, but I know a client called Bedrockskinutility that helps Java players see bedrock player skins, capes, etc.

https://github.com/Camotoy/BedrockSkinUtility

If you want to use this however you will need to download this plugin:
https://www.spigotmc.org/resources/geyserskinmanager.88607/

**Comment by Tim203** [comment]
Duplicate of #182 and #183
