### ISSUE TITLE
public-key.pem not generating

### ISSUE THREAD

**Issue by Stoicalboar7852** [GeyserMC/Floodgate#328]
Hi, i am trying to make my java SMP Crossplayable, because some of my friends dont have java, but in the floodgate plugin folder that is generated, the public-key.pem file is not generated.
![image](https://user-images.githubusercontent.com/108503162/176811670-64fced3b-89da-4643-b255-39e77f3c9483.png)
 is it in another folder, or do i not need it? By the way, i am trying to run spigot 1.19 with this

**Comment by Stoicalboar7852** [comment]
i am running windows 11 btw

**Comment by Jens-Co** [comment]
Hello there, 

You are probably watching the an old guide the setup Geyser/Floodgate. 

Public-key was renamed to key.pem which you have, so everything should be fine!

If you are having issues please check our wiki since that guide is the most recent https://wiki.geysermc.org 

thanks

**Comment by Camotoy** [comment]
Additionally you don't need to copy the key anymore if you're just using a Spigot server.

**Comment by Stoicalboar7852** [comment]
ok, i will try joining on bedrock without public-key.pem

**Comment by Stoicalboar7852** [comment]
i Can join on my Java account (in java edition), but windows edition says this:
![image](https://user-images.githubusercontent.com/108503162/176812660-c2133384-eefe-458a-829d-f02b605f50ae.png)

**Comment by Jens-Co** [comment]
https://wiki.geysermc.org/geyser/fixing-unable-to-connect-to-world/#windows-10

You are probably having a loopback restriction on windows10. For further assistance please join us on discord! 
https://discord.geysermc.org/
