### ISSUE TITLE
Would you like to migrate plugin release methods to Github?

### ISSUE THREAD

**Issue by dairin007** [GeyserMC/Floodgate#331]
Currently, built artifacts are placed on [Here](https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master). I understand that Github is used for code and issue management. 
However, Github has an excellent way of providing artifacts such as Github Release, and my understanding is that I can build with Jenkins and deploy to Github Release.
Other plugins also provide Github Release, which can be used to automate server management in a unified manner.

If I'm missing the point of this discussion, please feel free to let me know.

**Comment by Konicai** [comment]
It's possible, but setting up new build scripts that match our current Jenkins ones is a fair amount of effort that could be used on Geyser/Floodgate itself.

Also, a lot people depend on the current links to work. You can fetch the last successful build from a Jenkins job to automate management.

**Comment by Chew** [comment]
GitHub releases isn't ideal for every build. Even EssentialsX uses Jenkins for dev builds and only releases stable ones to GitHub. Plus, we don't need permanent jars that GitHub releases provide, and it's far easier to automate downloads as Konicai said, it's nearly impossible to grab latest release JARs though GitHub. Just seems more of a hassle unfortunately.

**Comment by Camotoy** [comment]
Yeah, I don't think this is a route we'll be taking. But if you wanted to automate downloading the latest Floodgate version then https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/lastSuccessfulBuild/artifact/spigot/build/libs/floodgate-spigot.jar should always point to that.

Thanks anyway.
