### ISSUE TITLE
[Development branch] Plugin error on load

### ISSUE THREAD

**Issue by Aurelien30000** [GeyserMC/Floodgate#332]
On Velocity, using GeyserMC combined with floodgate on ``dev`` branch _(https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/development/7/)_, plugin fails to load and throws this error: 

https://paste.domicraft.fr/sizujezigu.sql

_I'm aware of this being on an unstable branch, but I guess this is not expected :D_

Thanks!

**Comment by Konicai** [comment]
FYI, as of right now, there isn't any point in using the development branch

**Comment by Kas-tle** [comment]
My bad. I asked them to open this in support not realizing they were on the dev branch.

**Comment by Tim203** [comment]
This should be fixed in the latest version
