### ISSUE TITLE
Warning "[11:58:48 WARN]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [11:58:48 WARN]: The backend channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)" on Velocity

### ISSUE THREAD

**Issue by Garfieldwxg55** [GeyserMC/Floodgate#335]
Hi, I'm configuring a new Velocity server, and I noticed that whenever I start the server with Floodgate installed, I get this error:

[11:58:48 WARN]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:58:48 WARN]: The backend channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

I'm bit sure what's causing this, but I heard I could post the issue here.
Thanks for reading :)

**Comment by Camotoy** [comment]
This is safe to ignore; it is a deliberate warning that Floodgate is hooking into the network processes of Velocity.

**Comment by pauljsymonds** [comment]
> This is safe to ignore; it is a deliberate warning that Floodgate is hooking into the network processes of Velocity.

Why not replace the warning message with 'Floodgate is hooking into the network processes of Velocity.'?

**Comment by Camotoy** [comment]
The warning message is created by Velocity, so it has to print regardless. We can print a log nearby saying it's a warning that's supposed to happen but that's about it.
