### ISSUE TITLE
isFloodgatePlayer() returns false with BE players uuids

### ISSUE THREAD

**Issue by Filocava99** [GeyserMC/Floodgate#336]
Hi. I was creating an exemption for BE players in my anticheat but apparently any call to `FloodgateAPI.getInstance().isFloodgatePlayer()` always returns `false` with BE users uuids.
The floodgate version is `v2.2.0-SNAPSHOT (b70-6e2c19f)` and the geysermc version is `v2.0.4-SNAPSHOT` running on Spigot `1.19-R0.1-SNAPSHOT`.

I tried as a workaround to filter the list of floodgate users to find a match based on their username (I thought that maybe the java uuid was different from the BE one):
```
AtomicBoolean isFloodgatePlayer = new AtomicBoolean(false);
FloodgateApi.getInstance().getPlayers().stream().filter(player -> player.getJavaUsername().equals(event.getPlayer().getName())).findFirst().ifPresent(player -> {
    isFloodgatePlayer.set(true);
});
this.instance.getLogger().info("Is floodgate player:" + isFloodgatePlayer.get());
if(isFloodgatePlayer.get()){
    return;
}
```
But still didn't work.
At this point I am no longer sure if it's a bug in my code or in the floodgate API.
[Here's the startup log in case you need it](https://www.dropbox.com/s/3k2pkcqie9ec0s6/latest.log.txt?dl=0)

PS. Since I don't have BE account I wasn't able to test it myself, I am just reporting what the users of my plugin are experiencing on their servers.

**Comment by BobtheBob123456** [comment]
Can someone please respond to this?

**Comment by Konicai** [comment]
Can you publish your branch with WIP Floodgate support?

**Comment by BobtheBob123456** [comment]
What is that?

**Comment by Konicai** [comment]
You were calling `isPluginEnabled("floodgate")` during your `onEnable` before Floodgate was enabled. Although you had floodgate as  `softdepend`, you have `load: STARTUP`, which overrides the load order of `softdepend`s and `depend`s.

It doesn't look like your plugin needs to be loaded on startup, so I would remove that, or move your check for floodgate presence to a later time.

**Comment by Konicai** [comment]
Contact me on Geyser's Discord please

**Comment by Filocava99** [comment]
Oks I will
