### ISSUE TITLE
Horse issues

### ISSUE THREAD

**Issue by Ibotmealot** [GeyserMC/Floodgate#337]
> A player on my server seems to be unable to eat golden carrots near horses, unless they turn pvp on. They're playing on bedrock (with Nintendo switch), however, floodgate is installed on the server. T
> 
> https://youtu.be/HCcJqhSpXwQ and https://youtu.be/d-fMoVcVKzI

Was told to report this to y'all instead: https://github.com/YouHaveTrouble/PreventStabby/issues/11

**Comment by Camotoy** [comment]
Can you please open an issue on the Geyser repository? Thanks!

**Comment by Ibotmealot** [comment]
> Can you please open an issue on the Geyser repository? Thanks!

Saw that you replied to the other issue, would you still like me to go ahead and make an issue on that repo?

**Comment by Camotoy** [comment]
Yes.
