### ISSUE TITLE
using color codes in the username prefix breaks most Strings containing the username

### ISSUE THREAD

**Issue by Mari023** [GeyserMC/Floodgate#34]
**Describe the bug**
When using color codes in the username, the text following the username is still colored 
you can't use the name in a command (eg /msg §eMari_023) since minecraft java edition doesn't allow you to type the character '§' 

**To Reproduce**
1. in the floodgate config.yml, set username-prefix to something like "§e"
2. let a bedrock Player join
3. see that their name is colored (in the case of §e, yellow)

**Expected behavior**
the text after the username not to be colored

**Screenshots / Videos**
![colorprefix0](https://user-images.githubusercontent.com/38946771/82151309-424cd980-985b-11ea-8db0-91746934d16c.jpg)
![colorprefix1](https://user-images.githubusercontent.com/38946771/82151310-42e57000-985b-11ea-9a5f-025ba7264378.jpg)
![colorprefix2](https://user-images.githubusercontent.com/38946771/82151311-437e0680-985b-11ea-980d-97c43edb05d3.jpg)
![colorprefix3](https://user-images.githubusercontent.com/38946771/82151312-437e0680-985b-11ea-8130-001637951041.jpg)
![colorprefix4](https://user-images.githubusercontent.com/38946771/82151313-437e0680-985b-11ea-885d-53e32cf7ec31.jpg)
![colorprefix5](https://user-images.githubusercontent.com/38946771/82151314-44169d00-985b-11ea-8a22-f55e7d991640.jpg)

**Server Version**
Waterfall-Bootstrap:1.15-SNAPSHOT:e0795ab:341
git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)  and git-Spigot-2040c4c-1872231 (MC: 1.15.2)

**Floodgate and Geyser Version**
Floodgate pr #30
Geyser 1.0-SNAPSHOT (git-master-43ee7d6)

Minecraft: Bedrock Edition Version
v1.14.60
 
**Alternatives?**
a) don't use color codes in username prefix
b) allow for a suffix as well

**Additional Context**
this also happens if a offline mode java user with color codes in their name joins the server

**Comment by Tim203** [comment]
Like you said, you use the color a color code as prefix. Just don't use it x)

**Comment by rtm516** [comment]
It could be stripped from the xbox username tho to prevent this issue

**Comment by Tim203** [comment]
> in the floodgate config.yml, set username-prefix to something like "§e"
