### ISSUE TITLE
Injection Error on Plugin Initialisation

### ISSUE THREAD

**Issue by dparkinson101** [GeyserMC/Floodgate#342]
Velocity#167 (latest as of this ticket) on the development branch seems to make Floodgate crash on startup.
Both Geyser and Floodgate are on the latest versions.

See attached log: https://mclo.gs/wjiUqKt

**Comment by Konicai** [comment]
You're using this development branch of Floodgate?

**Comment by Konicai** [comment]
Oops, you said that. Duplicate of #332
