### ISSUE TITLE
Mobs can attack through crevices of blocks

### ISSUE THREAD

**Issue by VenomousSteam81** [GeyserMC/Floodgate#343]
I don't know if there are any duplicates, but it would be kind of hard to find some.

Mobs can shoot, throw at, or attack Bedrock players if there are only 2 blocks around or 1 above them.
For clarity, take the iron door trap, remove the pressure plate, and replace the 4 iron doors with any other blocks, along with adding a block above the center.

**Comment by Konicai** [comment]
Does this happen to java players?

Please re-open this [here](https://github.com/GeyserMC/Geyser/issues/new?assignees=&labels=&template=bug_report.yml) with the additional information it asks for
