### ISSUE TITLE
MySQL times out when trying to connect to database

### ISSUE THREAD

**Issue by LeehamElectronics** [GeyserMC/Floodgate#345]
Using the latest version of Floodgate with the MySQL addon on Waterfall.

For the past 8 months I can't get it to work, I use MySQL for everything in my network and I 100% know how to set it up properly and I have tested to make sure the user and database are valid, yet when the proxy starts up it times out when trying to connect to MySQL.
Using the latest version of everything from Jenkins. Is there any way I can get more information from the console such as the reason why MySQL is failing? It seems pretty generic. Can anyone else confirm if the MySQL addon is working for them?
Console log:
![image](https://user-images.githubusercontent.com/51737378/184045025-3808c143-1898-4756-9801-481ef9598701.png)

Thanks

**Comment by Tim203** [comment]
Could you try the mysql database jar of the latest development build?
It should be fixed there.
