### ISSUE TITLE
Bedrock username to Floodgate UUID tool is not working (https://floodgate-uuid.heathmitchell1.repl.co/).

### ISSUE THREAD

**Issue by ZD-ChaofanJ** [GeyserMC/Floodgate#348]
I do apologize if this is not the correct place to report this issue.

When trying to enter a Bedrock username and obtain the Floodgate UUID using https://floodgate-uuid.heathmitchell1.repl.co/ it gives the following error:
"An error occurred: Looks like you just got hit with a security audit &#x1f61e; Please go to <a href="https://account.live.com/Activity">https://account.live.com/Activity</a> and authorise the server. Its IP is XXX.XXX.XXX.XX"

**Comment by Camotoy** [comment]
This isn't our tool but I will redirect this to the right person. Thanks.

**Comment by Camotoy** [comment]
Also this may be a XAPI.us bug and not Circuit's bug.

**Comment by ZD-ChaofanJ** [comment]
Thanks. I appreciate it.

**Comment by Camotoy** [comment]
The issue has been resolved.

**Comment by Heath123** [comment]
(context: I am the creator of that site)

Thanks for telling me, I approved the logins and everything should be working again now
