### ISSUE TITLE
Error flooding console 

### ISSUE THREAD

**Issue by abhisantos** [GeyserMC/Floodgate#349]
27.08 14:59:08 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:08 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:08 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:08 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:08 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:08 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:10 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:10 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:10 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:10 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:10 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:10 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:11 [Server] INFO yCarol_ executed command: /tell Matias2020 574.99
27.08 14:59:12 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:12 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:12 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:12 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:12 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:12 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:12 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:13 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:13 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:13 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:13 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:15 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:15 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:15 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:15 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:16 [Server] INFO Matias2020 executed command: /r e
27.08 14:59:16 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:16 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:16 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:16 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:16 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:16 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:16 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:18 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:18 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:18 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:18 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:20 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:20 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:20 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:20 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:20 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:20 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:21 [Server] INFO Matias2020 executed command: /r ta no msm preco q aq
27.08 14:59:22 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:22 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:22 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:22 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:22 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:22 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
27.08 14:59:23 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.

**Comment by Camotoy** [comment]
Please open a new issue on the Geyser repository and provide the backend server version and plugins as well. Thanks!
