### ISSUE TITLE
ProtocolSupport is incompatible

### ISSUE THREAD

**Issue by oezingle** [GeyserMC/Floodgate#35]
**Describe the bug**
When connecting with MCPE iOS, the user returns the error 
 Invalid packet id: 27
Only while using Floodgate authentication and the ProtocolSupport plugin. without floodgate, the system both works in online and offline modes. Java Minecraft players can connect in any version, as is supported by ProtocolSupport.

**To Reproduce**
Install Geyser-Bukkit, Floodgate-Bukkit and ProtocolSupport on a PaperMC server in /plugins/. Configure Geyser to use Floodgate. 
When the bug occurs, the output is exactly the same as that of an incorrectly configured Floodgate installation

**Server Version**
[17:13:44 INFO]: This server is running Paper version git-Paper-301 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**

**Minecraft: Bedrock Edition Version**
1.14.60 hotfix

**Comment by DoctorMacc** [comment]
Nevermind, transferred myself.

**Comment by Tim203** [comment]
Most of the time a packet 27 error means that Floodgate is configured incorrectly, but I'll add debug mode for the bukkit version soon so we can help you easier.

**Comment by jackson-57** [comment]
I had this issue way back, around the start of the year. I probably should have made an issue, lol

**Comment by LegacyGamerHD** [comment]
Works fine form me

**Comment by LegacyGamerHD** [comment]
Am using bungee

**Comment by Tim203** [comment]
ProtocolSupport support has been out for a while now (since last June), so I'm going to close this issue.
