### ISSUE TITLE
Tried to login as a java edition player!

### ISSUE THREAD

**Issue by WOLFRAGE99** [GeyserMC/Floodgate#350]
Server wont allow bedrock players to join.

Uninstalled all plugins, updated to the newest floodgate version, Updated spigot, still doesn't work.

[log.txt](https://github.com/GeyserMC/Floodgate/files/9448219/log.txt)

**Comment by Tim203** [comment]
You're using a development version of Floodgate.
Can you reproduce the same error on a master build?

**Comment by WOLFRAGE99** [comment]
> You're using a development version of Floodgate. Can you reproduce the same error on a master build?

Could I be referenced to this master version?

**Comment by onebeastchris** [comment]
https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/
download it here

**Comment by WOLFRAGE99** [comment]
![image](https://user-images.githubusercontent.com/83514798/187322284-41a1ef91-ecb1-4d99-86e8-47cf173547c4.png)

[latest.log](https://github.com/GeyserMC/Floodgate/files/9448619/latest.log)

I did that and now I get this error.

**Comment by Camotoy** [comment]
Disable `enforce-secure-profile` in `server.properties`.

**Comment by User12345678999** [comment]
did that and still need to log in with java

**Comment by onebeastchris** [comment]
try setting the "auth-type" in geyser's config.yml to "floodgate", that should likely fix it

**Comment by Tim203** [comment]
It sounds like the issue you're having has been resolved, given that there hasn't been a comment from the OP for almost two months now.
