### ISSUE TITLE
How to specify port for floodgate-mysql-database?

### ISSUE THREAD

**Issue by angushushu** [GeyserMC/Floodgate#359]
Hi, we are using floodgate-mysql-database.jar for local linking. However, our MySQL uses a port different than 3306, and seems this causes floodgate-mysql-database.jar unable to connect to our MySQL database. I wonder if there's a way to specify the port of MySQL in mysql.yml or somewhere else?

**Comment by Tim203** [comment]
I expect that in the hostname field you can just place the port number after the hostname.
E.g.: `host.name:1234`

**Comment by angushushu** [comment]
> I expect that in the hostname field you can just place the port number after the hostname. E.g.: `host.name:1234`

Hey Tim, I tried for the master branch, and it didn't work. I'm trying with the dev branch

**Comment by angushushu** [comment]
> I expect that in the hostname field you can just place the port number after the hostname. E.g.: `host.name:1234`

It worked with dev branch! Appreciated that!
