### ISSUE TITLE
Add Bedrock Form support to Floodgate

### ISSUE THREAD

**Issue by MVDW-Java** [GeyserMC/Floodgate#36]
Dear Floodgate Team,

I was wondering if it possible to add an API to Floodgate Bungee and Bukkit.
This is to check if a player is connected to Bedrock or Java and to send a custom GUI.

Thank you for this amazing project!

Kind regards,
Max.

**Comment by Heath123** [comment]
There already is a Floodgate API. There isn't GUI support in it yet, though.

**Comment by Heath123** [comment]
It's not documented but this is the closest thing:
https://github.com/GeyserMC/Geyser/wiki/Floodgate#using-placeholderapi
Look at the Placeholder API code maybe

**Comment by Heath123** [comment]
https://github.com/rtm516/FloodgatePlaceholders/blob/master/src/main/java/com/rtm516/FloodgatePlaceholders/Placeholder.java

**Comment by Tim203** [comment]
You can look at the AbstractFloodgateAPI in the common module and the implemenetations named FloodgateAPI in the other modules.
And like circuit (health) said, bedrock GUIs (forms) isn't supported yet but will be added after #30 is merged.

**Comment by Tim203** [comment]
Bedrock Form support has been added in Floodgate 2.0
