### ISSUE TITLE
Dev branch cannot apply skins on Spigot

### ISSUE THREAD

**Issue by Konicai** [GeyserMC/Floodgate#361]
Always uses paper api in the skin applier. See: https://github.com/GeyserMC/Floodgate/blob/359484b3bec2770961719cbd8cf26a879f284d86/spigot/src/main/java/org/geysermc/floodgate/pluginmessage/SpigotSkinApplier.java#L66

Log: https://mclo.gs/KKU4oHA

I'll see about fixing this today.

**Comment by Tim203** [comment]
The PR has been merged.
This issue has been fixed in 90e9b1e3fcbff8679c0ed4d10cc9aeeea0e640dd
