### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by xF3d33** [GeyserMC/Floodgate#367]
after about 10hrs of uptime my proxy starts using 2200% of cpu and players cannot join. 
that's also depend to how many players are online, for example if 150 players join this happen after 10 hrs of uptime, otherwise after more time

that's my config: https://paste.celestymc.it/itocayugiz

and i also got this error on my bungee console today https://paste.celestymc.it/ikajecopiy

i have geyser standalone

**Comment by xF3d33** [comment]
![image](https://user-images.githubusercontent.com/67204462/199010935-d5bd0ac2-d044-4d8e-98fe-9a3914aea8b6.png)
that's a sparkb profiler

**Comment by RednedEpic** [comment]
Will need a heap dump to track down this memory issue.

**Comment by xF3d33** [comment]
with spark?

**Comment by onebeastchris** [comment]
Spark is a plugin that helps you monitor performance for you server.
<https://spark.lucko.me/download>

To record performance on your server use:
`/spark profiler --thread * --timeout 60`. This will run for 60 seconds then it will automatically stop.
It'll probably lag the server a good deal but it'll give us a link we might be able to process.

**Comment by Camotoy** [comment]
That doesn't produce a heap dump, but I believe Spark has an option for that, too.

**Comment by xF3d33** [comment]
so wich command should i use?

**Comment by xF3d33** [comment]
i tried to create an headdump with spark on bukkit and it create a file of one to 3 gb.. what should i do with this file?

**Comment by Konicai** [comment]
Shared it here. If github says its too large, use a file sharing service

**Comment by mastermc05** [comment]
> i tried to create an headdump with spark on bukkit and it create a file of one to 3 gb.. what should i do with this file?

also can make a zip archive, heap dump usually is compressed with a good ratio

**Comment by xF3d33** [comment]
ok.. and what's inside this file? how can i open it?

**Comment by mastermc05** [comment]
> ok.. and what's inside this file? how can i open it?

inside that file is information about what was in your ram, you cn open it for example using eclipse memory analizer

**Comment by xF3d33** [comment]
ok gonna send the report today/tomorrow. atm i have the server online with floodgate (send-flood-data and player-linking disabled) and everything seems normal, but i can't use the api ofc...

**Comment by xF3d33** [comment]
https://mega.nz/file/wGJTQBgI#B9t6DOglsa6MbzbvFvONJOYa8P20AFxPsi1Dq4ojmC4 here's the heapdump @Redned235 @Konicai @mastermc05

**Comment by Tim203** [comment]
Can you send a Geyser dump as well? `/geyser dump`

**Comment by xF3d33** [comment]
https://dump.geysermc.org/bw3wYxIcujW1I5uOPeWRnnYPiHG5VfX9 @Tim203

**Comment by Camotoy** [comment]
Can you also send a list of plugins on BungeeCord?

**Comment by Tim203** [comment]
And plugin versions

**Comment by xF3d33** [comment]
> And plugin versions

of wich plugin?

**Comment by Tim203** [comment]
Mainly interested in plhidepro

**Comment by xF3d33** [comment]
plhide had a leak issue but they fixed and i have the latest version... i also don't have any problem with it atm

**Comment by Tim203** [comment]
But you're still having a memory leak? If so, can you record another heap dump when that happens

**Comment by xF3d33** [comment]
> But you're still having a memory leak? If so, can you record another heap dump when that happens

no i don't have any memory leak atm. and i have plhide. the memory leak only happen if i have floodgate (that now is disabled)

**Comment by Tim203** [comment]
And what if you remove plhidepro and enable Floodgate again?
We can't do much if you don't enable Floodgate

**Comment by xF3d33** [comment]
> And what if you remove plhidepro and enable Floodgate again? We can't do much if you don't enable Floodgate

ok, gonna let you know tmr

**Comment by PedroMPagani** [comment]
There seems to be a fix on plhidepro about memory leaks for bungee!

**Comment by Creeperz653** [comment]
Try https://www.spigotmc.org/resources/advancedplhide.98645 if it doesn’t work I’ve heard this plugin works well and it’s a free alternative to plhide pro and it’s open sourced !!

**Comment by xF3d33** [comment]
@Tim203 i tried and for now without plhide the server hasn't crashed... so what is the problem with that plugin?

the server may crash in the next hrs, but i think that we found the problem so...

**Comment by Creeperz653** [comment]
> @Tim203 i tried and for now without plhide the server hasn't crashed... so what is the problem with that plugin?
> 
> 
> 
> the server may crash in the next hrs, but i think that we found the problem so... 

Did you see what I recommended

**Comment by xF3d33** [comment]
update: the memory leak still happen even without plhide

![image](https://user-images.githubusercontent.com/67204462/202853095-c3f3f01f-a5a7-4f50-a9e3-d0e7870e7032.png)
@Tim203

**Comment by onebeastchris** [comment]
Can you record another heap dump & send it?

**Comment by PedroMPagani** [comment]
> update: the memory leak still happen even without plhide
> 
> ![image](https://user-images.githubusercontent.com/67204462/202853095-c3f3f01f-a5a7-4f50-a9e3-d0e7870e7032.png) @Tim203

Your ram usage is at 2.27GB, how is that a memory leak?

**Comment by xF3d33** [comment]
> Can you record another heap dump & send it?

yeah i can, give me some hrs

**Comment by xF3d33** [comment]
> Your ram usage is at 2.27GB, how is that a memory leak? You're also not limiting the RAM Usage, are you able to provide startup flags?
> 
> Node conditions too, whos using how much memory allocated (in the panel) & node specs.

the leak is the cpu load.. the bungee is in a crash state, some players (that were connected while this state started) can't connect again, cause bungee think that they are still connected, sometimes players cannot even join (like when the join the server it takes too much time)

this is the "error" that happen when bungee think that players are still connected 
![image](https://user-images.githubusercontent.com/67204462/202855401-6eec684a-f21b-4b00-8806-aa3ed932aa5f.png)

btw the ram is limited in the startup flags: 
java -Xms512M -Xmx4G -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -jar waterfall-1.19-506.jar

and the node is a R9 5950x with 128gb of RAM. cpu load is also around 30% so that's not the problem ofc (also because without floodgate i have no issues).

**Comment by PedroMPagani** [comment]
Are you able to provide LOGS of the crashes?

**Comment by DarkChromaMC** [comment]
I strongly believe that there is a memory leak issue with either GeyserMC or Floodgate, as we've been having problems with the proxy crashing for at least 2 years. To fix this, we had to increase the RAM allocated to the proxy to a very high amount and frequently restart the proxy. We also run a dedicated server with a 5950x processor, 128GB RAM, and 31GB allocated to Velocity, but it doesn't usually experience any problems unless the server has been running for more than five days or the player count has increased dramatically (which can take 2-3 days before the server 'crashes').

**Comment by Redned235** [comment]
> I strongly believe that there is a memory leak issue with either GeyserMC or Floodgate, as we've been having problems with the proxy crashing for at least 2 years. To fix this, we had to increase the RAM allocated to the proxy to a very high amount and frequently restart the proxy. We also run a dedicated server with a 5950x processor, 128GB RAM, and 31GB allocated to Velocity, but it doesn't usually experience any problems unless the server has been running for more than five days or the player count has increased dramatically (which can take 2-3 days before the server 'crashes').

Please provide a heap dump of when the proxy is using an excessive amount of memory if you are having memory issues.

**Comment by DarkChromaMC** [comment]
I have provided heap dumps in the geyesr discord server in order to try and resolve an issue, but it was easier for me to just restart the proxy. My players hate downtime and running heap dumps can cause the server to lag, which is especially problematic when the server is about to crash. However, I know with certainty that other large servers using geysermc+floodgate also require huge ram allocated to proxies, as bedrock users a ton of ram per player compared to java users. We also experienced more proxy crash issues when we introduced a custom model data texturepack for our bedrock players.

Here are some links:
https://discord.com/channels/613163671870242838/1008027013161959444/1022657669535911937 
https://discord.com/channels/613163671870242838/613170125696270357/926082563498446848

This is a heap dump I just took now. We've only got 70 players online now, so the ram on the proxy is still low.
https://drive.google.com/file/d/13WIPg-CW6pN4WT1fsH4c2sciI_uBYOGq/view?usp=sharing

**Comment by MCHalfAssed** [comment]
Also wanted to chime in. 

My server was only utilized 4GB/16GB RAM with 5 players online, with Geyser disabled (Floodgate was enabled). Stayed steady for a couple hours. 

I re-enabled Geyser and rebooted, and my server was automatically using 6GB/16GB after startup, and started slowly rising with 1 player online.

Here was a heapsummary from Spark: https://spark.lucko.me/MmSPO8xv7v

I'm not as smart as you all, so I'm only just pointing out what I noticed. If you need me to provide more data, please don't hesitate to let me know.

**Comment by xF3d33** [comment]
> I strongly believe that there is a memory leak issue with either GeyserMC or Floodgate, as we've been having problems with the proxy crashing for at least 2 years. To fix this, we had to increase the RAM allocated to the proxy to a very high amount and frequently restart the proxy. We also run a dedicated server with a 5950x processor, 128GB RAM, and 31GB allocated to Velocity, but it doesn't usually experience any problems unless the server has been running for more than five days or the player count has increased dramatically (which can take 2-3 days before the server 'crashes').

the leak is in Floodgate because i have GeyserStandalone. i also restart my server every night but i can't give to the proxy 32gb of ram... and also this might "fix" the crash, but when this happen, as you can see above, the cpu usage goes from 100% to 1000%...

i had to remove bedrock support for this..

**Comment by Tim203** [comment]
I keep forgetting to reply to this issue. Can you try to use the dev branch? I believe that the issue might be solved there.

**Comment by xF3d33** [comment]
> I keep forgetting to reply to this issue. Can you try to use the dev branch? I believe that the issue might be solved there.

what have you changed? and also, do i need to compile it by myself?

**Comment by Tim203** [comment]
You can download it here https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/development/

**Comment by xF3d33** [comment]
@Tim203 at the moment no crashs. but bedrock players in the tab are shown twice. i had no issues with the master branch. 
![image](https://user-images.githubusercontent.com/67204462/211201782-04da1167-2ba5-46b4-8386-9ff1206a4099.png)

**Comment by Tim203** [comment]
And the players get listed twice directly after join or did they relog?
Did you try to reload the server?
It's weird that players get listed twice

**Comment by Tim203** [comment]
And are you using Paper or Spigot?

**Comment by xF3d33** [comment]
> And the players get listed twice directly after join or did they relog? Did you try to reload the server? It's weird that players get listed twice

directly. it happened it 2 server with also different versions. 




> And are you using Paper or Spigot?

the first: git-Purpur-1632 (MC: 1.18.2)*
the other server: git-Paper-307 (MC: 1.19.2)

**Comment by xF3d33** [comment]
@Tim203

**Comment by Tim203** [comment]
Is this still an issue? If so, can you open a new issue for that.
The memory leak itself has been fixed.
