### ISSUE TITLE
Detect Windows vs Mobile players?

### ISSUE THREAD

**Issue by nickga66** [GeyserMC/Floodgate#368]
Hello, I would like to detect Windows Bedrock players on my Geyser Server.
I only want to allow Mobile players (iOS or Android) to play.
Is there any way through the API to block them? Any clue on how to differentiate them?

**Comment by Tim203** [comment]
You can use the Floodgate API to see on which platform they're playing. Using a combination of the wiki: https://wiki.geysermc.org/floodgate/api and the source code you can find what you want.
