### ISSUE TITLE
Breaks Fabric runServer/runClient targets

### ISSUE THREAD

**Issue by wereii** [GeyserMC/Floodgate#373]
This is more of an FYI, not sure if it's something you can fix here.

`net.fabricmc:fabric-loader` uses `org.objectweb.asm` from `org.ow2.asm:asm:9.3` but this mod includes it's own `org.objectweb.asm` implementation which is incompatible and will throw something along: 

```gradle
[13:44:43] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.19.3 with Fabric Loader 0.14.11
2022-12-12 13:44:43 INFO  FabricLoader/GameProvider:51 - Loading Minecraft 1.19.3 with Fabric Loader 0.14.11
[13:47:59] [main/ERROR] (FabricLoader) Uncaught exception in thread "main"
 java.lang.IllegalArgumentException: Unsupported class file major version 61
```

when running either one of the `runX` gradle tasks.

**Comment by Konicai** [comment]
Please use the Floodgate-Fabric repo for fabric issues

I believe I fixed this already in my 1.19.3 PR though

**Comment by Konicai** [comment]
Ah, apologies for the misunderstanding. Yeah, something doesn't seem right here, I'll take a look in a bit.

**Comment by wereii** [comment]
Yeah no worries I should have given full details. 

It does look like similar problem you fixed here https://github.com/GeyserMC/Floodgate-Fabric/pull/69/commits/c00b99c619a34543c01446cf835385fdcfac2da9

**Comment by wereii** [comment]
Awesome, thanks!
