### ISSUE TITLE
Add better message when linking is required when joining with an unlinked account

### ISSUE THREAD

**Issue by Phoenix616** [GeyserMC/Floodgate#378]
When `player-link.require-link` is set to `true` and someone joins without having their account linked previously this pretty unhelpful message will show:

![image](https://user-images.githubusercontent.com/5768781/210370522-159b7ece-0bc8-49e9-b4f8-d25160decb2f.png)

Using floodgate 2.2.0-SNAPSHOT (b74-4f36112) and Geyser 2.1.0-SNAPSHOT (b1261-03390b9)

It would be good if this would explain the issue and maybe even provide instructions on how to link, ideally via a configurable translation key so that it could be adjusted depending on server setup.

**Comment by makcuber** [comment]
fully agree this needs better wording for the player trying to connect. It should really be something configurable in the floodgate config file even.

**Comment by Konicai** [comment]
Configurable localization will likely become available when Floodgate is merged into Geyser

**Comment by Phoenix616** [comment]
This seems to still be broken or at least not localised correctly. No matter which file I try to add this to it doesn't work. Tried to ask this on the discord but nobody knew how to add this message. Tried adding to both the english and german locale of Geyser.

Dump: https://dump.geysermc.org/B6lVprYVOdlSvTTrEn6G8lOtc2ET3fBN

**Comment by Konicai** [comment]
Seems like Floodgate's languages submodule wasn't properly updated before 2.2.2 was released. If you want to add the translation manually, you'll need to modify the locale files of Floodgate, not Geyser, using the most recent translations: https://github.com/GeyserMC/languages/tree/floodgate

**Comment by Phoenix616** [comment]
Ah, that explains it. Can I just add them somewhere in the plugin folder as they don't seem to generate automatically there? (At least not for me)

**Comment by Konicai** [comment]
Floodgate doesn't have locale customization like Geyser does, so you would need to modify the locale files within the Floodgate jar

**Comment by Phoenix616** [comment]
Ugh, that's a bit annoying but I guess it's a workaround for now.
