### ISSUE TITLE
Floodgate causes crash

### ISSUE THREAD

**Issue by thenilsdev** [GeyserMC/Floodgate#390]
Whenever we have a few more players during the day and therefore more floodgate forms are created/edited we have a crash in the evening, which is caused by floodgate.

https://mclo.gs/noB4R53

# Server
- **Paper** `1.19.2 git-Paper-173`
- **floodgate** `2.2.0-SNAPSHOP (b74-4f36112)`
- **ViaVersion** `4.5.1`

# Proxy
- **Geyser** `2.1.0-SNAPSHOT (git-master-bad077d)`
- **floodgate** `2.2.0-SNAPSHOT (b74-4f36112)`

**Comment by Tim203** [comment]
This should be fixed in the latest commit of the development branch.
