### ISSUE TITLE
Floodgate API: Attempt to invoke interface method 'java.util.concurrent.CompletableFuture org.geysermc.floodgate.api.FloodgateApi.getUuidFor(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by SlimyFrog123** [GeyserMC/Floodgate#393]
I am attempting to use the Floodgate Java API in my Java project. I set up everything correctly in my Gradle build file, that is **not** an issue in any way.

This is the code that I have:
```
FloodgateApi floodgateApi = FloodgateApi.getInstance();

try {

    assert floodgateApi != null;

    CompletableFuture<UUID> uuidCompletableFuture = floodgateApi.getUuidFor(
            "SlimyFrog123");

    UUID userUuid = uuidCompletableFuture.get();

} catch (Throwable exception) {
    exception.printStackTrace();
}
```

When I call the `floodgateApi.getUuidFor` method, it dies, saying: `Attempt to invoke interface method 'java.util.concurrent.CompletableFuture org.geysermc.floodgate.api.FloodgateApi.getUuidFor(java.lang.String)' on a null object reference`

My imports, just in case they are needed, are:
```
import org.geysermc.floodgate.api.FloodgateApi;

import java.util.UUID;
import java.util.concurrent.CompletableFuture;
```

**Comment by Camotoy** [comment]
Your Gradle build file *could* be an issue if you're shading in the Floodgate API files into your jar file (open it up and see if the Floodgate API files are in there - if they are, that's your problem).

**Comment by SlimyFrog123** [comment]
@Camotoy It's actually not compiling to a jar file, this is a Android app. I am using Android Studio for a server control app.

Here are my dependencies:
```
implementation 'androidx.appcompat:appcompat:1.6.1'
implementation 'com.google.android.material:material:1.8.0'
implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
implementation 'org.geysermc.floodgate:api:2.2.0-SNAPSHOT'
testImplementation 'junit:junit:4.13.2'
androidTestImplementation 'androidx.test.ext:junit:1.1.5'
androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
```

And in my `settings.gradle`, here are my repositories:
```
google()
mavenCentral()
maven { url 'https://repo.opencollab.dev/maven-snapshots/' }
```

**Comment by onebeastchris** [comment]
so uh, are you trying to get a uuid for a player, right? because uh, the floodgate api is intended to be used in plugins to get info from the floodgate plugin, as the floodgate api is only really useful to show which floodgate players are online right now (which is why you'd hook into it).
If you are developing a standalone app and just want to get a floodgate uuid for any player, use the web api https://api.geysermc.org/docs; that seems more appropriate for the usecase
(atleast from my understanding, feel free to correct if your usecase is another)

**Comment by Camotoy** [comment]
Our API is *not* designed to be used like this, and we don't intend to offer support for this (you would need to shade in all of the `core` module which includes the implementation). See Chris's response. Thanks.

**Comment by SlimyFrog123** [comment]
@onebeastchris @Camotoy 
My apologies, I misunderstood! I was under the impression that the API could be used in _any_ Java-based project. I was originally planning to use the web API to get the UUID, and I guess I will do that. Thank you very much for your assistance!
