### ISSUE TITLE
Kick a Bedrock player with a generated link PIN as the kick reason

### ISSUE THREAD

**Issue by NyaomiDEV** [GeyserMC/Floodgate#396]
To enforce local linking, it'd be nice to have the linking procedure initiated on the Bedrock client.

I imagine this flow here:

0. In the config file, the following are set:
   - `require-link: true`
   - `enable-own-linking: true`

1. The player initiates the linking procedure by trying to join the server on Bedrock.
2. The server kicks the player, stating that the player should join with their Java account on the server, and it gives off the linking PIN within the reason message to complete the linking process.
3. The player then issues the usual `/linkaccount` command with the PIN shown in the kick reason.
4. The player will then terminate the linking process, and they are able to join the server on Bedrock.

**Comment by Tim203** [comment]
That is actually quite a good idea.
The only potential catch I can think about is when someone is e.g. streaming or doing anything else where you don't want this kind of info exposed.

**Comment by NyaomiDEV** [comment]
> The only potential catch I can think about is when someone is e.g. streaming or doing anything else where you don't want this kind of info exposed.

Streamers shouldn't stream this kind of stuff in the first place IMO; as for everything else it's up to server owners to notify players of this behaviour, and players should take care accordingly.

**Comment by Tim203** [comment]
> Streamers shouldn't stream this kind of stuff in the first place IMO

I mean all they have to do is join a server they never joined before and suddenly the viewers can link their account to the one of the streamer.
I'll keep the issue open for a while so that others can comment on it, because except from this idea I also don't really know how local linking can be improved.
Maybe some kind of lobby/limbo server where people can link their accounts?
I believe that most people who have this option enabled atm are doing something like that.

**Comment by NyaomiDEV** [comment]
> Maybe some kind of lobby/limbo server where people can link their accounts?
> I believe that most people who have this option enabled atm are doing something like that.

Wouldn't it be done with Velocity/BungeeCord though? I see things becoming complex from here...

---

Well, you can kick a player twice, first thing you say "You can't join the server, linking is mandatory. Try to join again to get your PIN", if you REALLY want to put people into a "buffered" kind of scenario.

**Comment by Tim203** [comment]
> Well, you can kick a player twice, first thing you say "You can't join the server, linking is mandatory. Try to join again to get your PIN", if you REALLY want to put people into a "buffered" kind of scenario.

True. I think this might be the best option

**Comment by NyaomiDEV** [comment]
Hello there;
I wonder if there was news for this particular feature.

**Comment by Tim203** [comment]
Not yet. New features will be implemented in an experimental branch which currently is not very stable.

**Comment by NyaomiDEV** [comment]
@Tim203 is there any way to get this for Floodgate 2?

**Comment by Tim203** [comment]
Support for this feature has been added in Floodgate 3.0. I've closed this issue to keep track of the progress.
