### ISSUE TITLE
Floodgate Null, and the command /Floodgate Version states Floodgate is not updated, even if it is.

### ISSUE THREAD

**Issue by Yomamaeatstoes** [GeyserMC/Floodgate#401]
Hello I have found a exception in Floodgate https://mclo.gs/wD4w8pq This is my version server is running Geyser version 2.1.0-SNAPSHOT (git-master-0f99abc) (Java: 1.19.4, Bedrock: 1.19.30/1.19.31 - 1.19.70/1.19.71) Paper version - This server is running Paper version git-Paper-504 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: b626528)
. It also says I am one version behind, but I am not. I tested this out by downloading the newest floodgate and doing /floodgate version and it still says I am not on the newest floodgate. There are 2 issues here 

My plugins I use are - AutoPay, *BanItem, BetterEconomy, BetterRTP, BetterRTP, ChatFilter, Chunky, Citizens, ClansLite, CommandBlockAsPlayer, DeluxeMenus, DisableBreeding, DiscordSRV, dynmap, ElytraSpeed, floodgate, Geyser-Spigot, GlobalTrackedMaps, HarmonyScoreboard, IllegalStack, IridiumSkyblock, Lifesteal, LuckPerms, mcMMO, Multiverse-Core, Multiverse-NetherPortals, Parkour, PL-Hide, PlaceholderAPI, PlayerBountiesPlus, PlayerKits, PlugManX, PremiumVanish, ProtocolLib, ScoreboardChatShop, *SecondThreadAPI, SilkySpawnersLITE, spark, Spartan, *Spleef, StackMob, StormerAntiNetherRoof, StormerAntiSpam, StormerHomesReloaded, StormerTPAReloaded, StormerWarpsReloaded, Themis, TNTRun_reloaded, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WorldEdit, WorldGuard

**Comment by Tim203** [comment]
Are you using the mojmap variant of Paper?

**Comment by Yomamaeatstoes** [comment]
Just regular paper
