### ISSUE TITLE
Floodgate skins conflict with SkinsRestorer

### ISSUE THREAD

**Issue by Sayrix** [GeyserMC/Floodgate#403]
Hello, Floodgate seems to make conflicts with SkinsRestorer, here is the issue on SkinsRestorer so you have more information to fix the bug https://github.com/SkinsRestorer/SkinsRestorerX/issues/1000

**Comment by Tim203** [comment]
Since Floodgate version 2.2.2 a SkinApplyEvent has been added. SkinsRestorer can listen to that and cancel it.
