### ISSUE TITLE
Players joining via Floodgate are seen as Java Edition players

### ISSUE THREAD

**Issue by DarkChromaMC** [GeyserMC/Floodgate#404]
Issue Description:
Players joining our server through Floodgate API are incorrectly identified as Java players, instead of GeyserMC users. This misidentification is causing plugins such as Anti-cheats to trigger false bans against Floodgate users, which is a critical issue.

Steps to Reproduce:
- Set up a Minecraft server that supports both Floodgate API and GeyserMC.
- Have a player join the server via Floodgate API.
- Observe that the player is identified as a Java player instead of a GeyserMC user.

Expected Result:
Players joining through Floodgate API should be correctly identified as GeyserMC users and should not trigger false bans from anti-cheat plugins.

Actual Result:
Players joining through Floodgate API are incorrectly identified as Java users and are being falsely banned by anti-cheat plugins.

Environment Details:
Minecraft version: 1.19.2
Floodgate API version: 2.2.2-SNAPSHOT (b77-089b9a7) (branch: master)
GeyserMC version: 2.1.0-SNAPSHOT (git-master-96260cc) (Java: 1.19.4, Bedrock: 1.19.30/1.19.31 - 1.19.70/1.19.71)
Server operating system: Pufferfish+ Purpur
Anti-cheat plugin name and version: Vulcan 2.7.3

Geyser Dump: https://dump.geysermc.org/LMDmBlYgnifwVwqmxIEkYUl1asL13Ht3

**Comment by onebeastchris** [comment]
Please attach a geyser dump by running "geyser dump" in the server console

**Comment by DarkChromaMC** [comment]
https://dump.geysermc.org/LMDmBlYgnifwVwqmxIEkYUl1asL13Ht3

**Comment by onebeastchris** [comment]
This is likely a configuration issue. Follow the guide below to set up floodgate data forwarding - after doing that, players will get recognized correctly.
https://wiki.geysermc.org/floodgate/setup/#installing-floodgate-also-on-spigot-servers-behind-bungeecord-or-velocity

**Comment by DarkChromaMC** [comment]
I set send-floodgate-data to true but players are still not being recognised as bedrock users unfortunately. Is there anyway to test if the floodgate API is working properly on the server-end?

**Comment by DarkChromaMC** [comment]
https://github.com/GeyserMC/Geyser/issues/3684

**Comment by Camotoy** [comment]
Did you install Floodgate on the backend server too?

**Comment by DarkChromaMC** [comment]
> Did you install Floodgate on the backend server too?

Yes

**Comment by Tim203** [comment]
> set send-floodgate-data to true but players are still not being recognised as bedrock users unfortunately. Is there anyway to test if the floodgate API is working properly on the server-end?

Yes, if you see `Floodgate player ... joined ...` or something similar in your backend console then you know that Floodgate working properly on your backend servers

**Comment by DarkChromaMC** [comment]
Floodgate is working properly, but this is a bug with floodgate in that its incorrectly identifying linked players as Java users, when they're playing on a Bedrock Edition console.

Please read my bug report for more details:
https://github.com/GeyserMC/Geyser/issues/3684

**Comment by Tim203** [comment]
Make sure you're on the latest version (at the moment build 52), as there was an issue with a change in BungeeCord (end March).

**Comment by AltoClef6115** [comment]
I have always been distressed with this problem. Is there any good solution now?

**Comment by Tim203** [comment]
I'm not sure how to replicate this issue. For all I know it can be a misconfiguration.
Please attach logs and the Floodgate & Geyser configs.

**Comment by MirMiksan** [comment]
I'm experiencing the exact same error; Floodgate sometimes thinks that a Bedrock player is a Java player.
