### ISSUE TITLE
get Skin from floodgate

### ISSUE THREAD

**Issue by RompeCraneos** [GeyserMC/Floodgate#405]
How can i get the Skin/SkinName/SkinData from a floodgate player?

**Comment by Camotoy** [comment]
You can just use the Bukkit API to get this data like a Java player?

**Comment by RompeCraneos** [comment]
Bukkit returns Steve skin from floodgate players

**Comment by Tim203** [comment]
The best way to get a Floodgate player's skin is by using the SkinApplyEvent, because their skin might not be ready depending on when you're checking their skin.
