### ISSUE TITLE
Generating key.pem

### ISSUE THREAD

**Issue by lecatos** [GeyserMC/Floodgate#406]
How to generate key.pem file to be used in Geyser Standalone without a server?
Note: This is Geyser Standalone not Spigot server runing Geyser and floodgate plugins.

**Comment by onebeastchris** [comment]
As explained on our floodgate setup guide:
You need to install floodgate on the java server where you are connecting to, as it is modifying the server to accept non-valid java accounts (and bedrock/floodgate accounts instead).
If you cannot use/put floodgate on that server, you cannot use floodgate auth mode.
