### ISSUE TITLE
Admin level account linking

### ISSUE THREAD

**Issue by MattElek** [GeyserMC/Floodgate#41]
**What feature do you want?**
Add some kind of /linkaccount subcommand or functionality that would allow server admins to link bedrock and java accounts without requiring players to do it themselves, and without requiring players to log in on both accounts.

**Alternatives?**
Manually editing the linked-players.db with a tool such as [DB Browser for SQLite](https://sqlitebrowser.org/).

**Comment by rtm516** [comment]
This could maybe be done if the bedrock player is online and we could lookup the uuid of the java player using Mojang's API.
`/linkaccountforce <java> <bedrock>` so it doesn't collide with any usernames

**Comment by Tim203** [comment]
Sounds ok to me

**Comment by MattElekHarris** [comment]
Maybe even an option to pass either UUID and XUID or even XUID in UUID format, because although I'm not sure of whatever legal issues using an XUID grabber in the actual code presents, it's still possible and easy to just use an online XUID grabber.

**Comment by jackson-57** [comment]
This would be really handy, especially if someone can't get their accounts to link for some reason, or if they are unable to (like if they don't have access to their Java account)

**Comment by AryToNeX** [comment]
I would add to this the possibility to add another admin command to force unlink players.

**Comment by lukeeey** [comment]
Relevant API endpoint for retrieving a gamertag from xuid and vice versa 

https://docs.microsoft.com/en-us/gaming/xbox-live/api-ref/xbox-live-rest/uri/profilev2/uri-usersuseridprofilesettingspeopleuserlistget#ID4EKB

**Comment by PotatoIQ** [comment]
any updates on this? still work on progress?

**Comment by yqs112358** [comment]
Any instructions about how to use this new command? 🤔 Just use `/linkaccount <A> <B>` in server console or as OP?

**Comment by Tim203** [comment]
The current version in the development branch uses `/linkedaccounts` with `add` `info` and `remove` being the subcommands.

**Comment by yqs112358** [comment]
So... is it possible to migrate this feature (commit https://github.com/GeyserMC/Floodgate/commit/c4cc692f6f72705e552b67c850b1f51b678dfb9f) to the main branch? ☺️ As a relatively important and useful feature for server owners.

**Comment by Tim203** [comment]
It depends on other changes made to Floodgate, so I don't think that'd be very productive. I'm aiming for Floodgate 3.0 & Geyser 3.0 to be released by the end of Q1, so compared to how long this issue has been open the wait won't be that long.
