### ISSUE TITLE
Bedrock players get instantly kicked

### ISSUE THREAD

**Issue by Novasky-Guy** [GeyserMC/Floodgate#410]
Bedrock players cause an uncaught exception as soon as they join a server and they disconnect after a few seconds.

This is the exception that shows up (usually multiple times in a row) before the disconnect:

> [11.05 22:34:20] [Server] [io.netty.channel.DefaultChannelPipeline]An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
[11.05 22:34:20] [Server] io.netty.channel.unix.Errors$NativeIoExceptionsendmmsg(..) failed: Operation not permitted

Server log outlining the issue:
https://paste.helpch.at/hatopubuni.css

Geyser Dump:
https://dump.geysermc.org/jJP2bMBMLEca2r7KhQnXU1ksaCKDI5xB

Using the latest version of everything

**Comment by Tim203** [comment]
Can you add a hidden config option to the Floodgate config: `debug: true`?
And upload your logs to https://mclo.gs/

**Comment by BladedDingo** [comment]
I've been having the same issue and I can't seem to figure it out.

Latest Log
https://mclo.gs/POXWxFy

geyser Dump
https://mclo.gs/Z0jAFbJ

**Comment by onebeastchris** [comment]
> I've been having the same issue and I can't seem to figure it out.
> 
> Latest Log
> https://mclo.gs/POXWxFy
> 
> geyser Dump
> https://mclo.gs/Z0jAFbJ

This looks like a Geyser issue. Could you open a new issue there, enable debug mode in geyser, restart, and send the new log with the error?

**Comment by BladedDingo** [comment]
> ue. Could you open a new issue there, enable debug mode in geyser, restart, and send the new log with the error?

I have created a new issue https://github.com/GeyserMC/Geyser/issues/3789
