### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by ghost** [GeyserMC/Floodgate#411]
**Error**
This is the error >> https://mclo.gs/Ejk1HgG

**Server Version and Plugins**
Current: git-Purpur-1967 (MC: 1.19.4)*

https://dump.geysermc.org/DclFCy1Qd5z7qk2DMnVj2Mv3TVpMtnTR

**Geyser Version**
Geyser-Spigot version 2.1.0-SNAPSHOT
floodgate version 2.2.2-SNAPSHOT (b??-2702bc3)

**Additional Context**
Using floodgate and MySQL database too.

**Comment by Tim203** [comment]
Oops, closed the wrong one.
But regardless this error is safe to ignore.
