### ISSUE TITLE
prefix for java

### ISSUE THREAD

**Issue by xAffan** [GeyserMC/Floodgate#414]
add an option to add prefix for java players so I can have something like [JAVA] xAffan and [BEDROCK] xAffan
and there would be no conflicts

**Comment by onebeastchris** [comment]
That's out of scope for floodgate. You can use e.g. luckperms, and create prefixes there - combined with e.g. the BedrockPlayerManager plugin, you could automatically put bedrock players in a bedrock group.
You shouldn't make the floodgate prefix longer than a single character anyways, as that will cause issues for longer usernames.

**Comment by onebeastchris** [comment]
For reference:
https://www.spigotmc.org/resources/bedrock-player-managment-for-floodgate-geyser.82278/
https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta
