### ISSUE TITLE
"Connection Closed" Error Message when BE player Join.

### ISSUE THREAD

**Issue by benho7599** [GeyserMC/Floodgate#417]
When I use a PE client to join the server.It show "Connection Closed" Error Message to me.I change the auth-type to floodgate already.
I use the latest version geyser and floodgate.Thank for helping ~

Server Log:
[https://mcpaste.io/a4625d802b07bfd7](https://mcpaste.io/a4625d802b07bfd7)

The dump:
[https://dump.geysermc.org/3ak0AddUFrjZdiefpYUKfuAfWtt0Giom](https://dump.geysermc.org/3ak0AddUFrjZdiefpYUKfuAfWtt0Giom)

**Comment by Tim203** [comment]
Does this issue still occur when you're not using Floodgate?
