### ISSUE TITLE
Packet Type: PLAYER_INFO, Type: UUID, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55

### ISSUE THREAD

**Issue by DimaSergeew** [GeyserMC/Floodgate#420]
### Describe the bug

This is a strange bug arose on the game version 1.19.3 and occurs only with the players Bedrock, for some reason after a while go player geyser who causes this error and until he leaves no one can not go, we have tried literally everything!!! unloaded almost all the plugins effect 0! I am somehow sure that the thing geysermc well just no options already
the error works even without Viaversion!!

### To Reproduce

Completely unpredictable

### Expected behaviour

There will be no such thing.

### Screenshots / Videos

https://pastebin.com/z0KbYf2n
![Screenshot_5](https://user-images.githubusercontent.com/75163645/211563973-6e4bd1b3-ae71-4642-9430-ccc6cf0e4e88.png)

### Server Version and Plugins

![Screenshot_6](https://user-images.githubusercontent.com/75163645/211564236-90579f89-6cff-4412-b6b2-c939c645d6be.png)
![Screenshot_7](https://user-images.githubusercontent.com/75163645/211564244-53b1b7e8-fdc7-442e-8403-8cd2c8b13dc0.png)
![Screenshot_8](https://user-images.githubusercontent.com/75163645/211564246-5b24c26c-6157-4cac-a57f-b2d02f96d3af.png)

### Geyser Dump

-

### Geyser Version

This server has Geyser version 2.1.0-SNAPSHOT (git-master-c928baf) (Java: 1.19.3, Bedrock: 1.19.20 - 1.19.50/1.19.51)

### Minecraft: Bedrock Edition Device/Version

PurPur 1.19.3

**Comment by bobhenl** [comment]
Hello, I have the same issue and it would be nice if this could be fixed. https://paste.gg/p/anonymous/9afaf055832949f88460fff1d56b975b -> message for all Java players is probably: 
![image](https://github.com/GeyserMC/Floodgate/assets/18662086/085d9943-f9a8-4060-8fc8-7ef988803eb0)

Firstly, I've asked on Viaversion Discord but they've redirected me here

Only Bedrock players were online, seems there's something wrong: _RutilantZulu570, _Fury_bolt3095, _Hades6772, _NightSheet23533, _ranithu2576, _Slay_king421, _Spacefrog01, _Primenation192

https://paste.gg/p/anonymous/6487c7f05e134c93b1d4cb18757e8733 here is the player who caused it for the first time

**Comment by masmc05** [comment]
> Hello, I have the same issue and it would be nice if this could be fixed. https://paste.gg/p/anonymous/9afaf055832949f88460fff1d56b975b -> message for all Java players is probably: ![image](https://user-images.githubusercontent.com/18662086/246626288-085d9943-f9a8-4060-8fc8-7ef988803eb0.png)
> 
> Firstly, I've asked on Viaversion Discord but they've redirected me here
> 
> Only Bedrock players were online, seems there's something wrong: _RutilantZulu570, _Fury_bolt3095, _Hades6772, _NightSheet23533, _ranithu2576, _Slay_king421, _Spacefrog01, _Primenation192
> 
> https://paste.gg/p/anonymous/6487c7f05e134c93b1d4cb18757e8733 here is the player who caused it for the first time

if it's this issue then you can fix yourself by compiling a custom floodgate where you remove https://github.com/GeyserMC/Floodgate/blob/227858930d98dc8e89054b38edebc3b432c0a5eb/spigot/src/main/java/org/geysermc/floodgate/listener/PaperProfileListener.java#L42-L64 like that 
![image-32](https://github.com/GeyserMC/Floodgate/assets/63639746/57b2d486-9c33-4204-a99f-23870fbd222c)

it fixed for my server and for other 1.19.3-1.20.1 servers

**Comment by JHarris12345** [comment]
This also fixed it for me. Can we fix this in the main floodgate version as it's becoming a huge issue. Thanks

**Comment by Tim203** [comment]
That code you're asking us to remove has been added for a reason: to fix the February 2 2022 Mojang authentication changes.
This was an issue where suddenly (due to the API changes) no Bedrock players were able to connect to Paper and forks server software (also Bungee and Velocity), so this isn't something that I'll remove without consideration.

I personally haven't been able to replicate the issue (as I don't have this issue myself) and I also wasn't able to find what's causing this issue in the first place.

**Comment by JHarris12345** [comment]
@Tim203 Is that issue still valid though? Because if it’s as big an issue as you say, then how comes no one has issues using a fork that comments it all out? No one has further issues from doing so.

The problem with this is that it’s been going on for so long and no one has found a way to recognise what causes it as it is so incredibly random

**Comment by Tim203** [comment]
I haven't tested that. But that code isn't needed for backend servers anyway when you have Floodgate on your proxy.
That's because we also apply that same fix to Bungee and Velocity, as not everyone has Floodgate on their backend servers.

**Comment by JHarris12345** [comment]
Ahh so we dont need it at all on our spigot floodgate. Thats good news as I can just keep it removed

**Comment by Camotoy** [comment]
For those who get this bug, could you try https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/fix-weird-via-issue/ and see if it solves the issue?

**Comment by spookymgmt** [comment]
Issue is still persistent. It's been an issue for over a year now. Can this just be merged already?

**Comment by Kas-tle** [comment]
Should be resolved in latest build.
