### ISSUE TITLE
SkinApplyEvent is never triggered

### ISSUE THREAD

**Issue by xknat** [GeyserMC/Floodgate#426]
As a follow up from #403:
We found out that the event SkinApplyEvent is not being executed.

In our testing setup, we **did in fact register the event**, just not in our public code:

https://github.com/SkinsRestorer/SkinsRestorerX/blob/dev/shared/src/main/java/net/skinsrestorer/shared/floodgate/FloodgateUtil.java
https://github.com/SkinsRestorer/SkinsRestorerX/blob/dev/shared/src/main/java/net/skinsrestorer/shared/floodgate/FloodgateListener.java

We do register the event here: https://github.com/SkinsRestorer/SkinsRestorerX/blob/84765e53ccb73521de8e9a79f3fad1f03062bc67/shared/src/main/java/net/skinsrestorer/shared/plugin/SRPlugin.java#L402

**Comment by xknat** [comment]
Any ETA on this?

**Comment by Tim203** [comment]
Hey, I just tried to see whether the event is fired and they're fired on all platforms.

**Comment by xknat** [comment]
> Hey, I just tried to see whether the event is fired and it's fired on all platforms.

Did we register / handle the event wrong?

**Comment by Tim203** [comment]
I was able to find the issue. This issue is (apparently) not covered in the unit tests and I only tested whether the event was fired, not with an actual subscriber. I'll be fixing this issue shortly.

**Comment by xknat** [comment]
> I was able to find the issue. This issue is (apparently) not covered by the unit tests and I only tested whether the event was fired, not with an actual subscriber. I'll be fixing this issue shortly.

Thanks for the update.
This will fit nicely in our v15 major update

**Comment by Tim203** [comment]
This issue has been fixed in the latest build - 68
