### ISSUE TITLE
Add Offline UUID support

### ISSUE THREAD

**Issue by Cyanoure** [GeyserMC/Floodgate#431]
On our school network the mojang servers are blocked so we can't run the server in online mode.
We want to play together on PCs and phones.
Some of us have linux and there is no bedrock edition on linux. They don't always use the same platforms and the UUID is different if they joins from Android even if they use the same username and all items are missing from the inventory.
I would like to see a solution like in the #77 PR.

**Comment by Konicai** [comment]
That PR was closed for reasons described within it. If you're joining from a different bedrock device with the same xbox account and getting a different UUID, it sounds like you're in offline-xbox territory, which isn't supported or condoned.
