### ISSUE TITLE
help me pls

### ISSUE THREAD

**Issue by egeozcelik2** [GeyserMC/Floodgate#436]
No one is looking at github at the link I've been waiting for 19 hours please help please.          

https://github.com/GeyserMC/Geyser/issues/4031
 this is very important to me please help

**Comment by Camotoy** [comment]
Please do not bump issues - someone will get around to addressing your issue when they can. Remember this is a volunteer project - no one gets paid for doing this.

Thanks!

**Comment by onebeastchris** [comment]
Please stop. The error you're getting is in no way related to Floodgate, and cross-posting here (or any other repository) won't get you help quicker.

**Comment by egeozcelik2** [comment]
I know I'm very tight, but what do you suggest I do? I can't sleep for a week because of this, my company is hurting and I can't get help from you, please show me a way (sorry for English)
