### ISSUE TITLE
information missing tag

### ISSUE THREAD

**Issue by egeozcelik2** [GeyserMC/Floodgate#437]
This tag was given but I didn't know what to do so I opened it from here. I have disturbed you for a few days. i'm really sorry about this i'm so sorry i slept very little for 1 week because of this problem please help (sorry for my english)
(sorry again)
I hope you understand me

**Comment by onebeastchris** [comment]
Please stop posting about your issue in unrelated repositories. I added the tag there since there is not enough info currently to diagnose the issue, and once someone has time to look into it, there will be further responses there.
