### ISSUE TITLE
geyser.auth.floodgate.encryption_fail

### ISSUE THREAD

**Issue by JeffTheMurderCat** [GeyserMC/Floodgate#440]
I've been trying to fix this issue for a couple of days and I was wondering if any could help solve this issue for me.

![Screenshot (1)](https://github.com/GeyserMC/Floodgate/assets/102166148/50620ef0-7457-40ca-abb3-523ff705b956)

I'm using 1.20.1 java server that runs on Apex Hosting paper 1.20.1

https://mclo.gs/UhQI9cn

**Comment by Tim203** [comment]
Duplicate of Geyser#4054
