### ISSUE TITLE
Error when trying to whitelist bedrock player

### ISSUE THREAD

**Issue by Exquaker** [GeyserMC/Floodgate#444]
whenever I try to run "fwhitelist add [bedrock username]",  I get this error in the console:

[https://pastebin.com/xJ4KhZCb]

checked with multiple people and I got the same error
Thanks for help in advance!

**Comment by HideyBoi** [comment]
I'm getting the same error.
![image](https://github.com/GeyserMC/Floodgate/assets/62223632/8bc6d4b8-39c0-4638-a46f-24628003abea)
Here's my version info
![image](https://github.com/GeyserMC/Floodgate/assets/62223632/ce33de4d-a5b7-4ed5-a5df-acbf2f31c729)

**Comment by Exquaker** [comment]
Hey, I managed to get around it by having the player online on the server (you will have to temporarily turn off whitelist). It is definitely not ideal and I hope it gets fixed. Hope this helps!

[my reddit post about it if u want it for smth idk](https://www.reddit.com/r/admincraft/comments/165tjmt/floodgate_whitelist_command_not_working/)
