### ISSUE TITLE
[WARNING] [floodgate] en_ is not a supported Floodgate language. 

### ISSUE THREAD

**Issue by IDIXZ** [GeyserMC/Floodgate#446]
` **Unbundling libraries to /home/gs-41638/bundler

Starting server

Loading libraries, please wait...

[INFO] Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'

[INFO] Loaded 7 recipes

[INFO] Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'

[INFO] Loaded 7 recipes

[INFO] Starting minecraft server version 1.20.1

[INFO] > Loading properties

[INFO] This server is running CraftBukkit version 3870-Spigot-d2eba2c-78796c9 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

[INFO] Debug logging is disabled

[INFO] Server Ping Player Sample Count: 12

[INFO] Using 4 threads for Netty based IO

[INFO] Default game type: SURVIVAL

[INFO] Generating keypair

[INFO] Starting Minecraft server on *:41638

[INFO] Using epoll channel type

[INFO] [floodgate] Loading floodgate v2.2.2-SNAPSHOT (b69-492be77)

[WARNING] [floodgate] en_ is not a supported Floodgate language.

[INFO] [floodgate] Took 669ms to boot Floodgate

[INFO] [Geyser-Spigot] Loading Geyser-Spigot v2.2.0-SNAPSHOT

[INFO] [Geyser-Spigot] Loading extensions...

[INFO] [Geyser-Spigot] Loaded 0 extension(s)

[INFO] Preparing level "world"

[INFO] -------- World Settings For [world] --------

[INFO] Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false

[INFO] Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64

[INFO] Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false

[INFO] Experience Merge Radius: 3.0

[INFO] Mob Spawn Range: 6

[INFO] Cactus Growth Modifier: 100%

[INFO] Cane Growth Modifier: 100%

[INFO] Melon Growth Modifier: 100%

[INFO] Mushroom Growth Modifier: 100%

[INFO] Pumpkin Growth Modifier: 100%

[INFO] Sapling Growth Modifier: 100%

[INFO] Beetroot Growth Modifier: 100%

[INFO] Carrot Growth Modifier: 100%

[INFO] Potato Growth Modifier: 100%

[INFO] Wheat Growth Modifier: 100%

[INFO] NetherWart Growth Modifier: 100%

[INFO] Vine Growth Modifier: 100%

[INFO] Cocoa Growth Modifier: 100%

[INFO] Bamboo Growth Modifier: 100%

[INFO] SweetBerry Growth Modifier: 100%

[INFO] Kelp Growth Modifier: 100%

[INFO] TwistingVines Growth Modifier: 100%

[INFO] WeepingVines Growth Modifier: 100%

[INFO] CaveVines Growth Modifier: 100%

[INFO] Custom Map Seeds: Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645

[INFO] Max TNT Explosions: 100

[INFO] Tile Max Tick Time: 50ms Entity max Tick Time: 50ms

[INFO] Zombie Aggressive Towards Villager: true

[INFO] Item Merge Radius: 2.5

[INFO] Item Despawn Rate: 6000

[INFO] View Distance: 10

[INFO] Simulation Distance: 10

[INFO] Allow Zombie Pigmen to spawn from portal blocks: true

[INFO] Arrow Despawn Rate: 1200 Trident Respawn Rate:1200

[INFO] Nerfing mobs spawned from spawners: false

[INFO] -------- World Settings For [world_nether] --------

[INFO] Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false

[INFO] Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64

[INFO] Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false

[INFO] Experience Merge Radius: 3.0

[INFO] Mob Spawn Range: 6

[INFO] Cactus Growth Modifier: 100%

[INFO] Cane Growth Modifier: 100%

[INFO] Melon Growth Modifier: 100%

[INFO] Mushroom Growth Modifier: 100%

[INFO] Pumpkin Growth Modifier: 100%

[INFO] Sapling Growth Modifier: 100%

[INFO] Beetroot Growth Modifier: 100%

[INFO] Carrot Growth Modifier: 100%

[INFO] Potato Growth Modifier: 100%

[INFO] Wheat Growth Modifier: 100%

[INFO] NetherWart Growth Modifier: 100%

[INFO] Vine Growth Modifier: 100%

[INFO] Cocoa Growth Modifier: 100%

[INFO] Bamboo Growth Modifier: 100%

[INFO] SweetBerry Growth Modifier: 100%

[INFO] Kelp Growth Modifier: 100%

[INFO] TwistingVines Growth Modifier: 100%

[INFO] WeepingVines Growth Modifier: 100%

[INFO] CaveVines Growth Modifier: 100%

[INFO] Custom Map Seeds: Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645

[INFO] Max TNT Explosions: 100

[INFO] Tile Max Tick Time: 50ms Entity max Tick Time: 50ms

[INFO] Zombie Aggressive Towards Villager: true

[INFO] Item Merge Radius: 2.5

[INFO] Item Despawn Rate: 6000

[INFO] View Distance: 10

[INFO] Simulation Distance: 10

[INFO] Allow Zombie Pigmen to spawn from portal blocks: true

[INFO] Arrow Despawn Rate: 1200 Trident Respawn Rate:1200

[INFO] Nerfing mobs spawned from spawners: false

[INFO] -------- World Settings For [world_the_end] --------

[INFO] Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false

[INFO] Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64

[INFO] Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false

[INFO] Experience Merge Radius: 3.0

[INFO] Mob Spawn Range: 6

[INFO] Cactus Growth Modifier: 100%

[INFO] Cane Growth Modifier: 100%

[INFO] Melon Growth Modifier: 100%

[INFO] Mushroom Growth Modifier: 100%

[INFO] Pumpkin Growth Modifier: 100%

[INFO] Sapling Growth Modifier: 100%

[INFO] Beetroot Growth Modifier: 100%

[INFO] Carrot Growth Modifier: 100%

[INFO] Potato Growth Modifier: 100%

[INFO] Wheat Growth Modifier: 100%

[INFO] NetherWart Growth Modifier: 100%

[INFO] Vine Growth Modifier: 100%

[INFO] Cocoa Growth Modifier: 100%

[INFO] Bamboo Growth Modifier: 100%

[INFO] SweetBerry Growth Modifier: 100%

[INFO] Kelp Growth Modifier: 100%

[INFO] TwistingVines Growth Modifier: 100%

[INFO] WeepingVines Growth Modifier: 100%

[INFO] CaveVines Growth Modifier: 100%

[INFO] Custom Map Seeds: Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645

[INFO] Max TNT Explosions: 100

[INFO] Tile Max Tick Time: 50ms Entity max Tick Time: 50ms

[INFO] Zombie Aggressive Towards Villager: true

[INFO] Item Merge Radius: 2.5

[INFO] Item Despawn Rate: 6000

[INFO] View Distance: 10

[INFO] Simulation Distance: 10

[INFO] Allow Zombie Pigmen to spawn from portal blocks: true

[INFO] Arrow Despawn Rate: 1200 Trident Respawn Rate:1200

[INFO] Nerfing mobs spawned from spawners: false

[INFO] Preparing start region for dimension minecraft:overworld

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 15%

[INFO] Preparing spawn area: 55%

[INFO] Preparing spawn area: 97%

[INFO] Time elapsed: 7518 ms

[INFO] Preparing start region for dimension minecraft:the_nether

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 4%

[INFO] Preparing spawn area: 74%

[INFO] Time elapsed: 3685 ms

[INFO] Preparing start region for dimension minecraft:the_end

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 53%

[INFO] Time elapsed: 3779 ms

[INFO] [floodgate] Enabling floodgate v2.2.2-SNAPSHOT (b69-492be77)

[INFO] [Geyser-Spigot] Enabling Geyser-Spigot v2.2.0-SNAPSHOT

[INFO] Server permissions file permissions.yml is empty, ignoring it

[INFO] [Geyser-Spigot] ******************************************

[INFO] [Geyser-Spigot]

[INFO] [Geyser-Spigot] Loading Geyser version 2.2.0-SNAPSHOT (git-master-69f89ed)

[INFO] [Geyser-Spigot]

[INFO] [Geyser-Spigot] ******************************************

[INFO] [Geyser-Spigot] Started Geyser on 0.0.0.0:19132

[INFO] [Geyser-Spigot] Done (6.252s)! Run /geyser help for help!

[INFO] Done (27.004s)! For help, type "help"

[INFO] Starting GS4 status listener

[INFO] Query running on 0.0.0.0:41638

[INFO] Thread Query Listener started

say §cServer§c.pro §b- §bFree §bGame §bHosting. §6Upgrade §6to §6remove §6ads.

[INFO] [Not Secure] [Server] §cServer§c.pro §b- §bFree §bGame §bHosting. §6Upgrade §6to §6remove §6ads.**

**Comment by IDIXZ** [comment]
I don't know what to do anymore, I need help

**Comment by Konicai** [comment]
It's just a warning - it'll default to `en_us` in this case.

The warning occurs because your system has `en_` as its locale. You can specify a custom locale in floodgate's config.

**Comment by IDIXZ** [comment]
> It's just a warning - it'll default to `en_us` in this case.
> 
> The warning occurs because your system has `en_` as its locale. You can specify a custom locale in floodgate's config.

![Screenshot_2023-09-13-12-19-45-059_org.mozilla.firefox.png](https://github.com/GeyserMC/Floodgate/assets/106037508/ff3874c8-de55-41f5-b493-1f6d5c52eb53)

So, I change it to en_us ?

**Comment by IDIXZ** [comment]
> It's just a warning - it'll default to `en_us` in this case.
> 
> The warning occurs because your system has `en_` as its locale. You can specify a custom locale in floodgate's config.

![Screenshot_2023-09-13-12-19-45-059_org.mozilla.firefox.png](https://github.com/GeyserMC/Floodgate/assets/106037508/ff3874c8-de55-41f5-b493-1f6d5c52eb53)

So, I change it to en_us ?

**Comment by IDIXZ** [comment]
> It's just a warning - it'll default to `en_us` in this case.
> 
> The warning occurs because your system has `en_` as its locale. You can specify a custom locale in floodgate's config.

I keep getting the same error

**Comment by Konicai** [comment]
You need to uncomment the line. As I said already, its just a warning, and Floodgate is booting completely okay. Please join our discord if you need any further help
