### ISSUE TITLE
Bedrock player skin issue after switching servers.

### ISSUE THREAD

**Issue by Fridtjof-DE** [GeyserMC/Floodgate#476]
## Describe the bug
Bedrock players can't see the skin and cape of another bedrock player that has a linked account after switching servers in a proxy network. Instead they see one of the default skins.

The problem almost always occurs after any (locally)? linked Bedrock player changes servers using a Bedrock client within a proxy network. When this happens, other players using a Bedrock client no longer see the skin and cape of the player who has switched servers and the player who has switched no longer sees the skins and capes of all other linked players using a Bedrock client.

All players will always see their own skin correctly.

The skins and capes of all players using a Java client are always displayed correctly.

All skins and capes are always displayed correctly for players using a Java client.

There are no problems with Bedrock players who are not linked.

I experience the problem with local linking, I have not tried global linking.

## To Reproduce
1. Join a proxy network with two (locally)? linked accounts using Bedrock clients
2. a. Switch servers within the network with the first account and then also switch to the server with the secound
2. b. Switch servers within the network with the first account and then switch back to the first server
3. Experience the problem on both clients

## Expected behaviour
Skins and capes should be displayed correctly

## Screenshots / Videos
Before switching server with "Fridtjof":
![before](https://github.com/GeyserMC/Floodgate/assets/38737231/f3ec94dd-2533-49fc-82d0-17a189fa1cc7)

After switching server with "Fridtjof":
![after](https://github.com/GeyserMC/Floodgate/assets/38737231/bac957f6-1c3d-4e10-b26a-d349c81e7713)

## Server Version and Plugins
Velocity 3.3.0-SNAPSHOT (git-a54d8c68-b307)
git-Purpur-2105 (MC: 1.20.4)
authlib-injector-1.2.4.jar (I'm using a custom auth server but this shouldn't be the fault because everything works on first join.)
no relevant backend plugins (just floodgate, luckperms...)

## Geyser Dump
https://dump.geysermc.org/eGWOm1H2VTvCobB8749gN4fRSEjb13tq

## Minecraft: Bedrock Edition Device/Version
v1.20.51 @ Windows 10, iPhone, iPad

**Comment by onebeastchris** [comment]
Did you set up floodgate forwarding?
See here for reference: https://wiki.geysermc.org/floodgate/setup/#installing-floodgate-also-on-spigot-servers-behind-bungeecord-or-velocity

**Comment by onebeastchris** [comment]
Additionally, does it work when *not* using custom auth servers?

**Comment by Fridtjof-DE** [comment]
> Did you set up floodgate forwarding? See here for reference: https://wiki.geysermc.org/floodgate/setup/#installing-floodgate-also-on-spigot-servers-behind-bungeecord-or-velocity

Yes



> Additionally, does it work when _not_ using custom auth servers?

Yes

**Comment by Tim203** [comment]
This might be an issue that's fixed in the upcoming Floodgate 3.0.
I'll have to look into it

**Comment by kexility** [comment]
Try using the SkinRestorer plugin?
That works for my network.

**Comment by Tim203** [comment]
This issue is probably solved by a version released in May.
Let me know if the issue still persists and I'll reopen the issue.
