### ISSUE TITLE
Bedrock players dont get kicked when they join on java using account linking

### ISSUE THREAD

**Issue by betafruit** [GeyserMC/Floodgate#477]
When you set up account linking for your account and join a geyser server on java, then on bedrock your java account will be kicked because you logged in from a different client, but when you do the same in reverse (login to the server on bedrock, then on java) the bedrock player enters a weird state of frozen time where they aren't on the server and can still do basic interactions, except nothing they do is saved.

This is a problem because the bedrock player isn't ever notified that they are in this weird state where they should have been kicked, and will lose all their progress they make because it's not real progress.

**Comment by Tim203** [comment]
It's been a while, is this issue still happening? If so, could you please add replication steps. Is for example stock Bungee + Geyser + Floodgate and a Spigot server enough to replicate this issue?
I'm closing this issue for now, but will reopen it when you say its still a problem.
