### ISSUE TITLE
Bedrock players' skin disappears on Java players' side on join

### ISSUE THREAD

**Issue by MATRIX-feather** [GeyserMC/Floodgate#478]
When a bedrock player joins the server with a linked account, their skin shows as one of the default skins on other Java players' side. This issue exists until they re-join the backend server where the bedrock players at:

https://github.com/GeyserMC/Floodgate/assets/55654482/20dc9736-f8a1-4cc4-a45b-aa7112c2e7b4

Floodgate configuration: https://paste.gg/p/anonymous/a4187c14cf3245a485a5fb3b81e048d5
Geyser dump: https://dump.geysermc.org/wXG9KCTHVd6PtmsgGfwx5SxcraXnLYae

Floodgate is installed both on the proxy and the backend, and the backend server doesn't have Geyser installed.

**Comment by Tim203** [comment]
Should be fixed once #509 is merged
