### ISSUE TITLE
`Downstream packet error! Failed to create tag.` when Bedrock players try to connect

### ISSUE THREAD

**Issue by daviderazza** [GeyserMC/Floodgate#483]
Hi, i'm trying to use Geyser and Floodgate on my paper server (it's not a proxy) but it keeps sending this error:

` /***.**.***.***:***** tried to connect!
29.01 20:11:44 [Server] INFO Player connected with username redyt008
29.01 20:11:44 [Server] INFO redyt008 (logged in as: redyt008) has connected to the Java server
29.01 20:11:44 [Server] INFO UUID of player .redyt008 is ********-****-****-****-************
29.01 20:11:45 [Server] INFO Floodgate player logged in as .redyt008 joined (UUID: ********-****-****-****-************)
29.01 20:11:45 [Server] WARN Downstream packet error! Failed to create tag.`

# Enviroment Details:
Minecraft Version: `This server is running Paper version git-Paper-405 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 3841722)`
GeyserMC Version: `This server is running Geyser version 2.2.0-SNAPSHOT (git-master-d63a70d) (Java: 1.20.2, Bedrock: 1.20.0/1.20.1 - 1.20.50)`
Floodgate Version: `You're currently on 2.2.2-SNAPSHOT (b90-2886a71) (branch: master)`
To check the other plugins installed see the GeyserMC dump below:
https://dump.geysermc.org/YtPc0UP77khT8ECYSYSVg3qgmZxHnmBl

**Comment by onebeastchris** [comment]
Update ViaVersion to 4.9.3, that resolves it.

**Comment by onebeastchris** [comment]
https://ci.viaversion.com/job/ViaVersion/786/
