### ISSUE TITLE
crashing on startup

### ISSUE THREAD

**Issue by IXSENPA1XI** [GeyserMC/Floodgate#491]
here is the crash report 
[crash-2024-03-19_18.42.06-server.txt](https://github.com/GeyserMC/Floodgate/files/14657638/crash-2024-03-19_18.42.06-server.txt)
and here is log 
[latest.log](https://github.com/GeyserMC/Floodgate/files/14657640/latest.log)
[debug.log](https://github.com/GeyserMC/Floodgate/files/14657641/debug.log)

**Comment by onebeastchris** [comment]
This is still not a Floodgate issue - Floodgate-neoforge doesn't even exist.
For questions about how to run a NeoForge server, I'd recommend to ask in the NeoForge discord.
