### ISSUE TITLE
Maven build error

### ISSUE THREAD

**Issue by alfdef1** [GeyserMC/Floodgate#5]
I cannot build this project, i get the following error:

`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.                                                                                     1:compile (default-compile) on project floodgate-common: Compilation failure: Co                                                                                     mpilation failure:
[ERROR] /home/xevento/temp/Floodgate/common/src/main/java/org/geysermc/floodgate                                                                                     /FloodgatePlayer.java:[4,35] cannot find symbol
[ERROR]   symbol:   class BedrockData
[ERROR]   location: package org.geysermc.floodgate.util
[ERROR] /home/xevento/temp/Floodgate/common/src/main/java/org/geysermc/floodgate                                                                                     /FloodgatePlayer.java:[39,21] cannot find symbol
[ERROR]   symbol:   class BedrockData
[ERROR]   location: class org.geysermc.floodgate.FloodgatePlayer
[ERROR] /home/xevento/temp/Floodgate/common/src/main/java/org/geysermc/floodgate                                                                                     /FloodgateConfig.java:[8,35] cannot find symbol
[ERROR]   symbol:   class EncryptionUtil
[ERROR]   location: package org.geysermc.floodgate.util
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit                                                                                     ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea                                                                                     d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc                                                                                     eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :floodgate-common
`

**Comment by Tim203** [comment]
You have to compile the plugin branch of Geyser first, thr plugin branch contains the missing classes

**Comment by alfdef1** [comment]
Thanks, it works like that!
