### ISSUE TITLE
Add support to MySQL

### ISSUE THREAD

**Issue by MastoryMd5** [GeyserMC/Floodgate#51]
Hi, i'm a server owner and i have multiple proxyies, this plugin is really revolutionary but the circumstances makes the account linking impossible.

If i have multiple proxies i can't link the account on all the proxies so i might suggest to create a hook with mysql that can link multiple proxies so we can have the benefits of linking account but with multi proxy support.

**Comment by rtm516** [comment]
Its a feature we are planning on adding and are working on.

**Comment by Tim203** [comment]
This is available in Floodgate 2.0

**Comment by LeehamElectronics** [comment]
> This is available in Floodgate 2.0

Has anyone actually tried this lately? For the past 8 months I can't get it to work, I use MySQL for everything in my setup and I 100% know how to set it up properly and I have tested to make sure the user and database are valid, yet when the proxy starts up it times out when trying to connect to MySQL.
![image](https://user-images.githubusercontent.com/51737378/183831945-b28d77fa-27f8-4d13-b4ef-e92f9ea18f1c.png)

@Tim203 
@detobel36

**Comment by Chew** [comment]
Please make a new issue, and do not necro-post extremely old and unrelated issues...

**Comment by LeehamElectronics** [comment]
https://github.com/GeyserMC/Floodgate/issues/345

> Please make a new issue or ask on [Discord](https://discord.gg/geysermc), and do not necro-post extremely old and unrelated issues...
