### ISSUE TITLE
Install floodgate-velocity on velocity cause Java player cannot login

### ISSUE THREAD

**Issue by cgw2023** [GeyserMC/Floodgate#513]
I am trying to convert from waterfall to velocity, I am generating all file first the first time so that all files are new.

Problem:
When I put floodgate-velocity in velocity plugin folder, my java client will always timed-out, when i remove it and leave only geyser in the plugin folder, i can login to the server.

Steps:
1. make a new server and velocity
2. put geyser and floodgate into velocity folder
3. login to the server via velocity
4. timed out occurs

Jars:
velocity-3.3.0-SNAPSHOT-390
geyser velocity [5ebb6ef](https://github.com/GeyserMC/geyser/commit/5ebb6ef0d66ca5871c8c42adb245a2a3f48113d2)
geyser floodgate [00b8b1b](https://github.com/GeyserMC/floodgate/commit/00b8b1b6364116ff4bc9b00e2015ce35bae8abb1)
folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf (commit ec6b172)

No errors on server or velocity.

**Comment by Camotoy** [comment]
Can you try the Floodgate build here? https://github.com/GeyserMC/Floodgate/actions/runs/9082242411/artifacts/1501736048
Thanks!

**Comment by Tim203** [comment]
Should be fixed in the latest version. It'll be available for download in a few minutes.
