### ISSUE TITLE
Working with uuid and xuid

### ISSUE THREAD

**Issue by veetack1** [GeyserMC/Floodgate#515]
As strange as it may sound, give people the ability to work with uuid and xuid and the ability to disable them. I’m not eager to go through 5k+ accounts with my hands for the sake of privileges. After all, after installing floodgate, all accounts are as clean as a baby’s bottom. After such jokes, I’m not at all eager to work with floodgate. There is no point in putting together such a summary on LuckPerms, everything is already displayed there - so as not to work with uuid but only with nicknames.

**Comment by OurLobanov** [comment]
Make it possible to log in without xuid but by nickname

**Comment by Kas-tle** [comment]
What you are asking does not really make sense. The whole point of Floodgate is to authenticate Bedrock accounts on the Java server. Therefore, all bedrock players must be assigned a UUID based on their XUID.

**Comment by veetack1** [comment]
ok, I'm waiting for an idea to implement the transfer of privileges. How should I transfer 5k+ accounts to floodgate?

**Comment by Kas-tle** [comment]
I do not understand the question. All Bedrock accounts will work with Floodgate provided they are a legitimate Microsoft account.

**Comment by veetack1** [comment]
I'm logged in through Microsoft, nothing works as you say)

**Comment by OurLobanov** [comment]
when you install floodgate creates new uuid of players and you get 2 players with the same nicknames, you need the opportunity not to change the uuid from floodgate for the java server, he previously assigned his

**Comment by veetack1** [comment]
With floodgate, the account is reset to zero, due to the fact that the account has not changed in terms of authorization.

**Comment by Kas-tle** [comment]
If you are referring to the Java server being in offline mode, that is not supported as doing so encourages software piracy. You are on your own with regards to getting such a setup working.

**Comment by veetack1** [comment]
Here, OurLobanov described the problem, the original account, which was without floodgate, cannot be deleted in any way) as a result, two different copy accounts are created in terms of nicknames. But one is basic, the second is empty.

**Comment by veetack1** [comment]
no
this not offline mode

**Comment by Kas-tle** [comment]
If you do not want a different UUID for users with both a Bedrock and Java account, use either global linking or host your own local linking database.

**Comment by veetack1** [comment]
watch

**Comment by veetack1** [comment]
There is a geyser server, there was no floodgate on it, we ran around, installed a floodgate, now there is a total of x2 on accounts. One has things on it, because we played there before. There is nothing on the other one (with floodgate). What can you do in this case without deleting the first version of your account? Is it possible to merge the floodgate with the first account, simply speaking from my story?

**Comment by Kas-tle** [comment]
Merging player data is outside the scope of Floodgate. Floodgate does not control the data associated with any account. It only controls what account the user is authenticated is. The player data for both accounts still exists on your server.

**Comment by veetack1** [comment]
That is, only the demolition of the first version of the account, right?

**Comment by Kas-tle** [comment]
When a Bedrock and Java account are linked, the player will always be logged in as the Java account. When not linked, the player will always be logged in as the Bedrock account.

**Comment by veetack1** [comment]
So there is no way for me to establish a connection with a Java account through floodgate?

**Comment by Kas-tle** [comment]
Linking the accounts will cause the Bedrock player to always login as there Java account. If a player has made progress on their Bedrock account before linking, Floodgate cannot help with migrating the data.

**Comment by veetack1** [comment]
Understood thanks
