### ISSUE TITLE
Bedrock player sees themselves as Steve

### ISSUE THREAD

**Issue by rororororo5** [GeyserMC/Floodgate#519]
### Describe the bug

The Bedrock player changes his skin, but still shows himself as Steve.
Other players can see the skin he has set up, but he continues to show himself as Steve only on his own screen. No matter how many times I log in again, it does not fix the problem. All Bedrock players have this symptom. Oh. The cause is unknown.
I get the symptoms whether I use the geyserskin manager or not.

### To Reproduce

Start with geysermc-spigot in papermc.
Log in with bedrock.

### Expected behaviour

When you log in, the skin you have set up yourself will be displayed securely on your own screen.

### Server Version and Plugins

This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
You are running the latest version
Previous version: git-Paper-493 (MC: 1.20.4)

### Geyser Dump

https://dump.geysermc.org/rxlxpDynWK5xDyIzDs7mh5krd47cTiKO

### Geyser Version

2.3.1-SNAPSHOT git-master-a780eea

### Minecraft: Bedrock Edition Device/Version

1.20.81 Windows11/iOS/Nintendo Switch

**Comment by Clyde-Timonera** [comment]
Any fixes? My bedrock players including me have been ranting about it

**Comment by SpringPea** [comment]
I also got the same issue wher3 my skin shows as steve on a java bedrock crossplay server,  idk is it on the server's side cos I asked the developer he say he can't do anything about it

**Comment by Clyde-Timonera** [comment]
Even if you show up as steve on the server it should show you as your skin on the client side, I hope this gets fixed soon

**Comment by SpringPea** [comment]
Other players say they can see the skin I'm using, I also see theirs

**Comment by Clyde-Timonera** [comment]
Yes same, after a while some steve people turn into their skin but they claim that on their client "I'm still steve wdym?", this means the server IS setting and uploading the skin but does not update what the player sees on their client.

**Comment by Camotoy** [comment]
The issue regarding Bedrock players seeing themselves as Steve has now been resolved - please update to the latest Geyser build. Let us know if an issue still persists!

**Comment by SpringPea** [comment]
Lessgo

**Comment by iam-best** [comment]
Same issue actually, please fix this!!!

**Comment by gilsoncav** [comment]
My client is setted with a skin...
![Image](https://github.com/user-attachments/assets/4b1a49ff-2c52-4471-8184-0d2089a12a35)
But the in-game rendering of the character is showing another. Is it the same issue ? 

![Image](https://github.com/user-attachments/assets/064ae963-f61b-4c1b-96b3-09996d6e358e)

**Comment by iam-best** [comment]
It's already fixed, update your Geyser!

**Comment by gilsoncav** [comment]
I'm with all the stack updated: Paper (1.21.4-144) + Geyser (2.6.0-b756) + Floodgate (2.2.3 b114)

**Comment by iam-best** [comment]
Try using a different Skin to see if it's the same result.

**Comment by gilsoncav** [comment]
I changed to a new skin:
![Image](https://github.com/user-attachments/assets/fd96d041-743b-4bb9-9700-1a2fda6b0f0f)

![Image](https://github.com/user-attachments/assets/b5b781b4-6e44-4c7f-813c-c33e3487b9a7)
But it keeps rendering a complete different one: 
![Image](https://github.com/user-attachments/assets/582c73bd-375f-464a-8027-9fc030a08405)

The client screenshot was taken in a Bedrock PC edition but I also tested using the PS5 edition and the issue is the same. 😢

**Comment by iam-best** [comment]
Not sure if that makes a difference but if you don't have floodgate install it and Skin Restorer!

**Comment by gilsoncav** [comment]
I do have floodgate installed (latest version). 
Does the prepending of a `.` in the player name could have something to do with the issue?

**Comment by gilsoncav** [comment]
Installed the SkinRestorer now (latest version) and no luck.

**Comment by iam-best** [comment]
It has nothing do to with the "."! I don't know why it doesn't work, sorry! :/ You should ask them in the Discord!

**Comment by Modder556** [comment]
> I do have floodgate installed (latest version). Does the prepending of a `.` in the player name could have something to do with the issue?

That is just a way of differentiating the bedrock from java players
