### ISSUE TITLE
Player Gets Kicked Upon Opening Inventory

### ISSUE THREAD

**Issue by lrj1818** [GeyserMC/Floodgate#523]
Yeah mostly happens when in creative survival is 50%

**Comment by Chew** [comment]
This is very likely an issue with Geyser and not floodgate. Please fill out an issue [on the Geyser repo](https://github.com/GeyserMC/Geyser/issues/new?assignees=&labels=&projects=&template=bug_report.yml) or [join our Discord server](https://discord.gg/geysermc). Be sure to have some logs ready!
