### ISSUE TITLE
link command not found in backend server

### ISSUE THREAD

**Issue by ColdeZhang** [GeyserMC/Floodgate#524]
I installed geyser and floodgate in velocity proxy, then followed instruction to download database.jar and put it into `plugins/floodgate` toggled `enable-own-linking` true.

But I still can not use `/linkaccount` in backend server.

![image](https://github.com/GeyserMC/Floodgate/assets/29792376/8abd8d06-3fa9-4c72-8d9c-ebb4ea57b6f4)

![image](https://github.com/GeyserMC/Floodgate/assets/29792376/2c4e8fd9-79b1-46a1-9adf-e35b6ae22837)

**Comment by Tim203** [comment]
Do you have the permission to execute that command?

**Comment by ColdeZhang** [comment]
> Do you have the permission to execute that command?

I think "yes", if I added the right perm node `floodgate.command.linkaccount `.

![image](https://github.com/GeyserMC/Floodgate/assets/29792376/4bc1b7aa-3f00-4fa2-b01a-2c2190277bac)

**Comment by ColdeZhang** [comment]
I think I know the problem. If install floodgate on vc, then should install lp on vc and add perms too.
