### ISSUE TITLE
Add a new linkaccount command to let OP directly link 2 accounts

### ISSUE THREAD

**Issue by yqs112358** [GeyserMC/Floodgate#526]
The current `/linkaccount` command requires players to perform the link operation by themselves. However, for servers with a large number of people, it takes a lot of effort to guide players through the linking process. 

It will be great if there will be another high-privilege link command, which can allow OP to specify a pair of online JE-BE account names to link directly. This can reduce a lot of unnecessary trouble.

**Comment by Tim203** [comment]
Duplicate of #41
