### ISSUE TITLE
Where can I get the version with 1.16 support?

### ISSUE THREAD

**Issue by moomcakesleep** [GeyserMC/Floodgate#527]

**Comment by onebeastchris** [comment]
The floodgate-spigot version found on our downloads page - https://geysermc.org/download#floodgate - supports 1.16.

**Comment by moomcakesleep** [comment]
I forgot one thing, my server is fabric side,im sorry

**Comment by moomcakesleep** [comment]
> The floodgate-spigot version found on our downloads page - https://geysermc.org/download#floodgate - supports 1.16 too.

> The floodgate-spigot version found on our downloads page - https://geysermc.org/download#floodgate - supports 1.16 too.



> The floodgate-spigot version found on our downloads page - https://geysermc.org/download#floodgate - supports 1.16 too.
I forgot one thing, my server is fabric side,im sorry

> The floodgate-spigot version found on our downloads page - https://geysermc.org/download#floodgate - supports 1.16 too.

I forgot one thing, my server is fabric side,im sorry

**Comment by moomcakesleep** [comment]
> The floodgate-spigot version found on our downloads page - https://geysermc.org/download#floodgate - supports 1.16 too.

I forgot one thing, my server is fabric side,im sorry

**Comment by onebeastchris** [comment]
Fabric 1.16 isn't supported, we don't have a Floodgate-Fabric build for it.

**Comment by moomcakesleep** [comment]
> Fabric 1.16 isn't supported, we don't have a Floodgate-Fabric build for it.

Okay,I knew it,thank you!

**Comment by moomcakesleep** [comment]
> Fabric 1.16 isn't supported, we don't have a Floodgate-Fabric build for it.

Okay,I knew it,thank you!

**Comment by moomcakesleep** [comment]
> Fabric 1.16 isn't supported, we don't have a Floodgate-Fabric build for it.

I turned my server into spigot side.Haha
