### ISSUE TITLE
Incompatibility with JPremium

### ISSUE THREAD

**Issue by partridge420x** [GeyserMC/Floodgate#53]
**Describe the bug**
Incompatibility with JPremium. Jpremium i believe is trying to authenticate bedrock users through its verification system

**To Reproduce**
Setup Jpremium
Setup geyser-mc
Get bedrock player to join
Error: Connection failed: Invalid session. With a stacktrace error

**Expected behavior**
Bedrock player able to join without issue

**Screenshots / Videos**
https://gist.github.com/partridge420x/52814ca3a548f9fe2eb049ab835d8f56

**Server Version**
waterfall build GeyserMC/Geyser#366
**Geyser Version**
This server is running Geyser version 1.0.0 (git-master-7fc14d8) (Java: 1.16.1, Bedrock: 1.16.0)
Using floodgate

**Minecraft: Bedrock Edition Version**
Affects all versions

**Additional Context**
https://dump.geysermc.org/knMgfrz0doGrIJcsbwpzydWtwOn7TICc

**Comment by rtm516** [comment]
This is a known issue and slightly more information here https://github.com/GeyserMC/Geyser/wiki/FAQ#what-plugins-dont-work-with-geyser

**Comment by Tim203** [comment]
I would recommend asking the plugin creator to add support for Floodgate since the plugin is closed source.

**Comment by partridge420x** [comment]
@Tim203 The developer has given me a snippet of code and said i can use this to fix the issue. But i have no idea where to put it and would be much better in your hands

https://gist.github.com/partridge420x/6c3d0602900661a57809a8467163a3bd

**Comment by Tim203** [comment]
I can't compile that for you since I'm on vacation, but you have to make a plugin and register that class as a listener. Maybe that someone else here or the plugin developer can make it into a plugin for you.

**Comment by partridge420x** [comment]
i just tried taking a whack at compiling the plugin from the lines of code. got Absolutely nowhere with it. I would need some external help with this one

**Comment by DoctorMacc** [comment]
@partridge420x please give the developer our sincerest thanks and let him know we will incorporate this in our rewrite.

**Comment by partridge420x** [comment]
@DoctorMacc  I could link him to here. or ask for a full list of his api calls at least

**Comment by DoctorMacc** [comment]
We've got it from here.

**Comment by partridge420x** [comment]
Bedrock players unable to join: Invalid Session. Spits console errors. This is different because before bedrock players could still join. Now they cant at all with nothing changing

https://gist.github.com/partridge420x/d4560f3e8099c3ae85ec6090a89015a9

**Comment by Tim203** [comment]
Fixed in an upcoming version of JPremium and will be released somewhere this week.
