### ISSUE TITLE
Players logged in as floodgate do not seem to check the whitelist

### ISSUE THREAD

**Issue by kulipaa** [GeyserMC/Floodgate#531]
Hey, today when I was configuring the whitelist, I found that Bedrock users who were not on the whitelist could still join the server unimpeded. 

The wiki only found how to add players to the whitelist

I would like to ask if Bedrock players logging in using the Floodgate plugin will bypass the whitelist check.
 Thanks🙂

**Comment by Camotoy** [comment]
Please send a Geyser dump - this should not happen.

**Comment by kulipaa** [comment]
[Geyser-Spigot.zip](https://github.com/user-attachments/files/16459440/Geyser-Spigot.zip)

**Comment by Camotoy** [comment]
Thank you for sending that, but this is what we're looking for:

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by kulipaa** [comment]
sorry
https://dump.geysermc.org/95Mabn1GVjSrI3yewT7LwZEyYB5Abmmr

**Comment by kulipaa** [comment]
Before I added the player to the whitelist (using / whitelist add), which was later cancelled, Turns out he still has access to the server

**Comment by Camotoy** [comment]
Is he present in the whitelist.json file?

**Comment by kulipaa** [comment]
He is no longer on the whitelist

**Comment by Camotoy** [comment]
Was that player given operator status?

**Comment by kulipaa** [comment]
no

**Comment by Camotoy** [comment]
Does this issue persist if you switch to Paper?

**Comment by kulipaa** [comment]
I'll try again in the morning, thanks

**Comment by kulipaa** [comment]
Sorry for the trouble, I only turned on enforce_whitelist, not white_list.
