### ISSUE TITLE
Can not get final com.velocitypowered.proxy.connection.client.InitialInboundConnection field

### ISSUE THREAD

**Issue by timr2000** [GeyserMC/Floodgate#538]
Velocity: 3.3.0-SNAPSHOT (git-00ed2284-b415)
Floodgate: 2.2.3-SNAPSHOT (b109-49bd564)
Geyser: 2.4.2-b658 (git-master-8356b63)

When a user joins the server it spits out this error: https://mclo.gs/o2rDTHl

**Comment by Tim203** [comment]
I'm a little bit confused because the logic has not been touched (in both Velocity and Floodgate) for years now.
I'm suspecting that this is caused by another plugin. While it's technically valid PreLoginEvent should only be called by Velocity and not by other plugins.
