### ISSUE TITLE
Auto whitelist

### ISSUE THREAD

**Issue by tawan475** [GeyserMC/Floodgate#55]
**What feature do you want?**
Automatically re-whitelist everyone in the whitelist with "*" in it

**Alternatives?**
Allow bedrock players to bypass whitelist (will do but not good alternative)

**Comment by Tim203** [comment]
I'm not sure if I'll add an option to whitelist everyone that is using Floodgate, but there will be a command to add Floodgate people easier (see #39)

**Comment by chelminski** [comment]
You can set firewall for your server and accept only 19132, or if u have bungee u can allow only 172.15.. (bedrock proxy - ONLY IF U DON'T USE FLOODGATE).
