### ISSUE TITLE
Floodgate is preventing bedrock players from joining for my server

### ISSUE THREAD

**Issue by tmeuschel** [GeyserMC/Floodgate#552]
I host a papermc server which is on 1.21.1 (papermc hasn't updated from my info), I use velocity (to mask my local servers ip address), and I use floodgate to allow bedrock players to join

Geyser mc is updated to the latest version 1.21.4, but the problem is since bedrock players run a more modern version of minecraft compared to my paper mc server. Though I know this can be resolved using plugins like via version and the like (and also said prior Geyser is updated as well).

I just need floodgate to be updated or some way to allow bedrock players to join my papermc server.

**Comment by Tim203** [comment]
Geyser is actually the one responsible for supporting the latest Bedrock version, which it does. Make sure Geyser is updated.
