### ISSUE TITLE
How do version restrictions work?

### ISSUE THREAD

**Issue by KevinCCucumber** [GeyserMC/Floodgate#553]
I think I confused myself with my setup, so please help:
A friend has a nintendo switch which needed to be updated to the latest bedrock version (in this case the new bundle content update)
Is there a way he can join my server when I am still running 1.21.1 or do minecraft content updates disable the possibility of playing together temporarily?

**Comment by Camotoy** [comment]
Geyser supports 1.21.1 Java currently, regardless of the Bedrock version joining.

Once Geyser supports Java 1.21.3, you'll just need to install ViaVersion.
