### ISSUE TITLE
Download link on README.md 404s

### ISSUE THREAD

**Issue by some1chan** [GeyserMC/Floodgate#558]
Found this while Modrinth was down. Would be useful to have the master branch job shown to the public again in cases like these.

![image](https://github.com/user-attachments/assets/db0368dc-ca31-4490-989f-14825290f470)

**Comment by Kas-tle** [comment]
Thank you. I have updated it to link to our website which has builds for all platforms (https://geysermc.org/download/?project=floodgate)
