### ISSUE TITLE
Username suffixes

### ISSUE THREAD

**Issue by TOWUK** [GeyserMC/Floodgate#56]
**What feature do you want?**
Just add suffixes in config :з
![image](https://user-images.githubusercontent.com/28830162/89931643-21efa980-dc15-11ea-833e-15d90c239e27.png)
![image](https://user-images.githubusercontent.com/28830162/89931674-30d65c00-dc15-11ea-9b53-ec4b1832e9ae.png)

**Alternatives?**
plugins spigot (TAB, nametagEdit)

**Comment by Tim203** [comment]
See the comment on #60
