### ISSUE TITLE
Add jitpack to the Floodgate API

### ISSUE THREAD

**Issue by NikV2** [GeyserMC/Floodgate#62]
Hello! I am a plugin developer and i plan to be using the Floodgate API very soon.

I was just wondering if it could be possible for you to add the jitpack function to this api so we can directly get the latest Jar from Maven/Gradle in our pom.xml.
I believe this would make it much easier for everyone!

For further information on how to do that here's the jitpack website:
https://jitpack.io/

Thanks in advance!

**Comment by rtm516** [comment]
It is already on the nukkitx repo, see https://github.com/rtm516/FloodgatePlaceholders/blob/master/pom.xml for an example of it being in use.

**Comment by Tim203** [comment]
And please notice that Floodgate is having rewrite, and it has breaking changes.

**Comment by NikV2** [comment]
I see, i'm an idiot for not seeing that Thank you!
