### ISSUE TITLE
Fabric mods version?

### ISSUE THREAD

**Issue by BuyMyMojo** [GeyserMC/Floodgate#63]
I am leaving a comment

**Comment by Tim203** [comment]
Your current question (without any description) can mean multiple things, please clarify.

**Comment by BuyMyMojo** [comment]
Fair enough, I'm asking if there will be a version that can be installed on a fabric server

**Comment by QPCrummer** [comment]
I wish there was. That would be the best thing ever!

**Comment by DoctorMacc** [comment]
Closing this in favor of the clearer #71.
