### ISSUE TITLE
Admin level account information

### ISSUE THREAD

**Issue by NyaomiDEV** [GeyserMC/Floodgate#64]
It would be great to have some admin commands to check if players are Floodgate players.

Ideally it should behave like so:
- If a player is a legit Java player with nothing to do with Floodgate, a notice is displayed.
- If a player is a legit Java player, but has Floodgate account(s) linked to it, then display its linked Xbox gamertag(s) and XUID(s).
If the player is currently playing via Bedrock, an additional notice is displayed stating the current Xbox gamertag being used.
- If a player is only playing via Bedrock only, a notice is displayed (with gamertag and XUID).

**Comment by TOWUK** [comment]
maybe just add placeholder %geyser_edition%/%floodgate_edition%/%geyser_auth_type% and more?

**Comment by rtm516** [comment]
@TOWUK some of those placeholders are available as part of https://github.com/rtm516/FloodgatePlaceholders/ and these will not be implemented into floodgate

**Comment by AryToNeX** [comment]
@TOWUK PlaceholderAPI is not a substitute for admin commands.

**Comment by Tim203** [comment]
That's why I gave it the `enhancement` label

**Comment by TOWUK** [comment]
> @TOWUK some of those placeholders are available as part of https://github.com/rtm516/FloodgatePlaceholders/ and these will not be implemented into floodgate

😍😍😍

**Comment by TOWUK** [comment]
> @TOWUK some of those placeholders are available as part of https://github.com/rtm516/FloodgatePlaceholders/ and these will not be implemented into floodgate

how install it? its plugin bukkit?
