### ISSUE TITLE
Simplify the linking procedure

### ISSUE THREAD

**Issue by AryToNeX** [GeyserMC/Floodgate#65]
As it is now, specifying a gamertag on the `/linkaccount` command seems unnecessary (you're already generating a PIN).

I guess the linking procedure could be simplified like so:
- Simplify the `/linkaccount` command usage to `/linkaccount [PIN]`.
- If a Floodgate user uses the command without a PIN, a notice would tell them to specify a PIN.
If a Java user uses the command without a PIN, then all of the previous generated PINs are discarded (if any) and a new, unique PIN is generated and sent over to the user.
- If a Floodgate user uses the command with a PIN, if the PIN is valid, link to the Java account which generated it.
If a Java user uses the command with a PIN, display an error (they're not in a Floodgate session).

**Comment by Tim203** [comment]
The current system is more secure and for the end user it is only a few seconds more work.

**Comment by AryToNeX** [comment]
I really can't get why it is more secure like this, can you please tell me?
By the way, it's totally fine. I hope I didn't bother you that much with this suggestion.

**Comment by Tim203** [comment]
Because now you have to enter an username.
Guessing a 5 number code is hard for humans, but really not impossible.
Guessing both an username, a 5 number code and in 5 minutes is nearly impossible.

**Comment by AryToNeX** [comment]
Thanks for the clarification!
But I guess that the attacker has to be in the Floodgate session, so the mere fact that they have to take over the victim's xbox gamertag is already quite complex... so ultimately yes it's better to do it this way.
