### ISSUE TITLE
Bedrock display username not updating

### ISSUE THREAD

**Issue by chuushi** [GeyserMC/Floodgate#67]
Hello, I'm having an issue with the Bedrock username not syncing up properly with the server. My current setup is GeyserMC and Floodgate on a Waterfall server, and I do not have Floodgate installed on individual Paper servers.

When the Minecraft Bedrock username is changed either via changing Microsoft Gamertag or by changing the prefix configuraiton, the username is updated on the Waterfall server and partially on the Paper server, but the Paper server doesn't display the new name. I tried clearing user data in the Paper server by deleting playerdata for the bedrock player, but the game still displays the old name in the chat, over their head, and for the tab-completion.

The symptoms only exist for bedrock players who joined the game before either they changed their gamertag, or the prefix configuration was modified. The following does not reflect the new username:

* Name displayed over the character
* Name used in chat (and other game messages, e.g. death messages)
* Name shown in tab complete suggestion

This inconsistency causes issues when running commands with some other plugins, such as LuckPerms and LiteBans. These plugins rely on using the updated username, but the tab complete and the failure to know the name changed will make the user rather unmentionable.

This issue does not exist on Paper servers the player hasn't joined before their username was changed.

**Comment by DoctorMacc** [comment]
Can you try deleting  the `usercache.json` file that exists at the root of your server?

**Comment by chuushi** [comment]
Hi, sorry about the long delay, but deleting the line containing the bedrock player information in `usercache.json` file fixed the problem. Furthermore, editing the `.json` file and changing the username manually made the server use that name on restart.

**Comment by Tim203** [comment]
This is a Paper bug and will be fixed once https://github.com/PaperMC/Paper/pull/4970 has been merged
