### ISSUE TITLE
Error message when connecting to server

### ISSUE THREAD

**Issue by QPCrummer** [GeyserMC/Floodgate#68]
java.io.IOException: Broken pipe

**Comment by DoctorMacc** [comment]
Please provide the full error, server version, and Geyser dump if applicable. This does not help us at all.

**Comment by QPCrummer** [comment]
Full error:
07.09 14:44:13 [Server] Network Listener - #1/INFO /24.210.112.115:57658 tried to connect!
07.09 14:44:13 [Server] Network Listener - #1/WARN Loaded class org.geysermc.common.window.FormWindow from floodgate-bukkit v1.0-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.
07.09 14:44:13 [Server] Network Listener - #1/INFO Player connected with username qpcrummer1133
07.09 14:44:18 [Server] Network Listener - #1/INFO Attempting to login using floodgate mode... authentication will be encrypted.
07.09 14:44:18 [Server] Thread-10/INFO Loaded Floodgate key!
07.09 14:44:19 [Server] nioEventLoopGroup-2-2/INFO qpcrummer1133 (logged in as: qpcrummer1133) has connected to remote java server on address 147.135.31.38
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R2.LoginListener.initUUID()
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at java.lang.Class.getMethod(Class.java:1786)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at org.geysermc.floodgate.util.ReflectionUtil.getMethod(ReflectionUtil.java:129)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at org.geysermc.floodgate.PacketHandler.<clinit>(PacketHandler.java:161)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at org.geysermc.floodgate.injector.BukkitInjector$2$1.initChannel(BukkitInjector.java:72)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:637)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.DefaultChannelPipeline$3.run(DefaultChannelPipeline.java:229)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at java.lang.Thread.run(Thread.java:748)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R2.LoginListener$LoginHandler
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at java.lang.Class.forName0(Native Method)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at java.lang.Class.forName(Class.java:264)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at org.geysermc.floodgate.util.ReflectionUtil.getClass(ReflectionUtil.java:23)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at org.geysermc.floodgate.util.ReflectionUtil.getPrefixedClass(ReflectionUtil.java:18)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at org.geysermc.floodgate.PacketHandler.<clinit>(PacketHandler.java:180)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at org.geysermc.floodgate.injector.BukkitInjector$2$1.initChannel(BukkitInjector.java:72)
07.09 14:44:19 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)


Server Version: 1.16.2 CraftBukkit

Dump: https://dump.geysermc.org/9WR7M9LcCgBSZQtlYcfwabc8o5u74LUi

**Comment by RednedEpic** [comment]
Please use Paper (preferred) or Spigot. CraftBukkit is unsupported.

**Comment by QPCrummer** [comment]
It works with just geyser though

**Comment by RednedEpic** [comment]
Floodgate does not support CraftBukkit.

**Comment by QPCrummer** [comment]
Ok, I was just wanting something that was almost vanilla minecraft
