### ISSUE TITLE
Could you make a Fabric version of this plugin. It would be very useful!

### ISSUE THREAD

**Issue by QPCrummer** [GeyserMC/Floodgate#71]
Things that would be possible if this was made a fabric mod:
1. Using some useful mods that aren't available as plugins such as Gnembon's Carpet Mod
2. Better performance. Lithium + Phosphor = Omega Server Performance. Sadly Paper ruins a lot of mechanics. Fabric is Vanilla Minecraft with wrapping paper around it and a bow on top.
3. Even though more people do use Paper, they would much rather use a Vanilla server that doesn't break mechanics. The only reason they use Paper is because it "performs better". Lithium + Phosphor actually performs equally the same.
4. Who doesn't like modded Minecraft? I mean being able to play with your Bedrock Friends on modded Minecraft! That would be INSANE. I do know that only server side mods are compatible, but there are still really good server side mods!
5. I have been using Geyser for more than 4 months. I like how fast you guys update bugs and add new content. I feel like this idea would take a decent amount of time. 

Alternative: I use this fabric mod called Bukkit4Fabric( https://www.curseforge.com/minecraft/mc-mods/bukkit ). If you could some how make it compatible with this version of bukkit/spigot, that would probably be easier. Of course you could tell me that this will never happen. Would I be upset, 100%. Would I see why you said so, 100%. I feel like you were going to do this anyways, but I just wanted to spark the idea some more. I have committed the other issue post about this, but I feel like they didn't give enough evidence to support their idea. I hope I gave enough. If you do, this is definitely becoming my favorite plugin!

**Comment by npgoalkeeper** [comment]
[Geyser itself isn't even implemented in fabric yet ](https://github.com/GeyserMC/Geyser/issues/271)

**Comment by DoctorMacc** [comment]
We have interest in making Fabric implementations.

**Comment by Titaniumtown** [comment]
It would be amazing to have floodgate have a fabric port! I hope someone creates one.

**Comment by DoctorMacc** [comment]
For context: Geyser has been ported to Fabric, so this will be something we look into as the rewrite nears completion.

**Comment by Camotoy** [comment]
There is a Fabric version of Floodgate available at https://github.com/GeyserMC/Floodgate-Fabric. Unless someone else closes this, I will keep this open until we determine that it is ready for use at the same level of production that normal Floodgate is.

**Comment by Mhowser** [comment]
@Camotoy  the wiki for geyser-fabric says that Floodgate is not supported on fabric https://github.com/GeyserMC/Geyser/wiki/Geyser-Fabric , is this still true or does the wiki need to be updated?

**Comment by Camotoy** [comment]
The lack of a wiki update is intentional, as the Floodgate-Fabric build we currently have is not ready for publicity.

**Comment by Mhowser** [comment]
I see, do you think the wiki could mention this unstable build in that section? something like "Floodgate is available for Fabric, however it is unstable and not intended for production yet."
