### ISSUE TITLE
"Error while reading Floodgate key file"

### ISSUE THREAD

**Issue by NigelL12** [GeyserMC/Floodgate#73]
I was trying to join my server using floodgate and it says this: https://gist.github.com/NigelL12/6189978764302372f97ff62d77fb038d

How do I fix it?

**Comment by DoctorMacc** [comment]
PloudOS is listed as unsupported on our supporting hosting providers page which may be part of the problem.

**Comment by Tim203** [comment]
It cannot find the key.
If your issue isn't solved yet in our Discord, feel free to ask it.
However I don't think that this is an issue of Floodgate itself.
