### ISSUE TITLE
Downstream packet error! Invalid packet id: 25 & more

### ISSUE THREAD

**Issue by kotx** [GeyserMC/Floodgate#74]
**Describe the bug**

I am on Velocity 1.1.0-SNAPSHOT and Paper 228.
Geyser is installed on Velocity. Floodgate is installed on both Velocity and Paper.
This bug occurs when a Bedrock player attempts to connect to the Velocity proxy. The player connects without anything loaded for a split second, and then disconnects with "Connection closed." message. 

Here is a full log of the error on Paper: https://paste.mod.gg/sadecefuha.md. 

The Geyser plugin on Velocity spits this out:
```
[15:00:51 INFO] [geyser]: Attempting to login using floodgate mode... authentication will be encrypted.                                     
[15:00:51 INFO] [geyser]: Loaded Floodgate key!
[15:00:52 INFO] [geyser]: Kot9744 (logged in as: Kot9744) has connected to remote java server on address 127.0.0.1                          
[15:00:53 WARN] [geyser]: Downstream packet error! Invalid packet id: 25                                                                    
[15:00:53 INFO] [geyser]: Kot9744 has disconnected from remote Java server on address 127.0.0.1 because of Connection closed.               
[15:00:53 INFO] [geyser]: Bedrock user with ip: /MY-IP has disconnected for reason CLOSED_BY_REMOTE_PEER
```

**To Reproduce**

I have not tried to reproduce this bug, but it is fairly straightforward TMK.
1. Download Velocity
2. Download Paper
3. Install Geyser and Floodgate on Velocity.
4. Install Floodgate on Paper.
5. Configure both instances to use Floodgate. Copy the private keys to the floodgates, and the public key to Geyser.
6. Attempt to connect using a Bedrock client. 

**Expected behavior**

The user can connect to the server. 

**Server Version**

Velocity: `Velocity 1.1.0-SNAPSHOT (git-3b1009ca-b262)`
Paper: `This server is running Paper version git-Paper-228 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)`

**Geyser Version**

Geyser is on version 1.1.0. Floodgate is on 1.0-SNAPSHOT
I am using Floodgate-Velocity on Velocity, Floodgate-Bukkit on Paper.

**Minecraft: Bedrock Edition Version**

1.16.40 - I was told there are no protocol revisions between 1.16.2 and 1.16.40.

**Additional Context**

Here is the Geyser dump. https://dump.geysermc.org/Q6Td3MZ5dLqkxvnBul1fp7UKsvldT93U

**Comment by DoctorMacc** [comment]
Just tested with Paper 228, latest Velocity 1.1.0 (not the commit you have), and even with LuckPerms installed. With send-floodgate-data I was able to connect fine.

**Comment by DoctorMacc** [comment]
> and the public key to Geyser
Might be your issue? For Floodgate installations where Geyser is on the same server you don't need to do that.

**Comment by kotx** [comment]
> > and the public key to Geyser
> 
> Might be your issue? For Floodgate installations where Geyser is on the same server you don't need to do that.

No change. BTW, the paper server was online-mode, so I turned it off (velocity is already online-mode). I also installed SkinsRestorer. Shouldn't affect Floodgate.

**Comment by DoctorMacc** [comment]
SkinsRestorer 13.8.4 does interfere on BungeeCord.

Perhaps try deleting all your keys (and one config so Floodgate will regenerate the keys).

**Comment by kotx** [comment]
> SkinsRestorer 13.8.4 does interfere on BungeeCord.
> 
> Perhaps try deleting all your keys (and one config so Floodgate will regenerate the keys).

My bad for not clarifying, SkinsRestorer was installed on the Paper server (for now, until I need to use it). 

I deleted all of my keys. I deleted my Velocity Floodgate config and then copied the key from Velocity to Paper. I restarted both servers (Velocity with the correct config). 

Now the Bedrock client remains logged in for longer for some reason, but there is a lot of spam of `Please wait until you are logged in...` before it closes with `Connection closed.` The error in logs is the same.

**Comment by DoctorMacc** [comment]
Attach a new Geyser dump.

**Comment by kotx** [comment]
https://dump.geysermc.org/feDvQGlrUS7hIIq6EGo1rYcrFfQNqoiz

**Comment by DoctorMacc** [comment]
Set your `remote` `address` to `auto` and restart.

**Comment by kotx** [comment]
> Set your `remote` `address` to `auto` and restart.

Ah, that seems to have worked- could you explain why this happened? I'm very confused.

**Comment by DoctorMacc** [comment]
Not quite sure how you got 30066 as a port when your reported Velocity port is 25565, but I assume you tried changing things in an attempt to debug a situation that ultimately was corrupt Floodgate keys after all.

**Comment by Magi1053** [comment]
I can confirm that changing `remote address` from `127.0.0.1` to `auto` fixes _this_ issue for me

**Comment by kotx** [comment]
> Not quite sure how you got 30066 as a port when your reported Velocity port is 25565, but I assume you tried changing things in an attempt to debug a situation that ultimately was corrupt Floodgate keys after all.

Ah, port 30066 is my Paper server (not local, I forwarded it via frps). I didn't know it was supposed to be pointed to Velocity.

**Comment by Magi1053** [comment]
After restarting my server this morning I am back to the same error again. https://paste.mod.gg/ojeletatin.md
I also bypassed my proxy server and I am connecting directly to Geyser Spigot
https://dump.geysermc.org/Qu7in03JWUyQv8YKSJ5cVI9uIQielAvt

**Comment by Magi1053** [comment]
Ok I think I actually found out what the issue is, which would be setting `bungeecord: true` in the spigot.yml. I turned this setting to false, connected directly to my spigot server with floodgate and I had success.
When I re-enable the bungeecord and attempt to connect through Waterdog, I get this error even though I have floodgate-bungee installed on my proxy server.
