### ISSUE TITLE
Player cannot link their accounts

### ISSUE THREAD

**Issue by nessonic** [GeyserMC/Floodgate#75]
I have had her enter /linkaccount username on Java, then /linkaccount username #### on Bedrock. She gets an error that this needs to be initiated run a Java account, even though per console I saw her enter them. I've also tried sending commands via sudo. Tried with and without the asterisk prepend (still unsure which is correct)

This linking has worked for other players. I tested on my own via unlinking and then joining from Windows 10 Bedrock (her platform). One recent time she attempted, the error instead of the above was: you don't have permissions to run this command. So I've explicitly allowed floodgate.linkaccount & floodgate.unlinkaccount in LuckPerms for the default group.

The one oddity in my testing with her process & mine: She cannot be logged into both Java and Bedrock accounts simultaneously. I was able to while unlinked. She gets kicked on the other account upon logging in. Her username for both is the same, as is both my Java and Bedrock accounts.

**Comment by nessonic** [comment]
https://dump.geysermc.org/7IQ9dIlrBVwnOlHz2e5ErJaubQe1SQEJ

**Comment by Tim203** [comment]
Please try to find a way for us to be able to reproduce this, that will make it a lot easier for us.

**Comment by nessonic** [comment]
Apologies, I'm unsure how to provide that - had hoped there was some info the team could pass along to assist as issue was not able to be reproduced for any other user (including on my own test account).

**Comment by Tim203** [comment]
I'm also not sure what I can do about it. Maybe the log can help? And what is the path between the Bedrock client and the Java Server (e.g. Bedrock -> Geyser -> Geyser Spigot -> Spigot)?

**Comment by Tim203** [comment]
I'm going to close this issue since I haven't heard anyone else having this issue.

**Comment by Andarius68** [comment]
I appear to be having this exact same issue now.

**Comment by Andarius68** [comment]
https://dump.geysermc.org/MZpQ3dRTMvlaEFaz5awFWJcwrzs6uY2v
