### ISSUE TITLE
There has a "*" before player's name

### ISSUE THREAD

**Issue by mcdudu233** [GeyserMC/Floodgate#8]
There has a "*" before bedrock player's name.

**Comment by jackson-57** [comment]
This is intentional, to differentiate Java players from Bedrock players.

**Comment by mcdudu233** [comment]
But my server can't allow special characters.
So bedrock players can't connect the my server.

**Comment by Dummiesman** [comment]
This also prevented me from teleporting players from the command line in Spigot. Got "expected argument" and couldn't autocomplete the 2nd players name.

**Comment by jackson-57** [comment]
Use quotes at the ends of the player name @Dummiesman

**Comment by Tim203** [comment]
See #11 , the prefix is now configurable.
