### ISSUE TITLE
Floodgate does not work when using standalone, but works when running on the bungee or spigot

### ISSUE THREAD

**Issue by TheNextGamer21** [GeyserMC/Floodgate#83]
I will try to get logs later today, but when using floodgate with the standalone geyser server, things fail, but when running on bungeecord or spigot, floodgate works perfectly

On top of that, using ping passthrough with standalone causes bedrock players to not be able to join, but this goes away when running it on the bungeecord

**Comment by TheNextGamer21** [comment]
Do note I have chunk caching enabled as my windows server has 64 GB of ram

**Comment by rtm516** [comment]
Please double-check all your config and follow the Floodgate setup on the wiki. If configured properly Floodgate works fine with standalone. As for ping passthrough causing players to not join, likely is some strange permission issue or somehow caused by a bad floodgate config?

**Comment by TheNextGamer21** [comment]
Updating floodgate and regenerating the key fixes both ping passthrough and players not being able to join.
