### ISSUE TITLE
Floodgate API questions

### ISSUE THREAD

**Issue by TheNextGamer21** [GeyserMC/Floodgate#84]
Ok so, I originally thought I would use NukkitX as my server because it had built in support for vanilla bedrock combat, bedrock forms, and as I thought, had the ability to run spigot plugins using pokkit

So I got to work, I first focused on bedrock forms, I did it more than successfully using this:
https://cloudburstmc.org/resources/uiformapi.561/

I then decided to use Pokkit to run spigot plugins, but none of them worked

So here I am using geysermc again : (
I did notice however, that the code in the floodgate wiki is very similar to the code used in UIFormAPI: https://cloudburstmc.org/resources/uiformapi.561/

So would UIFormAPI's code work in on a spigot server with floodgate, or will it not?

**Comment by Tim203** [comment]
No, when you look at Cumulus you notice differences (click [here](https://github.com/GeyserMC/Cumulus/wiki)) e.g. the package name.
If you want to use the Forms API that Floodgate 2.0 uses you have to change things.
