### ISSUE TITLE
the ip arrives late for work

### ISSUE THREAD

**Issue by iSilviu-debug** [GeyserMC/Floodgate#85]
**Describe the bug**
When a person enters with Geyser, the IP is seen by the machine. If I use a connector or use the bungeecord directly, they receive the IP after actually entering the server with floodgate. Floodgate in fact converts the player afterwards and some plugins that use the prelogin and the login event, give problems because they take the local IP so 127.0.0.1 or IPMACHINE.

**To Reproduce**
1) Install a bungeecord with the geyser and floodgate plugin.
2) Go inside and look at the console.

**Expected behavior**
The ip must also reach the plugins and the PreLoginEvent

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/67197594/101644705-d1a71d80-3a35-11eb-915e-1a84acc5cf6c.png)

**Server Version**
[15:48:57 INFO]: This server is running Waterfall version git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:40370a3:388 by md_5

**Geyser Version**
[15:48:01 INFO]: Questo server usa Geyser versione 1.2.0-SNAPSHOT (git-master-2f294c9) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.56)
_I'm 3 versions back, but I don't see big fixes on this as it's floodgate._

**Floodgate Version**
Floodgate: 1.0 - ALPHA

**Minecraft: Bedrock Edition Version**
1.16.101

**Dump**
https://dump.geysermc.org/mKIGWjo2TUzcwFPQ9OOFSR66JUhZOjP8

**An idea**
I have seen the floodgate GITHUB code and noticed that the priority is on -32 instead of -64. Then, is the PreLoginEvent listener inserted? Could help?

**Additional Context**
🌵

**Comment by iSilviu-debug** [comment]
Any answer?

**Comment by DoctorMacc** [comment]
Be patient - someone will get around to this when they can.

**Comment by iSilviu-debug** [comment]
i found out how to fix it; in practice the main problem is `@EventHandler (priority = EventPriority.LOW) `and others with `@EventHandler (priority = EventPriority.HIGHEST)` to bring everything to `LOWEST`. Second problem is the` .getScheduler (). RunAsync (this, () ->`, which works fine when removed.

_One question, where can I find the source with the latest update? I need **always-force-offline-uuids**._

**Comment by Tim203** [comment]
Floodgate doesn't know such a thing as `always-force-offline-uuids`

**Comment by iSilviu-debug** [comment]
there are versions where he had it. Anyway I did and I'm going with the plugin that I modified, since we need to help everyone I recommend to remove runAsync when a player enters and put all events on LOWEST.

**Comment by Tim203** [comment]
runAsync is made for situations like this and we use LOW so that plugins can go before Floodgate if they want, but Floodgate will always be called before the default priority (NORMAL).

**Comment by iSilviu-debug** [comment]
> runAsync è fatto per situazioni come questa e usiamo LOW in modo che i plugin possano andare prima di Floodgate se lo desiderano, ma Floodgate sarà sempre chiamato prima della priorità predefinita (NORMAL).

for me it is useless because the plugins cannot take the IP and are not supported (eg AntiBot, playtime etc ..)

**Comment by Tim203** [comment]
This has been added to the todo list of the 2.0

**Comment by iSilviu-debug** [comment]
Fantastic !!!

**Comment by Tim203** [comment]
This should be fixed in Floodgate 2.0, but I haven't tested it with one of your mentioned plugins.
Please comment on this issue when it turns out not to be fixed.
