### ISSUE TITLE
Add support for ProtocolSupportBungee

### ISSUE THREAD

**Issue by Kapitowa** [GeyserMC/Floodgate#87]
This plugin works fine with waterfall, better then via version in many aspects. And it will be cool if you fix compatibility issue.

**Comment by candrawardana** [comment]
truly, we need,

i think this problem exist because of entity metadata rewrite

**Comment by Tim203** [comment]
ProtocolSupportBungee is not supported anymore by ProtocolSupport themselves.
Because of that, I'm closing this issue.
