### ISSUE TITLE
Let players link gamertags with spaces

### ISSUE THREAD

**Issue by wowpoppy** [GeyserMC/Floodgate#88]
Expected behavior:
`/linkaccount "my gamertag"` to work

Actual behavior:
`/linkaccount "my gamertag"` and `/linkaccount my gamertag` return usage example

No errors or warnings in the console, I suppose Floodgate takes it as a syntax error.

**Comment by rtm516** [comment]
You need to type the Gamertag exactly as it appears in-game and make sure account linking is enabled in the config.

**Comment by wowpoppy** [comment]
I see. Thank you! `/linkaccount *my_gamertag` worked like a charm!
