### ISSUE TITLE
Java clients (1.15.2) cannot connect

### ISSUE THREAD

**Issue by brettp** [GeyserMC/Floodgate#9]
Using the latest master as of today and Bukkit 1.15.2, built with both OpenJDK 11 and Oracle JDK 13, I am unable to connect to the server with a java client (1.15.2). I receive this message in the client: 
![image](https://user-images.githubusercontent.com/43375/76169793-1ffb5900-6152-11ea-96f2-46a4ef7c1262.png)

> Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index: 27, Size: 5

Here is the debug log from the server: https://gist.github.com/brettp/4d0d49b82954ef1f46e57f1f927b6c30

I am using the standalone version of Geyser, and Floodgate is the only plugin. Bedrock clients can connect.

**Comment by CamJW101** [comment]
Can confirm this issue on my fresh release as well.

**Comment by Tim203** [comment]
Yeah, several people reported this issue.
Thanks for making it an Github issue.

**Comment by Heath123** [comment]
This commit broke it: https://github.com/GeyserMC/Floodgate/commit/7edff139cc10364a3f106fd1dd7677cdfd2ea42c
Last working version: https://github.com/GeyserMC/Floodgate/tree/580ae0dcf063667e6802b5fe1e650010df5b9822
Zipped source of last working version: https://github.com/GeyserMC/Floodgate/archive/580ae0dcf063667e6802b5fe1e650010df5b9822.zip

**Comment by brettp** [comment]
Wow thanks for the fast response! I rebuilt Floodgate against the latest master.

Good news: Java clients can connect again!

Bad news: Android and Win 10 clients connect, but then crash after a couple seconds. There is no relevant info in the server logs, though the client does eventually time out. The Android debug logs are empty, and I have no idea how to find logs for the Windows 10 version.

**Comment by Tim203** [comment]
Sorry for the late reaction, but the commit what changed the xuid to the identifier is reverted until we find a way to solve it. So Bedrock players should be able to connect too.
