### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Kapitowa** [GeyserMC/Floodgate#92]
It happens when floodgate-bukkit installed, when player connect to the server on version 1.12.2 throw viabackwards.
Without floodgate-bukkit all works fine, floodgate on bungeecord don't do this problem. Server works in offline mode.
https://hastebin.com/eliwuracac.yaml

**Comment by Camotoy** [comment]
Floodgate is not mentioned once in these logs.

**Comment by Kapitowa** [comment]
I know, but it happens when floodgate-bukkit is installed. I think this problem happens due to uuid change from floodgate.
