### ISSUE TITLE
ProtocolSupport Connection closed.

### ISSUE THREAD

**Issue by masterhacka** [GeyserMC/Floodgate#93]
Describe the bug
When connecting with MCPE iOS, the user returns the error: Connection closed.
Error in console: lost connection: Internal Exception: java.lang.NoSuchMethodError: protocolsupport.protocol.ConnectionImpl.getLoginProfile()Lprotocolsupport/protocol/utils/authlib/LoginProfile;
Only while using Floodgate + ProtocolSupport plugin. Without Floodgate it works fine.

To Reproduce
Install Geyser-Spigot, Floodgate-Bukkit and ProtocolSupport on a PaperMC server in /plugins/. Configure Geyser to use Floodgate.

Server Version
git-Paper-1618 (MC: 1.12.2)

Geyser Version
1.2.0-SNAPSHOT

Floodgate Version
1.0-SNAPSHOT

ProtocolSupport Version
4.29-dev

Minecraft: Bedrock Edition Version
v1.16.201

**Comment by rtm516** [comment]
This looks like its caused by ProtocolSupport and nothing todo with Floodgate, but the fact that it doesn't appear without Floodgate is odd. Can you provide logs and a Geyser dump? Also, try updating Floodgate.

**Comment by masterhacka** [comment]
I am using newest version of Floodgate.

Log: `> [K[22:27:49 INFO]: [Geyser-Spigot] /XX.XXX.XXX.XXX:61256 versuchte zu verbinden!
> [K[22:27:50 INFO]: [Geyser-Spigot] Spieler OrnateBike8401 verbunden
> [K[22:27:54 INFO]: [Geyser-Spigot] Versuche im Floodgate Modus zu verbinden... Anmeldung wird verschlüsselt.
> [K[22:27:54 INFO]: [Geyser-Spigot] Floodgate Schlüssel geladen!
> [K[22:27:55 INFO]: [Geyser-Spigot] OrnateBike8401 (eingeloggt als: OrnateBike8401) ist jetzt mit dem Java Server unter der Adresse 95.156.227.148 verbunden
> [K[22:27:55 INFO]: [floodgate-bukkit] Added *OrnateBike8401 00000000-0000-0000-0009-01fc589d88c5
> [K[22:27:55 INFO]: /XX.XXX.XXX.XXX:38826 lost connection: Internal Exception: java.lang.NoSuchMethodError: protocolsupport.protocol.ConnectionImpl.getLoginProfile()Lprotocolsupport/protocol/utils/authlib/LoginProfile;
> [K[22:27:55 INFO]: [Geyser-Spigot] OrnateBike8401 hat den Java Server unter der Adresse 95.156.227.148 wegen Connection closed. verlassen
> [K[22:27:55 INFO]: [Geyser-Spigot] Bedrock Benutzter mit der IP /XX.XXX.XXX.XXX wurde getrennt wegen CLOSED_BY_REMOTE_PEER
> [K[22:28:41 INFO]: xXCYANIDEXx issued server command: /geyser dump
> [K[22:28:41 INFO]: [Geyser-Spigot] xXCYANIDEXx hat einen GeyserDump in https://dump.geysermc.org/19j6OFfxchZW7xvU2MdnFtLGVOufkQJI erstellt`

https://dump.geysermc.org/19j6OFfxchZW7xvU2MdnFtLGVOufkQJI

**Comment by Camotoy** [comment]
This is caused by an outdated version of ProtocolSupport. We're likely not going to go out of our way to support older versions of PS (ProtocolSupport doesn't offer support for older versions anyway) - we recommend using ViaBackwards for the best compatibility.
