### ISSUE TITLE
[Question] Hi why to use Floodgate instead of offline mode?

### ISSUE THREAD

**Issue by KeyloHyum** [GeyserMC/Floodgate#95]
I don't understand why it's better to use floodgate, when it mixes up uuids when I remove prefix? And I wanna allow my players to play on same account as they play on java, but then it breaks their uuids... and if I use authme, where's the problem then to have same uuids?

**Comment by Camotoy** [comment]
This is not something we're going to fix. While we allow for offline mode usage, we will not support it nor make accommodations for it.

**Comment by KeyloHyum** [comment]
Then why are you allowing it? I think if you already added this feature that you could fix issues and make it better.

**Comment by Camotoy** [comment]
We don't support piracy.

**Comment by RednedEpic** [comment]
> Then why are you allowing it? I think if you already added this feature that you could fix issues and make it better. And as I see here are multiple issues, so why don't you wanna fix this?

It's _there_ for the sake of testing purposes and for situations such as people running a Bedrock proxy in front of Geyser where an offline mode configuration may absolutely be needed. That being said we do _not_ support offline mode and we do _not_ support piracy.

**Comment by KeyloHyum** [comment]
And floodgate neither? But people could use it to these reasons. But ok, sorry then.
