### ISSUE TITLE
See linked players

### ISSUE THREAD

**Issue by masterhacka** [GeyserMC/Floodgate#96]
Hi there,

is there any way to see statistics of which players are playing Bedrock Edition with a linked account?

**Comment by EasyClifton** [comment]
As far as I know there is a method in the Floodgate API. Though as a note, Floodgate is currently being rewritten and the rewite will have a new API. Also, please ask these sorts of questions on our [Discord server](https://discord.geysermc.org) in the future. Thank you.

**Comment by Tim203** [comment]
If you're talking about the API, that is already possible like EasyClifton said.
But #64 already covers this if you're talking about admin commands.
