### ISSUE TITLE
[floodgate-2.0] skins issues

### ISSUE THREAD

**Issue by LegacyGamerHD** [GeyserMC/Floodgate#99]
skeep in mind this isn with `send-floodgate-data: true`

sometimes skins dont change when switching servers on bungee or sometimes slow

when changing skin on home menu and  rejoin the old skin apears

plz dont close as i had todo this from tim https://discord.com/channels/613163671870242838/744287608217272351/794994827623137332

**Comment by Tim203** [comment]
Does this issue still happen?

**Comment by LegacyGamerHD** [comment]
> Does this issue still happen?

Cant test it as floodgate froze load up the last time I tested it

**Comment by LegacyGamerHD** [comment]
> > Does this issue still happen?
> 
> Cant test it as floodgate froze on load up the last time I tested it

**Comment by Tim203** [comment]
That has been fixed. See https://github.com/GeyserMC/Floodgate/issues/125
